### ISSUE TITLE
Base character gets ignored when scanning Thai text starting with a diacritic on Firefox

### ISSUE THREAD

**Issue by peldas** [themoeway/yomitan#1002]
**Description**
With Thai, when i scan the วันเสาร์ on [this page](https://ja.wiktionary.org/wiki/%E0%B8%A7%E0%B8%B1%E0%B8%99%E0%B9%80%E0%B8%AA%E0%B8%B2%E0%B8%A3%E0%B9%8C) it seems to only pick it up from the ◌ั (incorrect), but the search page picks it up from the ว (correct).
![image](https://github.com/themoeway/yomitan/assets/13115959/7ca28e00-3951-4ab0-b26b-a41435d77283)
![image](https://github.com/themoeway/yomitan/assets/13115959/ce6db623-5ae6-4ce8-a7cc-68f5692d1708)

**Browser version**
Firefox 127.0b6 (64 ビット)

**Yomitan version**
24.5.14.1

**Comment by StefanVukovic99** [comment]
I can reproduce this on firefox, on chrome it's possible to scan starting from either character depending where you aim.

**Comment by peldas** [comment]
Update: `scan text at selection` and `scan selected text` shortcuts work perfectly so it's just the scanning with the cursor that's buggy.
