### ISSUE TITLE
Pitch accent dictionary is not linked from project page or dictionaries.md

### ISSUE THREAD

**Issue by lostfictions** [themoeway/yomitan#1014]
Hi there, thanks for this project! I've been a happy user of Yomichan for a few years, so I'm glad to discover that the torch has been passed to new developers.

I'm setting up Yomitan with a fresh configuration (rather than importing anything from Yomichan). One hitch I ran into is that there don't seem to be any pitch accent dictionaries listed on the main project README or in [`dictionaries.md`](https://github.com/themoeway/yomitan/blob/master/docs/dictionaries.md#recommended-dictionaries) (as linked from the main README as "recommended dictionaries").

At first I wondered if pitch accent display was integrated somehow, since the README has a section mentioning the Kanjium license -- but I couldn't get pitch accent information to display at all.

Finally, I went to the [Yomichan repo's Dictionaries section](https://github.com/FooSoft/yomichan#dictionaries) and grabbed `kanjium_pitch_accents.zip` and imported it. That fixed it!

If I had been a new user of Yomitan, _I would simply have assumed that pitch accent display functionality was broken_. Is there any reason `kanjium_pitch_accents.zip` or an equivalent isn't linked in `dictionaries.md`?

**Comment by MarvNC** [comment]
Removed: #227

**Comment by lostfictions** [comment]
@MarvNC Thanks for the response!

Am I to understand that there's no legitimate pitch accent support for Yomitan now, then? Will it be removed as a feature?

**Comment by MarvNC** [comment]
The feature is supported, there just won't be any dictionaries linked in the docs.

**Comment by aehlke** [comment]
I am not a lawyer / not legal advice but I don't believe raw pitch accent data can be copyrighted as it is factual

**Comment by Kuuuube** [comment]
That is correct. But a specific arrangement of facts may be copyrightable. I'm unsure if this protects a pitch accent dict but it might.

Japanese copyright law also has to be considered here.

If we cannot confidently say whether this is legal, Yomitan will err on the side of caution.

**Comment by ImenaOphelia** [comment]
> I am not a lawyer / not legal advice but I don't believe raw pitch accent data can be copyrighted as it is factual

A lot of countries protect databases like this (e.g. Poland – https://sip.lex.pl/akty-prawne/dzu-dziennik-ustaw/ochrona-baz-danych-16916843). It depends on the legislature you're in, but as Kuuuube said, there's no point in risking.
