### ISSUE TITLE
Add helper text on "No results found" popup

### ISSUE THREAD

**Issue by jamesmaa** [themoeway/yomitan#1029]
We have a "No results found" text that shows up our popup and search occasionally. I'm willing to bet a good portion of users who see this popup have not installed or enabled a dictionary

This task involves adding a conditional helper text to the "No results found" that helps users understand potential reasons why results are not showing up

**Comment by SalwynnJP** [comment]
It could be even better if each part was written for each langage (see below in JP for ex)
Other suggestion : it could be cool if some sections were added to facilitate the research (で始まる etc...)
![スクリーンショット 2024-06-22 063152](https://github.com/themoeway/yomitan/assets/156306448/63a4c2b7-141b-4a1f-8c8c-ce53019cde37)
![スクリーンショット 2024-06-22 063251](https://github.com/themoeway/yomitan/assets/156306448/623ccdce-a633-469d-b017-9e16047d1b90)
![スクリーンショット 2024-06-22 061905](https://github.com/themoeway/yomitan/assets/156306448/c8ba08a7-f639-4f88-a076-1911b9c64025)

**Comment by khaitruong922** [comment]
Maybe show something like this in case the user does not enable any dictionary.

No dictionaries have been installed or enabled yet.
[Go to Dictionaries settings](#)

**Comment by jamesmaa** [comment]
> Maybe show something like this in case the user does not enable any dictionary.

The thing is that the "no results found" popup is a static string, so it would be a bit more work do add the conditional logic. I guess we could do that 🤔

**Comment by jamesmaa** [comment]
#1220
