### ISSUE TITLE
Unable to import zipped `jitendex-mdict-2024-06-02`

### ISSUE THREAD

**Issue by akacoda1** [themoeway/yomitan#1033]
I downloaded `jitendex-mdict-2024-06-02` from the [https://jitendex.org/](url) and I get the error of 
"Error: No dictionary index found in archive"

![image](https://github.com/themoeway/yomitan/assets/143565784/e7730629-5ad8-43d5-92bc-71ce7c63cc5a)

Current Chrome build im using: Extension version: Yomitan (development build) 24.6.3.0

I've have also tried to import `jitendex-mdict-2024-06-02`  on the base build of yomitan 
"Extension version: Yomitan 24.5.21.0"
and got the same error 

here's my exported settings for the dev build im running: [yomitan-settings-2024-06-06-04-32-13.json](https://github.com/user-attachments/files/15603355/yomitan-settings-2024-06-06-04-32-13.json)

**Comment by jamesmaa** [comment]
I just tried repro'ing in my own setup by downloading the zip in [this link](https://github.com/stephenmk/stephenmk.github.io/releases/download/v4.7-7/jitendex-yomitan-2024-06-02.zip), then importing the zip. Could you upload the `jitendex-mdict-2024-06-02.zip` file you used?

**Comment by MarvNC** [comment]
> Download Jitendex for Yomitan and import it into Yomitan. You do not need to unzip the file.

Please download the Yomitan version.

**Comment by akacoda1** [comment]
says file size is to big 

> > Download Jitendex for Yomitan and import it into Yomitan. You do not need to unzip the file.
> 
> Please download the Yomitan version.

ah, I downloaded both and was trying to upload the mdict instead of the yomitan without noticing. thank you
