### ISSUE TITLE
Three or four finger tap scans for Japanese

### ISSUE THREAD

**Issue by seanblue** [themoeway/yomitan#1038]
**Description**
For some reason, doing a three or four finger tap on my trackpad scans for Japanese and opens the dictionary popup. I ran into this when using the three finger tap to open a link in a new tab (I have the three finger tap in Windows set to mimic the middle mouse button). I thought at first that this could be related to the scan while scrolling feature since you scroll with the middle mouse button (wheel), but I have that setting disabled. Additionally, I noticed that this also happens with a four finger tap and even when I change my Windows setting for the three and four finger taps to do nothing, so I don't think that's actually related.

**Browser version**
Chrome 125.0.6422

**Yomitan version**
24.5.21.0

**Comment by seanblue** [comment]
@Kuuuube I disabled the touch and pen inputs in the second option, but it still happened. In the end, I entirely deleted the second option and also unchecked all touch and pen options within the advanced settings of the first option. Even with all that the issue still occurs. I'll also add that I can't get it to scan by actually touching my touch screen.

![image](https://github.com/themoeway/yomitan/assets/5884067/0a14c17c-5008-4eeb-aaf4-776fb45bca4e)

**Comment by seanblue** [comment]
Any update on this issue?

**Comment by Kuuuube** [comment]
Sorry forgot to test this. Just gave it a try now and I can't replicate this behavior. It's probably something specific to your device configured by the vendor.

Doesn't mean we can't fix it but since I can't replicate it I can't really help here.

**Comment by seanblue** [comment]
@Kuuuube I had only installed Yomitan the day I reported the issue, so I think I was using default settings at the time.

From a little bit of research, I just confirmed that the JavaScript `wheel` event will detect scrolling on the trackpad with a `ctrlKey` value of `false` and it'll detect a pinch-to-zoom with a `ctrlKey` of `true`. Now, those are both two finger actions (which don't trigger Yomitan popups), but I wonder if the three finger tap is sending some event that does include the Shift key for scanning. I can't find one that does that. (I didn't check many, but `pointerdown` for example is `false` for `shiftKey` on triple finger tap.)

I do think it's related to this though. When I have the scanning key set to `Shift` or `Ctrl` this issue occurs, but not when I have it set to `Alt.` I only started using Yomitan (instead of Yomichan) right before I reported this, so I never used an earlier version. But @prismflasher seemed to think it was a new problem in June. Does anything from the latest release back in June ring a bell?

**Comment by Kuuuube** [comment]
At some point we did add the ability to scan without moving the cursor. It's possible that indirectly exposed this issue. If you can show the full event details for this i can try to get a fix in.

**Comment by seanblue** [comment]
How do I get the full event details? Not sure if there's some debug setting within Yomitan you're talking about, but if you just mean manually listening to the event I'd need to know which event to listen to.

**Comment by seanblue** [comment]
@Kuuuube Ah, never mind I see it. I get three `keydown` events with a triple tap on my trackpad. For `ctrlKey` and `shiftKey` respectively, the first is `false` / `false`, the second is `true` / `false`, and the third is `true` / `true`.

Here are the full events.

1.
```json
{
    "isTrusted": true,
    "key": "Meta",
    "code": "",
    "location": 0,
    "ctrlKey": false,
    "shiftKey": false,
    "altKey": false,
    "metaKey": true,
    "repeat": false,
    "isComposing": false,
    "charCode": 0,
    "keyCode": 91,
    "detail": 0,
    "sourceCapabilities": {},
    "which": 91,
    "type": "keydown",
    "currentTarget": null,
    "eventPhase": 0,
    "bubbles": true,
    "cancelable": true,
    "defaultPrevented": false,
    "composed": true,
    "returnValue": true,
    "cancelBubble": false,
}
```

2.
```json
{
    "isTrusted": true,
    "key": "Control",
    "code": "ControlLeft",
    "location": 1,
    "ctrlKey": true,
    "shiftKey": false,
    "altKey": false,
    "metaKey": true,
    "repeat": false,
    "isComposing": false,
    "charCode": 0,
    "keyCode": 17,
    "detail": 0,
    "sourceCapabilities": {},
    "which": 17,
    "type": "keydown",
    "currentTarget": null,
    "eventPhase": 0,
    "bubbles": true,
    "cancelable": true,
    "defaultPrevented": false,
    "composed": true,
    "returnValue": true,
    "cancelBubble": false
}
```

3.
```json
{
    "isTrusted": true,
    "key": "Shift",
    "code": "ShiftLeft",
    "location": 1,
    "ctrlKey": true,
    "shiftKey": true,
    "altKey": false,
    "metaKey": true,
    "repeat": false,
    "isComposing": false,
    "charCode": 0,
    "keyCode": 16,
    "detail": 0,
    "sourceCapabilities": {},
    "which": 16,
    "type": "keydown",
    "currentTarget": null,
    "eventPhase": 0,
    "bubbles": true,
    "cancelable": true,
    "defaultPrevented": false,
    "composed": true,
    "returnValue": true,
    "cancelBubble": false
}
```

**Comment by Kuuuube** [comment]
Unfortunately those events dont have anything special about them to differentiate them from legitimate shift, ctrl, or meta key presses so there wont be any way to filter them out on yomitan's end.

**Comment by seanblue** [comment]
Could you perhaps add back the requirement for cursor movement to trigger the scan as a setting? I have no idea why that was changed, so if that doesn't make sense for some reason let me know.

**Comment by Kuuuube** [comment]
No. It can be a quite bad user experience to have to move the cursor and press a modifier at the same time in some circumstances and some setups.

There is a chance of adding an advanced option to disable it.

**Comment by seanblue** [comment]
Yeah I understand why it was changed. Hopefully an advanced option is possible to let people fix this trackpad situation.

**Comment by szdarkhack** [comment]
I want to second the addition of an option to turn this behavior off (scanning without movement). I've run into the same issue with the three-finger taps as well, but the far more annoying issue is using some keyboard shortcuts that contain Yomitan's modifier key in japanese websites (a common example being Alt+Shift+F to focus the search bar in various wikis). In that case, unless the cursor happens to be on a blank spot (which is fairly rare), the key chord gets eaten by Yomitan (and the dictionary opens up), which is extremely annoying.

I understand the reasoning behind the change, but adding that option would be HIGHLY appreciated.
