### ISSUE TITLE
Add setting to hide example sentences

### ISSUE THREAD

**Issue by seanblue** [themoeway/yomitan#1039]
I just switched from Yomichan to Yomitan and decided to try the new recommended Jitendex dictionary over JMdict. However, I find the example sentences highly distracting. I could of course request a version of Jitendex without example sentences over on that github, but if the Yomitan dictionary format allows for it, I think a native setting to disable example sentences would be better.

**Comment by Kuuuube** [comment]
This isn't possible. Put in an issue with jitendex or use yomitan's custom css to select that element and hide it.
