### ISSUE TITLE
Change Spanish's example text to leer

### ISSUE THREAD

**Issue by jamesmaa** [themoeway/yomitan#1052]
The current spanish example text is `acabar de`, which I feel like is not a good example text

<img width="987" alt="image" src="https://github.com/themoeway/yomitan/assets/2382537/f4229754-4ec9-4996-b861-9e425b96fae9">

> The example text is usually some form of the verb "to read" in your language, but it can be any example you feel is good. This will be shown in the preview popup on the settings page.

I think going with `leer` ("to read" in Spanish) or some conjugated version will be better

**Comment by louisv20** [comment]
Is there anyone working on this? May I make the adjustment?
