### ISSUE TITLE
Strip a field of any html when you create a note

### ISSUE THREAD

**Issue by aramrw** [themoeway/yomitan#1061]
When you create an a note, does Yomitan have any way you strip the html and only leave the textContent when it adds it with Anki Connect?

The reason is because of https://ankiweb.net/shared/info/1565434616. 
Sometimes the definitions are heavily nested in useless divs, it messes with this plugin, and sometimes even how Anki displays it. 大辞林第四版 is especially bad for this, it will break almost every time, which requires me to go back to the definition and re-paste it into Anki.

You can see here the definition is really only a couple sentences, but it's deeply nested in a bunch of elements.
https://pastebin.com/EBUKnj88

Would really appreciate some kind of way to fix this

**Comment by Kuuuube** [comment]
Are you aware of the result of stripping html from that? This is what it would look like:

`ひしょ[2]【避暑】（名）スル夏の暑さを避けるために涼しい土地へ行くこと。⇔避寒。Image夏。「軽井沢へ━に行く」「別荘の設が有つて、例年必ず其処へ━する／婦系図（鏡花）」避暑地←夏暑い時期に暑さを逃れて涼しい場所へ行く事。概要夏場の暑い時期に、暑さを逃れて快適に暮らす目的で涼しい地域へ行って過ごす事。日本では明治時代に外国人によって始められ、富裕な日本人も行うようになった。海辺や高原が避暑地として人気があるが、エアコンが普及してからは都会の喫茶店や商業施設、公共施設もまた避暑スポットとして良く使われるようになった。関連記事残暑見舞い・暑中見舞い・日本の夏・夏の風物詩・熱帯夜Image pixivで読む避暑（ひしょ）とは、一時的に涼しい場所に移ることで夏の暑さを避けること。続きを読む`

**Comment by aramrw** [comment]
> Are you aware of the result of stripping html from that? This is what it would look like:
> 
> `ひしょ[2]【避暑】（名）スル夏の暑さを避けるために涼しい土地へ行くこと。⇔避寒。Image夏。「軽井沢へ━に行く」「別荘の設が有つて、例年必ず其処へ━する／婦系図（鏡花）」避暑地←夏暑い時期に暑さを逃れて涼しい場所へ行く事。概要夏場の暑い時期に、暑さを逃れて快適に暮らす目的で涼しい地域へ行って過ごす事。日本では明治時代に外国人によって始められ、富裕な日本人も行うようになった。海辺や高原が避暑地として人気があるが、エアコンが普及してからは都会の喫茶店や商業施設、公共施設もまた避暑スポットとして良く使われるようになった。関連記事残暑見舞い・暑中見舞い・日本の夏・夏の風物詩・熱帯夜Image pixivで読む避暑（ひしょ）とは、一時的に涼しい場所に移ることで夏の暑さを避けること。続きを読む`

Yes thats perfect, that's already what I have to do to get it work with kotu. Kotu will break if there is any formatting, even a single span that has a background color

**Comment by aramrw** [comment]
My apologies, I thought Yomitan took feature requests, it but it seems that's not actually not the case. Might want to remove that section so someone doesn't accidentally ask for something
