### ISSUE TITLE
[STRUCTURED-CONTENT] Possibility to add audio files (like examples sentences, etc...) when making dict ?

### ISSUE THREAD

**Issue by SalwynnJP** [themoeway/yomitan#1069]
Hello,
I'm wondering if it's possible to directly add audio files within a dictionary. If so, what is the procedure to follow to add them in a JSON file (structured-content)?
Unlike the existing pronunciations on Yomitan, these could be "examples sentences" or something else. I would like to test this.
I'm asking this here because as far as I know, there aren't any existing parameters in the terms_meta_bank schema for this.
![スクリーンショット 2024-06-14 192935-overlay](https://github.com/themoeway/yomitan/assets/156306448/eedc886a-2150-4461-9885-62c5f58f517d)

**Comment by stephenmk** [comment]
> I'm asking this here because as far as I know, there aren't any existing parameters in the terms_meta_bank schema for this.

There aren't. I made an issue as well (#324)

**Comment by Kuuuube** [comment]
Closing as duplicate.
