### ISSUE TITLE
Changing appearance of Hanzi/Kanji

### ISSUE THREAD

**Issue by Azv121** [themoeway/yomitan#1074]
I just switched over from yomichan to yomitan. How do I change the appearance of the hanzi to have the same as yomichan. Yomitan looks bold whereas yomichan is regular font.
![yomitan](https://github.com/themoeway/yomitan/assets/142043934/3ed2b38d-65fd-47c7-8796-5c6d67dcda12)

**Comment by Kuuuube** [comment]
I thought this was fixed with #979. Do you have Chinese selected in settings? And are you sure you weren't using a Japanese font to display it previously? Language tags should be getting set correctly now so if you have Chinese selected you should get a Chinese language tag set for that element.

**Comment by Kuuuube** [comment]
On second thought it may be #979 that "broke" this for you. If you were using a Japanese font previously.

**Comment by MarvNC** [comment]
Yeah, as we can see with the Yomichan screenshot there's a different font being used on both characters. Here it appears that 他 is rendered with a Japanese gothic font while 們 is rendered with a fallback Ming/Mincho font that's actually Chinese. If you want to have the headwords rendered with a different font you can use CSS to specify it.
```css
.headword-term {
  font-family: 'Example font name';
}
```

**Comment by Azv121** [comment]
Yes Chinese setting is selected in the settings menu.
After playing around with a few fonts I found '微軟正黑體' to be an ideal font.
Thanks.

![reg1](https://github.com/themoeway/yomitan/assets/142043934/dfd5d80a-4d03-46bc-972d-9cbcd28aead0)

**Comment by Kuuuube** [comment]
Closing as this appears to be resolved.
