### ISSUE TITLE
JMDict shows up at the top no matter where I put in in the priority list

### ISSUE THREAD

**Issue by MangoHusky** [themoeway/yomitan#1106]
**Description**
After reinstalling Yomitan and importing my settings and dictionaries, no matter what I do, JMDict always appears at the top of the pop up. The only way I can get it to go away is to disable it, and while I don't want it to be at the top, it is useful to have it down the list.

[Video demonstrating the issue](https://streamable.com/kda3v6)

**Browser version**
Microsoft Edge
Version 126.0.2592.61

**Yomitan version**
Yomitan 24.6.10.0

**Exported settings file**
[yomitan-settings-2024-06-21-05-50-22.json](https://github.com/user-attachments/files/15923300/yomitan-settings-2024-06-21-05-50-22.json)

**Comment by Kuuuube** [comment]
Enable advanced and check the priority of them. You probably have a higher priority set for jmdict in that settings file.

You should set all priority numbers to 0. The priority numbers shouldnt be used anymore now that dict sorting by order has been fixed.

**Comment by MangoHusky** [comment]
That was the problem, thank you!
