### ISSUE TITLE
Blocking input bar even by scrolling

### ISSUE THREAD

**Issue by SalwynnJP** [themoeway/yomitan#1113]
Current Behavior

https://github.com/themoeway/yomitan/assets/156306448/f527c32e-0268-4241-b0e0-aa8ad2dac5d1

Expected Behavior

https://github.com/themoeway/yomitan/assets/156306448/14316ba5-0100-4318-a526-a5be94249cd6

**Comment by SalwynnJP** [comment]
maybe smth like :

.search-header {
    position: sticky;
    top: 0;
    z-index: 1000;
    background-color: var(--background-color); 
    padding-bottom: 1em;
}

???

**Comment by Kuuuube** [comment]
Give  #1114 a test. I think making the entire header sticky is a bad idea. But only the search and search query is good.
