### ISSUE TITLE
Not working in chrome extension windows (LINE)

### ISSUE THREAD

**Issue by Viterkim** [themoeway/yomitan#1118]
**Description**
Trying to lookup stuff in a chrome extension (either the embedde window, or by taking the URL [chrome-extension://ophjlpahpchlmihnnnihgmmeilfjmjjc/index.htm] in a tab.

Trying to manually add 'chrome-extension://*/*' as an allowed origin in [chrome-extension://likgccmbimhjbgkjambclfkhldnlhbnn/permissions.html] gives the message `Invalid value for origin pattern chrome-extension://*/*: Invalid scheme.`

Link to the example extension
https://chromewebstore.google.com/detail/line/ophjlpahpchlmihnnnihgmmeilfjmjjc?hl=en

**Browser version**
Brave
[Version 1.67.119 Chromium: 126.0.6478.114 (Official Build) (64-bit)](https://brave.com/latest/)

**Yomitan version**
Extension version: Yomitan 24.6.10.0
Platform: Windows
Browser: Chrome
Language: en-US

**Comment by djahandarie** [comment]
AFAIK this is simply not possible in Chrome. Unless you have some evidence otherwise I don't think there's much that can be done.

**Comment by Kuuuube** [comment]
Yep this is explicitly disallowed in all major browsers. We cannot fix this. See:

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns#scheme
https://developer.chrome.com/docs/extensions/develop/concepts/match-patterns?hl=en
https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/match-patterns

**Comment by Viterkim** [comment]
ahh okay! do you know if it would be possible to do something like, hosting a local service that would proxy it from a normal http server? (locally ofcourse). Then i could just make something like that and leave it running.
