### ISSUE TITLE
(Firefox) Welcome page pops up randomly if enabled

### ISSUE THREAD

**Issue by Aquafina-water-bottle** [themoeway/yomitan#112]
Manifest version 3 changes persistent background pages to service workers, which has the following side effect:

> Service workers are ephemeral, which means they'll likely start, run, and terminate repeatedly during a user's browser session. It also means that data is not immediately available in global variables since the previous context was torn down. [^1]

Due to this, [this line in backend.js](https://github.com/themoeway/yomitan/blob/451b7f429414bedeb0e363b474c9b43429c48045/ext/js/background/backend.js#L241) keeps getting ran, and opens up the welcome page pretty much arbitrarily.

As noted in the mv3 migrating page, a potential solution is to use [`chrome.storage`](https://developer.chrome.com/docs/extensions/reference/storage/#storage-areas) (and in particular, [`storage.session`](https://developer.chrome.com/docs/extensions/reference/storage/#property-session))

~~Only tested on Chromium so far, unsure if the behaviour is the same on Firefox.~~
Fixed for Chrome in #113, but bug still exists for Firefox.

[^1]:  https://developer.chrome.com/docs/extensions/migrating/to-service-workers/#persist-states

**Comment by Aquafina-water-bottle** [comment]
As mentioned in #113, this issue still exists for Firefox because `storage.session` isn't implemented, so this issue will be re-opened for the time being.

**Comment by EwanFox** [comment]
It appears storage.session now exists in Firefox: (https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/session)
