### ISSUE TITLE
Add an ability to capture all punctuation at the end of a sentence

### ISSUE THREAD

**Issue by rduwjjnh** [themoeway/yomitan#116]
Currently, if a sentence ends with `？！”`, for example, Yomi will only capture the question mark. Would be nice if it could capture all symbols that are specified as sentence terminators until there aren't any.

**Comment by djahandarie** [comment]
Could you add an example of where/why this would be useful?

**Comment by Aquafina-water-bottle** [comment]
As a workaround, you can try playing around with the termination characters (set to newlines only) and "Layout-aware scanning" settings. This will likely capture the entire paragraph, but it will at least preserve the termination characters.

**Comment by rduwjjnh** [comment]
> Could you add an example of where/why this would be useful?

It's purely cosmetic, so the cards look neat.
