### ISSUE TITLE
Yomitan causes theme to reset daisyui

### ISSUE THREAD

**Issue by Issue-maker-9000** [themoeway/yomitan#1166]
**Description**
Scan japanese text using yomitan on [DaisyUI](https://daisyui.com/docs/install/?lang=ja) with a different theme than the default.
Older version(24.01.14.0 ) in ungoogled chromium 126.0.6478.126-1 does not have this issue, same for the latest release on chromestore (this release is behind the FF release)
Issue started for me since the last update that has been pushed on 2024/7/1

**Browser version**
Firefox 127.0.2

**Yomitan version**
Yomitan 24.6.24.0

**Exported settings file**
Settings do not matter, but tested after reset.

**Comment by Kuuuube** [comment]
Can you explain how daisyui works with yomitan? Are you dropping the daisyui css file into yomitan's custom css?

**Comment by Issue-maker-9000** [comment]
No daisyui is a tailwind plugin, but it has themes that you can change on the toprightside on that link I posted.

If you scan the japanese text on that page the daisyui theme will reset to what its default, nothings happens to yomichan itself.

What theme is used is set by an attribute on the root element of the webpage.
