### ISSUE TITLE
Add option to convert audio to mp3 on card creation

### ISSUE THREAD

**Issue by bgs6** [themoeway/yomitan#1170]
The audio from the newly added audio source (Wiktionary) is of type ogg.

Ogg/Opus is not supported on iOS.

I suggest adding a feature that converts any unsupported audio types to a supported one when creating an anki card.

This will also be useful for those who want to have a lighter local-audio server.

[local-audio-yomichan](https://github.com/themoeway/local-audio-yomichan?tab=readme-ov-file#steps)

As of now if you want the audio to work on iOS you have to download the MP3 audio which is almost 2x the size.

**Comment by Kuuuube** [comment]
Closing as this is unfortunately very rough to implement with current browser apis and is best done in anki instead of yomitan.
