### ISSUE TITLE
Add an option to ignore brackets

### ISSUE THREAD

**Issue by emanuelps2708** [themoeway/yomitan#1181]
Hi, I think it would be great to add this feature, either by ignoring the brackets and the contents inside it, or only ignoring the brackets (to search the term with kana). The reason is because some dictionaries that contain rare kanji might show the reading of that said kanji in brackets, so it doesn't make possible to scan the term.
Example :

嚙ませる。

![image](https://github.com/themoeway/yomitan/assets/147004033/8ce1b6a1-4d5c-4b55-b54c-e79c4b933f6c)

**Comment by StefanVukovic99** [comment]
Should be able to do this with text replacements, Advanced > Translation > Configure custom ...
`\(([^)]*?)(?:\)|$)`
![image](https://github.com/themoeway/yomitan/assets/24891609/3b8ccd30-b9ce-4445-99d6-4626fdc2c27c)

**Comment by emanuelps2708** [comment]
It works, thank you so much ;)
![image](https://github.com/themoeway/yomitan/assets/147004033/e7c9f637-308e-46cb-a721-0e84eae7d97a)
