### ISSUE TITLE
Clipboard Monitor firefox window priority

### ISSUE THREAD

**Issue by childishweb** [themoeway/yomitan#1197]
**Description**
The clipboard monitor (for use with other apps) when active on chrome pops-up in-front of all windows, when the same is done with Firefox, the dictionary is hidden behind all primary windows. I'm unsure if this is a bug of Yomitan or a limitation of Firefox. However it makes the clipboard monitor rather obsolete on Firefox, and cumbersome to use. 

**Browser version**
(e.g. Firefox 83.0)

**Yomitan version**
(e.g. 20.11.1.1)

**Comment by Kuuuube** [comment]
Cant replicate. Please provide your settings.

**Comment by Kuuuube** [comment]
Also are you seriously using firefox 83? Is that a typo? We can't guarantee any support for 4 year old browser versions.

**Comment by MarvNC** [comment]
And please specify your browser and Yomitan version.

**Comment by childishweb** [comment]
Oh sorry! I thought it automatically added the version type I didn't read correctly the "e.g." my Firefox version is 128.0 (64-bit) 

Yomitan: Extension version: Yomitan 24.7.1.0
Platform: Mac OS
Browser: Firefox
Language: en-US
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:128.0) Gecko/20100101 Firefox/128.0
AnkiConnect version: 6


Here are my settings file please if there is anything else i can provide let me know. 
[yomitan-settings-2024-07-11-23-56-56.json](https://github.com/user-attachments/files/16184904/yomitan-settings-2024-07-11-23-56-56.json)

**Comment by Kuuuube** [comment]
Thank you. I'm still unable to replicate this. It doesn't appear to be an issue with yomitan. It may be a firefox bug related to macos or something wrong with your firefox settings.

**Comment by childishweb** [comment]
Okay thank you my apologies.
