### ISSUE TITLE
Option to search on pressing Return key on mobile

### ISSUE THREAD

**Issue by khaitruong922** [themoeway/yomitan#1217]
**Browser:** Kiwi Browser

Pressing Return key when searching will make a new line instead of search, it feels kinda unexpected and I have to move my finger up to the top to click the Search button. 

Having an toggle like `Search on Enter` on mobile would feel nice. If user wants to have multiple lines, they can turn it off.

**Comment by jamesmaa** [comment]
I believe this is fixed here https://github.com/themoeway/yomitan/commit/10b826192fba0ad49650d1b905492cb69d49ce38 though it's not toggleable just the default behavior on mobile devices
