### ISSUE TITLE
why don't JMdict (English) specify expressions used with the word?

### ISSUE THREAD

**Issue by Triramama** [themoeway/yomitan#1226]
As seen in the screenshots, the entry for 棒 on Jisho.org references a collocation used with it, but this same collocation isn't listed on yomitan, instead there's just the definition of 棒読み and no expression itself:
![2024-07-14 20-21-57 棒 - Yomitan Search - Chromium](https://github.com/user-attachments/assets/171e40dd-ed12-4e32-b644-cdee01c1d183)
![image](https://github.com/user-attachments/assets/eb1fd1a4-28bf-4c79-ba43-8d55bbc34188)
And those references exist for many very many entries. Is it a problem with yomitan, the dictionary base or is it just a thing only present on jisho? In any case I would really like if the collocation referenced there displayed in Yomitan too or was omitted altogether, because there's a possibility of interpreting that definition as one of the meanings of the searched word.

**Comment by MarvNC** [comment]
You are on an extremely old version of JMdict for Yomitan that is lacking such information; the latest version is available [here](https://github.com/themoeway/jmdict-yomitan) if you want to keep using it.
![msedge_棒_-_Yomitan_Search_and_2_more_pages_-_Dev_-_Micros_2024-07-13_23-47-46](https://github.com/user-attachments/assets/12348535-0e40-4902-bd15-9c4faa083a63)

However we now recommend using [Jitendex](https://github.com/stephenmk/Jitendex) instead.
![msedge_Main_2024-07-13_23-42-53](https://github.com/user-attachments/assets/52819a92-9412-4f28-b887-c19fa523a60c)
