### ISSUE TITLE
Option to hide extra frequency info when using group related terms

### ISSUE THREAD

**Issue by shiki-tm** [themoeway/yomitan#1235]
![image](https://github.com/user-attachments/assets/61a02e3c-00a5-4205-9e33-14a326de9e25)

As you can see it takes up a lot of space.

Thanks to Marv's recent update to the free chinese dictionary CC-CEDICT can now be used with group related terms setting.
But because of the chinese frequency lists we have, theyre basically all based on simplified chinese character corpus. i know the frequency between the scripts isnt the same but gotta work with what we got. because the lists are basically for one script, i dont need to see the extra frequency numbers  in parenthesis since theyre obviously crazy different or the exact same as the opposite character set.  this is just the situation with chinese freq lists but im sure other languages might have similar issues. I just want a setting to turn them off for frequency lists since the info in paranthesis is useless for our situation with chinese lists.

It might also be useful if there was a setting to also just turn off the parenthesis info for all dicts since the way CC-CEDICT is setup it doesnt group all terms with different readings, it only groups simplified and traditional characters in search results. So no worries about confusing different meanings separated by promunciation, those are still separate entries.

![image](https://github.com/user-attachments/assets/9e0c1166-c0dd-4ea3-8371-8897162f26f4)

**Comment by kilowatson** [comment]
![Completely-gone-small](https://github.com/user-attachments/assets/fb577b1b-0f86-4a6c-ad03-d7863606853b)
![Partial-small](https://github.com/user-attachments/assets/d8a21e62-4596-4b29-be22-42fbed8df23b)

Something like one of these?

**Comment by shiki-tm** [comment]
Just the stuff in parentheses, I still want to see the frequency numbers of course

**Comment by kilowatson** [comment]
![Parentheses](https://github.com/user-attachments/assets/b4e7281a-da32-4b6b-bead-7bb951461569)

Is this good?

**Comment by shiki-tm** [comment]
Yes that's good! Can you tell me how did you do this?

**Comment by kilowatson** [comment]
`.frequency-disambiguation{
display: none
}`
Add this line to the popup css

**Comment by shiki-tm** [comment]
thanks for this. is it possible to hide the first frequency number if theres 2 from a freq list?

**Comment by kilowatson** [comment]
`.frequency-body::after, span.frequency-group-item span.frequency-item:not(:first-child) span.frequency-value{
display: none;
}`

**Comment by shiki-tm** [comment]
amazing. tysm!
in case anyone wants to hide the definition parenthesis info i was able to do it with this css:

.definition-disambiguation { display: none }
.definition-disambiguation-list:after,:before{ display: none }
