### ISSUE TITLE
Problems with font on Cyrillic dictionaries

### ISSUE THREAD

**Issue by YukiNagat0** [themoeway/yomitan#1259]
**Description**
After update, on default font (void or "sans-serif") cyrillic dictionaries went crazy. Before addition of Font customization (#1184) entries were displayed correctly.
![Cyrillic](https://github.com/user-attachments/assets/d35d6d80-dfb3-4b91-85ea-abfc211dd97d)

Proposal:

1. Return prior default font
2. ~~Add an option to change font of the specific dictionary (e.g. set a global/base font for all dictionaries and set a different font for the specific dictionaries as exception)~~

For more context: https://discord.com/channels/617136488840429598/1081538711742844980/1265006180028387400

Browser version
Chrome 126.0.6478.183 (64-bit)

Yomitan version
Yomitan 24.7.15.0

**Comment by MarvNC** [comment]
Reproduced on the 7.15 release, it appears to be fixed in the 7.22 development release likely due to #1231.

Having an empty string as the font should be the same as before the font option was added (the font will be `'Helvetica Neue', Helvetica, Arial, sans-serif`).

**Comment by YukiNagat0** [comment]
Fixed in 24.7.24.0 (stable)
