### ISSUE TITLE
New Font family update overwrites CSS by default

### ISSUE THREAD

**Issue by chiascuro** [themoeway/yomitan#1267]
**Description**
The new "Font family" addition under "Appearances" overwrites the font I had set in "custom CSS" by default.
![image](https://github.com/user-attachments/assets/4f1910b4-040a-4449-a8a4-be38f49efb88)
![image](https://github.com/user-attachments/assets/d86483a4-4f7a-48cd-b520-e12469ffbd76)
Only if I now add "Yu Mincho" to the family field does it display correctly again.
![image](https://github.com/user-attachments/assets/56dd8393-8405-41e0-89b0-3c4749f21628)
I use Yomitan on 5 different devices with 4 custom profiles, so I would have to do this change manually at least 20 times in order to fix it everywhere... I don't think this is intended, or well if someone went to the length of adding it in the custom CSS it's safe to assume that the custom CSS should take priority, in my opinion.

**Browser version**
any

**Yomitan version**
Yomitan 24.7.15.0

**Exported settings file**
[yomitan-settings-2024-07-24-14-22-30.json](https://github.com/user-attachments/files/16363501/yomitan-settings-2024-07-24-14-22-30.json)

**Comment by MarvNC** [comment]
This is fixed in #1231, which is reflected in the 7.22 release of Yomitan.
