### ISSUE TITLE
Add support link in info.html asking for support

### ISSUE THREAD

**Issue by jamesmaa** [themoeway/yomitan#1268]
Let's add a support link that links to the ff/chrome store for review?

Something like "Enjoying Yomitan? Help us by writing a review on the Firefox/Chrome store!"

<img width="712" alt="image" src="https://github.com/user-attachments/assets/92be12f8-b548-45f8-adfb-f3f98c27396e">

**Comment by SeanAverS** [comment]
Hello, 

I'm interested on working on this. Could I please be assigned? Thanks.

**Comment by elijahLyons** [comment]
Hey there, I'm interested in this and would like to be assigned.

**Comment by Kuuuube** [comment]
> Hey there, I'm interested in this and would like to be assigned.

Is there a particular reason you want this assigned? Almost everyone who asks this on issues (and the person right above) seem to just disappear after being assigned something.

You don't have to worry about getting this issue assigned before you submit a PR if that's of any concern.

**Comment by elijahLyons** [comment]
I'm new to open source contribution, wasn't sure if I needed it assigned first. Thanks for the heads up. That is puzzling that folks will vanish like that.
