### ISSUE TITLE
(Firefox) Intuitive UI to grant permissions for websites

### ISSUE THREAD

**Issue by Aquafina-water-bottle** [themoeway/yomitan#127]
For Firefox, the extension does not work unless the user explicitly allows Yomitan to work on each individual site, or unless the user stumbles their way into the extension settings -> permissions tab -> set `Access your data for all websites` to `true`. This is expected behavior, as shown below:

> In MV2, host permissions are granted by the user at the time of install and there’s no elegant way for the user to change this setting (short of uninstalling/reinstalling and choosing different permissions). But with the new extensions button in MV3 in Firefox, users will have easy access and persistent control over which extensions can access any web page, at any time. Users are free to grant ongoing access to a website, or make a choice per visit. **To enable this, MV3 treats host permissions (listed in the extension manifest) as opt-in.** [^1]
[^1]:  https://blog.mozilla.org/addons/2022/11/17/unified-extensions-button-and-how-to-handle-permissions-in-manifest-v3/

We can likely use [permissions.request()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/permissions/request) to ask the user to grant the permission automatically on welcome page startup, and include a button somewhere in the welcome page and settings if they still haven't set the permission.

**Additional reading:**

- https://github.com/mdn/webextensions-examples/tree/main/permissions
- https://discord.com/channels/617136488840429598/1081538711742844980/1090137318658158674

**Comment by EwanFox** [comment]
Firefox(and probably all other browsers) only allows requesting permissions in a user input handler, meaning that requesting on welcome page startup isn't possible. The[ permissions page](https://github.com/themoeway/yomitan/blob/master/ext/settings.html) already has a button to request the required permissions, but it's hard to find for users, so the answer is probably to integrate this into the setting/welcome pages.

**Comment by djahandarie** [comment]
Resolved by #214
