### ISSUE TITLE
Show "Search text with non-Japanese characters" optional for Mandarin

### ISSUE THREAD

**Issue by lindseycadwell** [themoeway/yomitan#1283]
[PR 1247](https://github.com/themoeway/yomitan/pull/1247) hid this setting for all languages except for Japanese. This is an issue because this feature toggle is also needed for Mandarin.

**Comment by Kuuuube** [comment]
This setting doesnt apply internally when the language is not set to japanese. It certainly could be expanded to work with other languages that use chinese characters but unhiding the option right now would do nothing.
