### ISSUE TITLE
why is this so slow

### ISSUE THREAD

**Issue by Triramama** [themoeway/yomitan#1286]
i recently updated from yomichan (my version was from mid 2022), and this extension is so incredibly laggy compared to it. if it's just word I'm looking up, it's no biggie, but if i input a sentence it takes ages to process, yes i have a buttload of dictionaries installed and i did have that much on yomichan. except for the 2: "nihongo kyoshi" and "nihongo no sensei", which are just grammar explanations. i mean, since the original dev abonded us, there's no hope for improvent, im just here to vent good day

**Comment by jamesmaa** [comment]
Can you list the dictionaries you have? There are some problematic dictionaries that blow up yomitan

**Comment by Kuuuube** [comment]
I think this is a recent regression. Just tested current stable against some random dev build i had on my phone from a month or so ago. Stable has slowed down tremendously.

Will do some testing to try to narrow this down.

**Comment by Triramama** [comment]
> Can you list the dictionaries you have? There are some problematic dictionaries that blow up yomitan
Like i said the only dictionaries i didn't have on yomichan are the bottom 2, because i couldn't install them.
![image](https://github.com/user-attachments/assets/7adad9e2-f49f-4bbe-a794-0f21932de4ae)
![image](https://github.com/user-attachments/assets/0be0aab3-8da3-4287-beb5-14c4d5e66093)

**Comment by Kuuuube** [comment]
Can you time how long it takes to search in yomitan vs yomichan? Or at least in yomitan if you no longer have access to yomichan. Along with the text youre trying to search.

**Comment by YukiNagat0** [comment]
This is just a guess, but It may be worth to check `Kenrowa` as potential "problematic" dictionary.

**Comment by Triramama** [comment]
> Can you time how long it takes to search in yomitan vs yomichan? Or at least in yomitan if you no longer have access to yomichan. Along with the text youre trying to search.

feels like 10 seconds on average, the more complicated sentence is, the more it struggles, here have a recording, if it helps (don't mind the red boxes, it's my ocr), text I'm trying to search is literally anything in the video i entered a line from sailor moon
https://github.com/user-attachments/assets/bb668acb-4040-4ea1-9aa6-c85abec2c127

**Comment by jamesmaa** [comment]
Not helpful
