### ISSUE TITLE
Search on JMDict form matches text in below form

### ISSUE THREAD

**Issue by khaitruong922** [themoeway/yomitan#1290]
**Description**
![Screenshot_20240731_121146_Gallery.jpg](https://github.com/user-attachments/assets/afa272fb-7cdb-42e0-b281-914f52a29498)

For example, this should not match な in the below form.

**Browser**
Kiwi Browser

**Yomitan version**
24.7.24.0

**Comment by MarvNC** [comment]
Enable `Layout-aware scanning` and text on the next line shouldn't be scanned.
