### ISSUE TITLE
Keep custom dictionary name on update

### ISSUE THREAD

**Issue by Wyzmic** [themoeway/yomitan#1292]
Before the update:
![image](https://github.com/user-attachments/assets/f371f83e-7bb2-46a8-92ce-cd2a217168ef)

After the update:
![image](https://github.com/user-attachments/assets/627c7ec2-5446-4ac3-9f61-a2cd0a8d5657)

I have a custom anki card template with the dictionary name as "英" and I would have to update the template every time I update. But setting that aside, most updatable dictionaries have dates at the end so I would have to update the template regardless. So I'm hoping it'll be a thing in future updates!

**Comment by StefanVukovic99** [comment]
I guess once we have aliases (#1270) we would just need to make it so that dictionary settings are kept on update.
