### ISSUE TITLE
Anki duplicate detection failing on most cards

### ISSUE THREAD

**Issue by RfzVd** [themoeway/yomitan#1301]
**Description**

When viewing a dictionary entry for a word that has already been added to anki, seemingly most of the time the duplicate detection fails, and overwrites the existing card if you press the "Add expression" button (with the "Prevent adding" option chosen in Yomitan Anki options).

[Here's a picture of working detection](https://i.imgur.com/1yTr0CT.png)
[And here's a picture when it's not working, both are from the same browser session](https://i.imgur.com/k6RLC81.png)

**Browser version**

Firefox Extended Support Release 115.13.0esr (64-bit)

**Yomitan version**

24.7.24.0

Anki is on version 24.06.3, AnkiConnect is the newest available via Anki's update function (can't seem to find the version number).

If it seems like a firefox-esr issue, I can try moving to a newer browser version.

**Comment by 4890A** [comment]
Test the output of your card template's key field (Yomitan Settings -> Anki Card Templates -> Test). Sometimes custom handlebars break and add spaces to the field that's being used to duplicate check.

**Comment by RfzVd** [comment]
Would that be what is in the "front" field in Anki? There indeed seem to be a bunch of spaces and linebreaks: [pic](https://i.imgur.com/DDsdshk.png)

If the problem is because the modified template is badly formatted, then I guess it's something to figure out elsewhere and this issue can be closed.

Thanks.

**Comment by 4890A** [comment]
Yeah this appears to be a template issue. You can resetting your template to the new default tempalte and adding any custom handlebars back in. But it may be the case that the custom handlebars themselves need to be modified/updated.

**Comment by RfzVd** [comment]
Okay, it appears that the template had space characters on the "empty" lines that separate the different code blocks and simply deleting those seems to have fixed the issue. So I'll close this and thank you again for helping to fix this.
