### ISSUE TITLE
why english translation is so small in the dictionary

### ISSUE THREAD

**Issue by serene-ding** [themoeway/yomitan#1304]
can the appearance be changed. couldnt find an option to adjust the font of the dictionary example sentences.
![image](https://github.com/user-attachments/assets/95f04967-1bbb-4ed8-a64c-ca7e47c25cd0)

**Comment by MarvNC** [comment]
Please ask in the [Jitendex discussions](https://github.com/stephenmk/Jitendex/discussions).

**Comment by tadorituki** [comment]
this can be changed in custom css
![スクリーンショット 2024-08-10 215832](https://github.com/user-attachments/assets/cb060be1-9b29-4fb1-8586-6fb06b1138ac)
by adding 
`[data-sc-content="example-sentence-b"] {
    font-size: 20px !important;
}`
refer to: https://learnjapanese.moe/yomicss/

**Comment by serene-ding** [comment]
thank you!
