### ISSUE TITLE
Add recommended dicts for non-ja languages

### ISSUE THREAD

**Issue by jamesmaa** [themoeway/yomitan#1331]
We have recommended dicts for japanese. Let's use kty-yomitan as the default for non-ja languages

**Comment by jamesmaa** [comment]
I've determined this should be easy enough to do for beginners. Simply follow this pattern in the original PR https://github.com/themoeway/yomitan/pull/991/files#diff-8701393ea44900b36bbaa8bb2992fe82c6f346c974660de3ced928ed2d56c787R1

**Comment by jamesmaa** [comment]
For dictionary links please refer to here: https://github.com/themoeway/kaikki-to-yomitan/blob/master/downloads.md

**Comment by Mjishu** [comment]
```json
"zh": {
        "terms": [
         {
                "name": "kty-zh-en",
                "downloadUrl": "https://github.com/themoeway/kaikki-to-yomitan/releases/latest/download/kty-zh-en.zip"
            },
            {
                "name": "kty-zh-zh",
                "downloadUrl": "https://github.com/themoeway/kaikki-to-yomitan/releases/latest/download/kty-zh-zh.zip"
            },
            {
                "name": "kty-zh-fr",
                "downloadUrl": "https://github.com/themoeway/kaikki-to-yomitan/releases/latest/download/kty-zh-fr.zip"
            },
            {
                "name": "kty-zh-de",
                "downloadUrl": "https://github.com/themoeway/kaikki-to-yomitan/releases/latest/download/kty-zh-de.zip"
            },
            {
                "name": "kty-zh-ru",
                "downloadUrl": "https://github.com/themoeway/kaikki-to-yomitan/releases/latest/download/kty-zh-ru.zip"
            },
            {
                "name": "kty-zh-es",
                "downloadUrl": "https://github.com/themoeway/kaikki-to-yomitan/releases/latest/download/kty-zh-es.zip"
            }
        ],
        "kanji": [],
        "frequency": [],
        "grammar": [],
        "pronunciation": []
    }
``` Is this how the format should be for non-ja languages? or should it just be the zh-en dictionary? and should I only use the main dictionaries of kaikki or the ipa and extra dictionaries? thanks.

**Comment by jamesmaa** [comment]
Yes. Adding a description and homepage url would be great as well. See ja for example 

Let's only add English for now. If we add too much the modal content overflows and we might not see the grammar and pronunciation dicts. I'm not sure about adding pronunciation IPA dicts for everything since I don't think most people know or care for it besides ja and ah.

**Comment by Mjishu** [comment]
got it! should the homepage url be this https://github.com/themoeway/kaikki-to-yomitan/blob/master/downloads.md or should it be the kaikki page?

**Comment by jamesmaa** [comment]
Downloads sounds good!
