### ISSUE TITLE
Cannot download recommended dictionaries on Firefox

### ISSUE THREAD

**Issue by khaitruong922** [themoeway/yomitan#1350]
**Description**
Click on Download button and nothing happens.

https://github.com/user-attachments/assets/524feadc-9c3a-41be-b411-6bb60e20e4ae

**Browser**
Firefox

**Yomitan version**
24.8.12.1

**Comment by Kuuuube** [comment]
Just tested an I cannot replicate. Maybe theres some bad setting you have enabled in firefox?

**Comment by khaitruong922** [comment]
Does not work on older Firefox versions (mine is installed in 2021 and hasn't updated) where mouse click emits `MouseEvent` instead of `PointerEvent` which stops the download function on this condition.

```
        if (!(e instanceof PointerEvent)) { return; }
```
