### ISSUE TITLE
Add link to edge store in info.html

### ISSUE THREAD

**Issue by jamesmaa** [themoeway/yomitan#1372]
Add link to the extension on microsoft edge to ask for ratings and review

Link: https://microsoftedge.microsoft.com/addons/detail/yomitan/idelnfbbmikgfiejhgmddlbkfgiifnnn

Related: #1268

**Comment by ketansahugit** [comment]
Hi, I'd like to work on this issue. could you please assign it to me?

**Comment by Casheeew** [comment]
Hi, 
we don't often use Github's assignment system. If you feel that you can take on this issue, feel free to open a PR and we will merge it if the changes are desirable.
