### ISSUE TITLE
Touchpad zoom

### ISSUE THREAD

**Issue by LadivItnas** [themoeway/yomitan#1380]
Is it possible for text to shrink relative to the window when using touchpad zoom? Video shows problem.

https://github.com/user-attachments/assets/1b9ec7d7-7ddd-41f0-aa4a-ad758004f447

**Comment by tadorituki** [comment]
Using units "em" instead of "px" for font-size in your custom css should work.

**Comment by LadivItnas** [comment]
Thanks for the reply. Yep, changing font-size under .gloss-content and .tag-label-content both to 1em did the thing. Works perfectly, Thanks!

https://github.com/user-attachments/assets/52610f3d-c918-493e-b858-1fa158da5f3c
