### ISSUE TITLE
History of lookups

### ISSUE THREAD

**Issue by ganqqwerty** [themoeway/yomitan#1381]
It would be great to have access to history of lookups. It can enable several nice use cases. 
### Use case 1: see how often was the word looked up
It's a nice use case, because if the word is looked up often, maybe a learner can do something about it, depending on their strategy: create anki card or write it down for example.

The amount of lookups can be displayed somewhere in dictionary page of the word. 

### Use case 2: aggregation and data analysis of the looked up words. 
If we have a table of lookups we can do analytics in dedicated page or offline. The data science and data visualizations specialists can come up with interesting use cases, but even the simplest drilldowns, sorting and filtering look exciting: 
* my top-10 looked up words this month
* how the amount of lookups changed from previous week to this week
* which domains have the biggest frequency of lookups

### Implementation
A user should be able to turn on the logging, or turn it off. 

At first, the lookup log could be a simple list of items like that:
* datetime of lookup
* word 
* url in which yomitan was called
* title of the window in which yomitan was called
* (context)
* (source of lookup: clipboard, hyperlink inside yomitan, hovering)
* (amount of time spent before closing the yomitan or going to a different yomitan page)

The data is stored somewhere and is available for exporting in csv. 
### Storage considerations
Persistence of the data [seems to be achievable](https://developer.chrome.com/docs/extensions/reference/api/storage). I guess, IndexedDB is a good candidate for a storage. 

The amount of data can be big, so it's nice to consider several settings: 
* the upper limit for the size of the log. After the upper limit is reached, the oldest data entry is deleted
* ability to clean the log to free up some space
* ability to store the log outside of the user's browser, possibly in some webservice. This could be challenging because yomitan can be used in an offline mode

**Comment by Renji-XD** [comment]
multiple times requested, multiples times rejected. see e. g. #48, #741  etc.
