### ISSUE TITLE
Add .avif as a valid extension for images

### ISSUE THREAD

**Issue by Gilfaro** [themoeway/yomitan#1388]
Dictionaries with a lot of images can save a lot of space even when compared to webp.
All of the modern browsers like Firefox or Chrome already have native avif support, so only adding the extension to allowed and mime image/avif. 
You can already use avif if you rename to an allowed extension, but it would be good to have it properly supported.
https://caniuse.com/avif

**Comment by MarvNC** [comment]
Does Anki support avif?

**Comment by Mansive** [comment]
Yes
