### ISSUE TITLE
Some standard 連用形 inflections marked as kansai-ben

### ISSUE THREAD

**Issue by peldas** [themoeway/yomitan#1391]
**Description**
The 連用形 of a word like 給う (たまう) in standard Japanese is たもう as in たもうて/たもうた, but because this differs from the general 五段活用 pattern of う→っ as in 買う→買っ they are marked as "kansai-ben" instead. This is not correct and there should be special logic for the few words which inflect this way. It appears there may be special logic handling this for 問う already if that makes it easier. I have included screenshots of scanning both たもうた and 問うて to show how the results differ.
![image](https://github.com/user-attachments/assets/21dbb8a0-53cf-478b-b4a4-2bef37d1f27f)
![image](https://github.com/user-attachments/assets/cb42b0a9-7976-4ac9-8893-e4648977b8e4)

**Browser version**
Firefox 130.0b9 (64 ビット)

**Yomitan version**
24.8.19.0

**Comment by khaitruong922** [comment]
Looks like we need to refine the logic of irregular verbs and kansaiben -te (-ta) form too. Currently we can conjugate irregular verb using normal rule and Yomitan will still treat it as correct conjugation. For example: 行いて, 問って, 追って, etc.

I suppose that たまう should conjugate same as のたまう, which will result as
![image](https://github.com/user-attachments/assets/2b34a2a0-1787-41d3-9487-704473700152)

Not sure if the conjugation `-ta` -> `kansai-ben` should show up here. I don't know much of how kansaiben -te form works with irregular verb.

**Comment by Casheeew** [comment]
> Looks like we need to refine the logic of irregular verbs and kansaiben -te (-ta) form too. Currently we can conjugate irregular verb using normal rule and Yomitan will still treat it as correct conjugation. For example: 行いて, 問って, 追って, etc.

It is true that it is incorrect, but I also think that it is becoming more common (問って, 追って) in which case we should keep the deinflection.

> Not sure if the conjugation `-ta` -> `kansai-ben` should show up here. I don't know much of how kansaiben -te form works with irregular verb.

Actually according to [Wiktionary](https://en.wiktionary.org/wiki/%E3%81%9F#Usage_notes), these words in Standard Japanese follow the Kansai forms. So it is correct, and just a matter of whether or not it is redundant.
