### ISSUE TITLE
Scan without mouse move does not work when a popup is open

### ISSUE THREAD

**Issue by khaitruong922** [themoeway/yomitan#1398]
**Description**
As title, when opening a popup, move to another word, then stop the mouse and press Shift, new popup is not shown.

https://github.com/user-attachments/assets/8203739c-b01e-42ab-a42e-3e2b5e7bcd27

In the video, I have set the id = 1 for `TextScanner` in the main window and id = 2 for `TextScanner` within the popup and log them into the console.

From what I have debugged, the root cause is that the `keydown` event when pressing Shift does not trigger for the main window after an popup is  opened. It only triggers the event listener within the popup. 

**Browser**
Chrome

**Yomitan version**
24.8.26.0

**Comment by Kuuuube** [comment]
This is known and not possible to fix due to security practices enforced by all browsers (and for good reason). It was noted in the original PR #917 as well.
