### ISSUE TITLE
Can't capture screenshots on firefox

### ISSUE THREAD

**Issue by Aeases** [themoeway/yomitan#1447]
**Description**
Can't capture images on firefox when adding words to anki
![image](https://github.com/user-attachments/assets/8aec2dec-a6fc-40b4-817d-e53d571a5c47)

**Browser version**
Firefox 130
(Linux, Wayland)
It works fine under chromium.
**Yomitan version**
24.9.16.0

**Comment by Kuuuube** [comment]
Duplicate of #1121
