### ISSUE TITLE
Notifications for security advisories turned on?

### ISSUE THREAD

**Issue by stephenmk** [themoeway/yomitan#1455]
I submitted a security advisory to this repo a couple weeks ago. It's not a critical issue, but I asked for someone to acknowledge that it has been seen and nobody has responded. I'm not sure if I'm getting the cold shoulder or if github just hasn't sent notifications to anyone.

**Comment by Kuuuube** [comment]
Might be something with permissions but I cant see it even though I can see other security stuff. Maybe @jamesmaa can take a look.

**Comment by jamesmaa** [comment]
Thanks for reporting! I see it. I'm currently the only active maintainer who can see these advisories. I don't see any notifications in my inbox nor does update any other top-level UI to indicate it's been submitted

I updated my notification settings from this [discussion](https://github.com/orgs/community/discussions/51573#discussioncomment-8939086) that should let me receive new alerts. If you submit a new security advisory, feel free to ping this GH again for followup.
