### ISSUE TITLE
(Chrome) "Search page clipboard text monitoring" not working

### ISSUE THREAD

**Issue by TanJou** [themoeway/yomitan#165]
Both "Enable search page clipboard text monitoring" in Settings and "Clipboard monitor" on a search page are turned on, yet it doesn't automatically search text that's cut or copied. Even after going through and testing all of the settings, nothing works.

**Comment by TanJou** [comment]
> o/ Thanks for the report! What browser are you using (i.e. Chrome, Firefox) and what version? This may be a duplicate of [FooSoft#1247](https://github.com/FooSoft/yomichan/issues/1247)

Version 100.0.4896.60 (Developer Build, ungoogled-chromium) (64-bit). I don't think it's the same issue, as that other one mentions nothing about the built-in search page.

**Comment by Morgawr** [comment]
I'm having the same problem, one of my main usages of yomichan/tan is having it as a standalone window and hook into clipboard and this bug is really stopping me from using it fully :(

**Comment by Morgawr** [comment]
Looks like https://github.com/themoeway/yomitan/pull/278 should have fixed the clipboard monitoring being broken on chromium and I updated to version 23.10.22.0 which is supposed to have the fix, but it's still not working for me. I tried to enable/disable it many times both in the search query window and also in the options but it still doesn't work. Is there anything I can do to help? I tried looking at console logs or anything but I don't see anything weird.

**Comment by praschke** [comment]
we've discovered Morg's problem is due to Chrome not upgrading the service worker. on fresh installs, and under whatever conditions Chrome decides to finish upgrading the service worker, clipboard monitoring on the search page now works.

**Comment by Morgawr** [comment]
I've been using clipboard hooking in the search page 24/7 for the last few days with chrome and it's been working perfectly, I think we can consider this issue fixed, unless we hear reports from other users still having trouble.

**Comment by djahandarie** [comment]
Fixed by #278 (please reopen if not).
