### ISSUE TITLE
Custom URL (Json) not working on Firefox

### ISSUE THREAD

**Issue by Latrolage** [themoeway/yomitan#173]
**Description**
(Describe what the issue is, if it is reproducible, and if possible, how to reproduce it.)
Using firefox, I tried to use https://github.com/themoeway/local-audio-yomichan with yomitan but it would just act as if there was no audio sent back from the addon. (and in console, there was no http request like the other audio sources)

When I tried it with `Version 113.0.5672.126 (Official Build, ungoogled-chromium)` it worked properly.
Edit: it also works properly on the original yomichan (22.10.23.0)

**Browser version**
Firefox 114.0.1 (64-bit)

**Yomichan version**

Version
23.4.7.0

**Exported settings file**
It doesn't work on a clean firefox install with clean yomitan settings (but with jmdict imported)

**Comment by Aquafina-water-bottle** [comment]
Hey @Latrolage,

Can you try navigating through the following:

Click on the Yomitan icon -> Information (question mark circle) -> Permissions (bottom of the page) -> Configure allowed origins… -> Allow access to all URLs (switch on)

![image](https://github.com/themoeway/yomitan/assets/17107540/6529154d-e4cb-4280-85e0-4cb1369449ac)

Likely related to #127

**Comment by Latrolage** [comment]
I checked just now but the option was already enabled.

**Comment by Aquafina-water-bottle** [comment]
Can you send your settings file to make 100% sure nothing about it is off?

**Comment by Latrolage** [comment]
[yomitan-settings-2023-06-10-11-31-53.txt](https://github.com/themoeway/yomitan/files/11712299/yomitan-settings-2023-06-10-11-31-53.txt)

**Comment by Aquafina-water-bottle** [comment]
Settings file looks good, thank you!

Just to make sure:

a) Under `about:addons` (url) -> Extensions -> Yomitan -> Permissions, `Access your data for all websites` is turned on, like the image below:
![image](https://github.com/themoeway/yomitan/assets/17107540/eed4a70a-65be-4731-8923-1023c2b76e27)

b) If you open Anki in the console, are there any messages from the local audio server printed to the console when you try playing audio?

c) What operating system are you on?

Unfortunately, I'm not all too sure what's going on here :(

**Comment by Latrolage** [comment]
a) Yes that's turned on
b) No, nothing at all, and in browser console for yomichan, it doesn't send a http request either.
On the other hand when I do it on chromium, it prints `[]` when there is no audio or something, and it prints: `[{'name': 'JPod101', 'url': 'http://localhost:5050/jpod/よむ - 読む.mp3'}, {'name': 'JPod101 Alt', 'url': 'http://localhost:5050/jpod_alternate/よむ - 読む.mp3'}, {'name': 'NHK16 ヨ＼ム [1]', 'url': 'http://localhost:5050/nhk16/audio/20180221161451.aac'}, {'name': 'Forvo (strawberrybrown)', 'url': 'http://localhost:5050/forvo/strawberrybrown/読む.mp3'}]` when there is a match. The original yomichan does the same.
c) Arch linux

**Comment by Latrolage** [comment]
Ummm, as I was messing around, with yomitan and yomichan, it just started working again. I'm not sure what I changed tbh, I'm still on yomitan 23.4.7.0 but it's fixed.

**Comment by Latrolage** [comment]
Seems to be inconsistent. It's not working properly again.

**Comment by praschke** [comment]
> Ummm, as I was messing around, with yomitan and yomichan, it just started working again. I'm not sure what I changed tbh, I'm still on yomitan 23.4.7.0 but it's working now.

It works whenever I've freshly installed the extension, and stops working after Firefox restarts. When it breaks, calling `declarativeNetRequest.updateDynamicRules` returns with an unexpected error. This is a Firefox bug.
