### ISSUE TITLE
Do you guys intend on publishing new stable updates for the regular add-on stores?

### ISSUE THREAD

**Issue by Tosh0kan** [themoeway/yomitan#198]
Just asking because I don't want to install a specific variant of Firefox to get the most recent updates.

**Comment by Xelieu** [comment]
I'm pretty sure that's the plan

**Comment by djahandarie** [comment]
Yes, that is the plan, once we have a fully functional stable version! Currently still trying to fix bugs surrounding the MV3 migration. Once that is done, we will release stable versions for both Chrome and Firefox, and make an announcement.

**Comment by Tosh0kan** [comment]
That's awesome! Thanks for the reply.
