### ISSUE TITLE
Kanjium appears not to have permission to redistribute pitch information

### ISSUE THREAD

**Issue by kekkoudesu** [themoeway/yomitan#227]
See: https://github.com/mifunetoshiro/kanjium/issues/13

The creator of the repository says:

> It's not listed due to potential copyright issues, but it's from 2-3 legitimate sources.

This implies to me that they do not have permission to use or redistribute that information, and so Yomitan does not have permission to use or redistribute the dictionary.

I am not affiliated with Kanjium or any of the sources from which the information has been sourced, but I thought the maintainers of this repository might like to know. I see a lot of effort has been made to only include freely redistributable dictionaries in the README, so I thought this might have slipped under your radar.

**Comment by MarvNC** [comment]
Another user on the Discord pointed out:

> https://www.edrdg.org/wiki/index.php/JMdict-EDICT_Dictionary_Project#COPYRIGHT
> > Dictionary copyright is a difficult point, because clearly the first lexicographer who published "inu means dog" could not claim a copyright violation over all subsequent Japanese dictionaries. While it is usual to consult other dictionaries for "accurate lexicographic information", as Nelson put it, wholesale copying is, of course, not permissible, and contributors have been advised to avoid direct copying from other sources. What makes each dictionary unique (and copyright-able) is the particular selection of words, the phrasing of the meanings, the presentation of the contents (a very important point in the case of this project), and the means of publication.

> can't really copyright a fact like "俺 is heiban"
