### ISSUE TITLE
Yomitan popup window fails to update, repeatedly showing the same dictionary entry

### ISSUE THREAD

**Issue by soamsy** [themoeway/yomitan#241]
**Description**
After using Yomitan for a reasonable amount of time on a single HTML page, occasionally the popup window gets "stuck", showing the same dictionary entries no matter what word you hover over. Notice how no matter what word I hover over, the dictionary entries for 王国 are all that show up.

https://github.com/themoeway/yomitan/assets/20632064/ccdab51a-f55d-4336-ae5e-afd5852eced0

This can be worked around by refreshing the HTML page you're on whenever it happens. I don't know how to reproduce it reliably yet, but on a fresh profile of chrome with a new install of yomitan with just JMDict (I didn't mess with the default settings), I can **sometimes** reproduce it through some combination of hovering over a word, opening up a new tab, coming back after 30 seconds to 5 minutes, and discovering that I somehow got into this state.

After the problem appears, I start to get errors in my dev console like these (requires you to un-ignore yomitan's content scripts before you can debug/see these errors in the console):
![image](https://github.com/themoeway/yomitan/assets/20632064/ad7ef982-c3ed-4bd1-8b2a-3e5f41c6d740)
```
cross-frame-api.js:173 Uncaught (in promise) Error: Acknowledgement timeout (popupMessage)
    at CrossFrameAPIPort._onError (cross-frame-api.js:173:21)
    at cross-frame-api.js:65:62
_onError	@	cross-frame-api.js:173
(anonymous)	@	cross-frame-api.js:65
await in (anonymous) (async)		
clearAutoPlayTimer	@	popup.js:320
_clearSelection	@	frontend.js:356
_onTextScannerClear	@	frontend.js:311
trigger	@	core.js:409
_triggerClear	@	text-scanner.js:1178
_onMouseDown	@	text-scanner.js:434
```
```
cross-frame-api.js:173 Uncaught (in promise) Error: Acknowledgement timeout (popupMessage)
    at CrossFrameAPIPort._onError (cross-frame-api.js:173:21)
    at cross-frame-api.js:65:62
_onError	@	cross-frame-api.js:173
(anonymous)	@	cross-frame-api.js:65
await in (anonymous) (async)		
showContent	@	popup.js:304
await in showContent (async)		
_showPopupContent	@	frontend.js:613
_showContent	@	frontend.js:603
_onSearched	@	frontend.js:332
trigger	@	core.js:409
_search	@	text-scanner.js:373
await in _search (async)		
_searchAt	@	text-scanner.js:952
await in _searchAt (async)		
_searchAtFromMouseMove	@	text-scanner.js:975
_onMouseMove	@	text-scanner.js:418
```

**Browser version**
Chrome 117.0.5938.62

**Yomichan version**
23.4.7.0 (I downloaded the master branch at commit https://github.com/themoeway/yomitan/commit/94ccff4c790ae8c2ef301bdb4e593f51436b3c8e and loaded the unpacked extension)

**Comment by soamsy** [comment]
Steps to reproduce:
1. Scan a word, leaving the popup's dictionary entries _open_
2. Switch to the extensions page, and wait for the Yomitan service worker to display "inactive"
![chrome_2023-09-15_19-47-29](https://github.com/themoeway/yomitan/assets/20632064/1f0c39b2-b988-4107-9328-df8a02fc7905)
3. Navigate back to where Yomitan's popup was, and click anywhere to close it
4. Any dictionary lookups from now on will fail to display the correct word

So, most likely this is just a symptom of #114 i.e. 30 seconds of inactivity stops the service worker, causing problems like this.

**Comment by praschke** [comment]
the behavior described in #114 is due to a new service worker being installed, not the service worker stopping. this behavior is the main issue caused by the service worker stopping.

in my testing the popup does not need to be left open for the issue to appear.
