### ISSUE TITLE
Can't access settings

### ISSUE THREAD

**Issue by Waterfallls** [themoeway/yomitan#245]
**Description**
![image](https://github.com/themoeway/yomitan/assets/104545378/79382060-a02f-49b0-90c8-4fafff16859f)
Image shows it all. I haven't been using Yomichan for a while, but as I come back to transfer some settings, I can't even get into said settings. I barely was able to reach it on Microsoft Edge, but on chrome it's just flat out impossible. Is there _at least_ another way to access the settings if this can't get fixed or something?

**Browser version**
Chrome Version 116.0.5845.210 (official build)

**Yomichan version**
(development build) 23.8.19.0

**Comment by MarvNC** [comment]
You should be able to access settings through your browser's extension menu. Fix is currently available on Yomibaba.

**Comment by jarmanso7** [comment]
![image](https://github.com/themoeway/yomitan/assets/19256433/bcc48ada-2166-41ef-a15f-e6576221ba73)

**Comment by jarmanso7** [comment]
@MarvNC 

> You should be able to access settings through your browser's extension menu. Fix is currently available on Yomibaba.

Do you have a link to the fix there, please? I would like to take a look

**Comment by forsakeninfinity** [comment]
Hmm, maybe there hasn't been a recent build? Ah yeah, there hasn't been a new build since August.

Pretty sure the CSS fix was also merged here already.

On Yomibaba: https://github.com/forsakeninfinity/yomibaba/commit/199578a6aaf625ab1710df14fe0167dff9385449

On Yomitan: https://github.com/themoeway/yomitan/commit/45d28461d8b120c9a169a262ff724da42b95d654

**Comment by forsakeninfinity** [comment]
Also fwiw, the settings page is just another page so you can just click on the search button then update the URL end in the address bar to `/settings.html` instead of `/search.html` to access it.

**Comment by jarmanso7** [comment]
> Hmm, maybe there hasn't been a recent build? Ah yeah, there hasn't been a new build since August.

@forsakeninfinity Thank you, I've just landed into this project a couple of days ago. So, I take it that there isn't a periodic release cadence, is there it?

**Comment by forsakeninfinity** [comment]
AFAIK, there is CICD that autobuilds stuff after a commit is merged, but it seems it's not auto-released which is probably a good idea but there could be releases after major QoL changes I guess.

**Comment by jarmanso7** [comment]
With the new release of today  23.9.24.0 I confirm the bug is not happening. You may close this bug.
