### ISSUE TITLE
[object Object] for {glossary} when making anki cards through yomitan

### ISSUE THREAD

**Issue by Weroxig** [themoeway/yomitan#246]
**Description**
```html
<div style="text-align: left;">
	<ol>
		<li><i>(1, v5m, vt, JMdict Extra)</i> to read</li>
		<li><i>(1, v5m, vt, JMdict)</i> to read</li>
		<li><i>(2, JMdict Extra)</i> to recite (e.g. a sutra) | to chant</li>
		<li><i>(2, JMdict)</i> to recite (e.g. a sutra) | to chant</li>
		<li><i>(3, JMdict Extra)</i> [object Object]</li>
		<li><i>(3, JMdict)</i> [object Object]</li>
		<li><i>(4, JMdict Extra)</i> to decipher</li>
		<li><i>(4, JMdict)</i> to decipher</li>
		<li><i>(5, JMdict Extra)</i> [object Object]</li>
		<li><i>(5, JMdict)</i> [object Object]</li>
		<li><i>(6, JMdict Extra)</i> [object Object]</li>
		<li><i>(6, JMdict)</i> [object Object]</li>
	</ol>
</div>
```
This is {glossary} for 読め (beautified)

**Browser version**
Firefox nightly 119.0a1 (2023-09-20)
I also tried Firefox stable 117.0.1 (64-bit)

**Yomichan version**
23.8.19.0

**Exported settings file**
[yomitan-settings-2023-09-23-06-58-13.zip](https://github.com/themoeway/yomitan/files/12705830/yomitan-settings-2023-09-23-06-58-13.zip)

**Comment by dtop129** [comment]
I have the same problem, happening only with Firefox, if I try switching to Chromium {glossary} works as expected

Using Firefox 117.0.1

**Comment by jarmanso7** [comment]
@Weroxig  I am trying to reproduce your issue to no avail. Are you using a custom Anki Card Template? Besides the exported settings file (thanks for that), can you also please provide:

1. The dictionaries you are using
2. the dictionary configuration you are using
3. the anki card template you are using

### 1. Dictionaries

You have an option to export your dictionary collection at (Settings -> Backup -> Export Dictionary Collection). The result should be a rather heavy file in the format yomitan-dictionaries-2023-10-03-13-24-26.json:

![image](https://github.com/themoeway/yomitan/assets/19256433/4a28449c-9c33-4283-81f7-8b36f042d8ed)

### 2. Dictionary configuration

What I currently have is probably different than your setup (Settings -> Dictionaries -> Configure installed and enabled dictionaries...:

![image](https://github.com/themoeway/yomitan/assets/19256433/fcc92251-bd7c-46d2-ad66-ecd180920fcb)

### 3. Anki card template

You can find the anki card template (handlebars) if you go to Settings -> Anki -> Configure Anki card templates..., inside the textbox. Make sure you copy all the contents until the last line inside the textbox and save it into a txt file:

![image](https://github.com/themoeway/yomitan/assets/19256433/76edd716-6198-4f2f-a37f-66c47262183c)

**Comment by praschke** [comment]
@jarmanso7 all you need to reproduce is yomitan, firefox, a dictionary with structured data like JMdict Extra, and to test `{glossary}`. i've reproduced this already.

**Comment by praschke** [comment]
@jarmanso7 the sourcemap can be found at https://github.com/Aquafina-water-bottle/handlebars-noeval/raw/master/handlebars.min.js.map

jsyk, Aquafina hasn't been around for a while.

**Comment by jarmanso7** [comment]
@praschke I will try to set the sourcemaps. I am not a frontend developer which means each new step I take I have to learn it on the go, but hopefully I can get it to work. Thanks your your help

**Comment by jarmanso7** [comment]
@praschke Thank you very much!! I just came back here to let you guys know I ran out of time to continue to look into this issue, just to find it already solved. Thank you again.
