### ISSUE TITLE
Clipboard reading not supported in this context error

### ISSUE THREAD

**Issue by Wyzmic** [themoeway/yomitan#269]
When I create any card, I get this sort of popup. The card creation and everything is performed correctly, it's just kind of an eyesore lol
![image](https://github.com/themoeway/yomitan/assets/72083780/de6a51e7-9c75-479d-b79f-d40566ad9846)

Microsoft Edge 117.0.2045.47

(e.g. 23.10.1.0)

I got the following in the inspector console:

Object
ankiNoteErrors: Array(1)
0: Error: Clipboard reading not supported in this context at ClipboardReader.getImage (chrome-extension://glnaenfapkkecknnmginabpmgkenenml/js/comm/clipboard-reader.js:146:19) at Backend._injectAnkiNoteClipboardImage (chrome-extension://glnaenfapkkecknnmginabpmgkenenml/js/background/backend.js:1825:53) at Backend._injectAnkNoteMedia (chrome-extension://glnaenfapkkecknnmginabpmgkenenml/js/background/backend.js:1726:53) at Backend._onApiInjectAnkiNoteMedia (chrome-extension://glnaenfapkkecknnmginabpmgkenenml/js/background/backend.js:463:27) at invokeMessageHandler (chrome-extension://glnaenfapkkecknnmginabpmgkenenml/js/core.js:367:31) at Backend._onMessage (chrome-extension://glnaenfapkkecknnmginabpmgkenenml/js/background/backend.js:329:16) at Backend._onMessageWrapper (chrome-extension://glnaenfapkkecknnmginabpmgkenenml/js/background/backend.js:300:25)
name: "Error"
message: "Clipboard reading not supported in this context"
stack: "Error: Clipboard reading not supported in this context\n    at ClipboardReader.getImage (chrome-extension://glnaenfapkkecknnmginabpmgkenenml/js/comm/clipboard-reader.js:146:19)\n    at Backend._injectAnkiNoteClipboardImage (chrome-extension://glnaenfapkkecknnmginabpmgkenenml/js/background/backend.js:1825:53)\n    at Backend._injectAnkNoteMedia (chrome-extension://glnaenfapkkecknnmginabpmgkenenml/js/background/backend.js:1726:53)\n    at Backend._onApiInjectAnkiNoteMedia (chrome-extension://glnaenfapkkecknnmginabpmgkenenml/js/background/backend.js:463:27)\n    at invokeMessageHandler (chrome-extension://glnaenfapkkecknnmginabpmgkenenml/js/core.js:367:31)\n    at Backend._onMessage (chrome-extension://glnaenfapkkecknnmginabpmgkenenml/js/background/backend.js:329:16)\n    at Backend._onMessageWrapper (chrome-extension://glnaenfapkkecknnmginabpmgkenenml/js/background/backend.js:300:25)"
[[Prototype]]: Object
length: 1
[[Prototype]]: Array(0)
[[Prototype]]: Object

[yomitan-settings-2023-10-03-19-48-02.txt](https://github.com/themoeway/yomitan/files/12796453/yomitan-settings-2023-10-03-19-48-02.txt)

**Comment by djahandarie** [comment]
Interesting... I'm not sure if anyone else testing Yomitan has been using Edge. Does this reproduce on Chrome pr Firefox?

**Comment by Wyzmic** [comment]
> Interesting... I'm not sure if anyone else testing Yomitan has been using Edge. Does this reproduce on Chrome or Firefox?

Yes, I just got it on chrome and imported my dictionaries together with my settings and I get the same thing.

**Comment by Wyzmic** [comment]
With the latest version it's been fixed! Great work guys 🔥
