### ISSUE TITLE
"Clipboard not supported in this context" and "The created card may not have some content" When creating a flashcard for Anki; cannot automatically copy text.

### ISSUE THREAD

**Issue by rikafuruda** [themoeway/yomitan#275]
**Description**
Whenever I create a new Flashcard for my Anki deck, I get two Errors: "Clipboard not supported in this context" and "The created card may not have some content".
The flashcard itself is fine, however any text that I have set up to automatically copy to my flashcard will not copy, meaning i have to do it manually.
I thought it may have been because I took this profile from my old computer and put it into Brave which could've caused some errors, but i have reinstalled yomitan entirely, so this shouldn't happen.
![image](https://github.com/themoeway/yomitan/assets/138363522/21c6cd2b-1889-428f-9d1c-814a1b624d30)

**Browser version**
Brave Browser, 1.59.117 Chromium: 118.0.5993.70 (Official Build) (64-bit) 

**Yomichan version**
Yomitan (development build) 23.10.1.0

**Exported settings file**
[yomitan-settings-2023-10-17-10-51-49.txt](https://github.com/themoeway/yomitan/files/12927748/yomitan-settings-2023-10-17-10-51-49.txt)

**Comment by djahandarie** [comment]
Fixed by #278 (please reopen if not).
