### ISSUE TITLE
Allow blacklisting of individual terms/entries from any dictionaries from the UI

### ISSUE THREAD

**Issue by Morgawr** [themoeway/yomitan#289]
Similarly to the request in https://github.com/themoeway/yomitan/issues/288 I would like to be able to tell yomitan that a certain entry is "bad" and not to show it to me ever again. 

Take for example this entry from the pixiv dictionary:

![image](https://github.com/themoeway/yomitan/assets/184056/cebbc1f0-3466-4772-9763-1a34dcad93d1)

It is not useful to me and I don't want it to show up in my results when I search the word 年 (luckily frequency sorting makes it easier to ignore). It would be nice if I could have a "blacklist" or "filter out" button in next to the anki buttons in the pop-up to let yomitan know I don't ever want to see this entry again.

This would likely require storing some local data about filtered lists/entries and it'd be structured like: `Dictionary name | Entry | Reading` or something like that, and I don't know how feasible it'd be, but it'd be incredibly useful so I don't have to go into the dictionary data itself and manually remove those entries myself.

**Comment by djahandarie** [comment]
Side note, but is XまたはY a common style for pixiv entry furigana? If so, maybe it'd be good for @MarvNC to account for that in his export script

**Comment by Morgawr** [comment]
Yeah in that specific case, cleaning up those entries would definitely help too, but it's also a common problem I have with a lot of other vocabs from other dictionaries too.

**Comment by MarvNC** [comment]
Yep it's in progress https://github.com/MarvNC/yomichan-dictionaries/issues/36

**Comment by jamesmaa** [comment]
I don't think this will get implemented anytime in the near feature, nor do I feel like it's a huge benefit for users. Please react to the original issue if you believe otherwise.
