### ISSUE TITLE
Remove Innocent Corpus

### ISSUE THREAD

**Issue by MarvNC** [themoeway/yomitan#291]
As most people use rank-based frequency dictionaries for sorting now, I think it would make sense to remove Innocent Corpus as it is occurrence-based and often causes confusion among new users.

**Comment by michael-schienbein-fhr** [comment]
isn't this achieved by just not turning on the innocent corpus dictionary?
![image](https://github.com/themoeway/yomitan/assets/7663497/f5ae122b-54ac-4478-9663-6dcf1c16e411)
