### ISSUE TITLE
Can't search within popup anymore.

### ISSUE THREAD

**Issue by wwly23** [themoeway/yomitan#317]
**Description**
Used to work, but now it doesn't. Can't look up words within a J-J definition anymore for example. I can still do it on Chrome with Yomichan. Not sure what changed. Settings are the same. Allow scanning popup content checked. Maximum number of child popups: 5.

**Browser version**
Firefox 119.0.1 (64-bit)
**Yomitan version**
23.11.10.0 (the version I had before this one has the same issue)

**Exported settings file**
(If you think it might be relevant, create a settings export file using the _Export Settings_ button on the settings page; zip or rename the resulting file to .txt to attach to the issue.)

**Comment by jbukl** [comment]
Tested a bit and it looks like it was inadvertently resolved by https://github.com/themoeway/yomitan/pull/316 - just isn't in the release version yet

**Comment by djahandarie** [comment]
I'll release a new version later today with the fix!

**Comment by praschke** [comment]
testing #316, it doesn't look like #315 fixed this

**Comment by praschke** [comment]
sorry, my test install didn't have scanning in the popup enabled. this problem does seem to be resolved.

**Comment by djahandarie** [comment]
@wwly23 Just released the new version, please confirm it's fixed for you once updated!

**Comment by wwly23** [comment]
Perfect! Works great now, thanks guys.
