### ISSUE TITLE
Cannot connect to MeCab anymore as of 23.11.10.0

### ISSUE THREAD

**Issue by uhp00** [themoeway/yomitan#320]
**Description**
Yomitan used to be able to connect to MeCab on 23.10.25.0 by using [Yomichan MeCab Installer](https://github.com/siikamiika/yomichan-mecab-installer) and replacing Yomichan's extension ID with Yomitan's in yomichan_mecab.json.
This doesn't work anymore on the latest 23.11.10.0 and 23.11.12.0 versions, doing the same steps results in a "Cannot connect to native MeCab component" error when testing.

**Browser version**
Brave 1.60.114 but Brave's native messaging is a mess so I also tried on Chrome 119.0.6045.124 to make sure the problem indeed came from Yomitan. Same result on both browsers

**Yomitan version**
23.11.10.0 and 23.11.12.0

**Comment by jbukl** [comment]
Had some troubles setting it up (didn't understand nativeMessaging at all and broke something on my end 😅) but I ended up getting it to work on my end.
My guess it's because of https://github.com/themoeway/yomitan/pull/314/files#diff-4c6a2b1872323412a1d1319aca6d1933e328b745aa5b79d54be77bf8f86e5777R222
You just need to change yomichan_mecab to yomitan_mecab in your registry, or replace yomichan_mecab in the installer file (lines 32, 35 in this file: https://github.com/siikamiika/yomichan-mecab-installer/blob/master/install_mecab_for_yomichan.py#L32)

**Comment by uhp00** [comment]
> Had some troubles setting it up (didn't understand nativeMessaging at all and broke something on my end 😅) but I ended up getting it to work on my end. My guess it's because of https://github.com/themoeway/yomitan/pull/314/files#diff-4c6a2b1872323412a1d1319aca6d1933e328b745aa5b79d54be77bf8f86e5777R222 You just need to change yomichan_mecab to yomitan_mecab in your registry (or whatever is created for your OS), or replace yomichan_mecab with yomitan_mecab in the installer file (lines 32, 35 in this file: https://github.com/siikamiika/yomichan-mecab-installer/blob/master/install_mecab_for_yomichan.py#L32) and rerun the installer.
> 
> Probably should keep this issue open though so it gets noted somewhere in the README (or the repo is forked/cloned and updated) at the very least

Worked, thank you!

**Comment by starxeras** [comment]
Because it seems like the old author isn't active anymore, I changed those small things in a fork. Firefox doesn't work right now because I don't know what to do with the extension ids. Could anyone assist?
https://github.com/starxeras/yomitan-mecab-installer

**Comment by jbukl** [comment]
> Because it seems like the old author isn't active anymore, I changed those small things in a fork. Firefox doesn't work right now because I don't know what to do with the extension ids. Could anyone assist? https://github.com/starxeras/yomitan-mecab-installer

might be this https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_specific_settings needing to be added to the [firefox manifest variant](https://github.com/themoeway/yomitan/blob/master/dev/data/manifest-variants.json#L238)

**Comment by starxeras** [comment]
> > Because it seems like the old author isn't active anymore, I changed those small things in a fork. Firefox doesn't work right now because I don't know what to do with the extension ids. Could anyone assist? https://github.com/starxeras/yomitan-mecab-installer
> 
> might be this https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_specific_settings in the [firefox manifest variant](https://github.com/themoeway/yomitan/blob/master/dev/data/manifest-variants.json#L238)

Tried to put `{cb7c0bec-7085-4f84-8422-7b55a7c4467c}` and all sorts of variations into it and it doesn't seem to work (even taking the id directly from yomitan firefox)

**Comment by jbukl** [comment]
> > > Because it seems like the old author isn't active anymore, I changed those small things in a fork. Firefox doesn't work right now because I don't know what to do with the extension ids. Could anyone assist? https://github.com/starxeras/yomitan-mecab-installer
> > 
> > 
> > might be this https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_specific_settings in the [firefox manifest variant](https://github.com/themoeway/yomitan/blob/master/dev/data/manifest-variants.json#L238)
> 
> Tried to put `{cb7c0bec-7085-4f84-8422-7b55a7c4467c}` and all sorts of variations into it and it doesn't seem to work (even taking the id directly from yomitan firefox)

I just installed the firefox-dev release (although any should probably work) from the Releases page in Firefox (nightly), uncommented the firefox code from your fork and ran it with the extension id from this page:

![image](https://github.com/themoeway/yomitan/assets/148171160/d91b67cb-1fd1-486e-9bd0-3be3518c9a91)
it worked

**Comment by starxeras** [comment]
I have fixed the repository and included a step-by-step guide. This issue should be marked as resolved.
[https://github.com/starxeras/yomitan-mecab-installer](https://github.com/starxeras/yomitan-mecab-installer)

**Comment by djahandarie** [comment]
@starxeras Thank you, could you also open a PR to link to this new repo from the README?

**Comment by starxeras** [comment]
> @starxeras Thank you, could you also open a PR to link to this new repo from the README?

Sure. Do you also want me to link it in the settings page where yomichan-mecab-installer is mentioned?

**Comment by djahandarie** [comment]
Fixed by #326
