### ISSUE TITLE
JapanesePod101 is the only working audio source

### ISSUE THREAD

**Issue by uhp00** [themoeway/yomitan#321]
**Description**
Upon browser start-up, JapanesePod101 is the only working audio source when trying to play audio on any word. All other sources, whether they're custom URLs or even other integrated ones like JapanesePod101 (Alternate) or Jisho.org will simply load indefinitely and  never play anything.
Going to the browser's extension settings page, switching the "Allow access to file URLs" option back and forth fixes the issue temporarily (it doesn't seem to matter whether it's enabled or disabled, touching that option will fix it regardless). However it will start not working again after some time, or after browser restart.

I saw that a similar issue was posted some time ago, but it seemed to be a Firefox bug that has been fixed since then and that had to do with the allowed origins in Yomitan's permissions, but those are already properly set up on my end.
This was tested on the 3 current latest versions, with the same result on each (I had never encountered this issue on Yomichan).

**Browser version**
Brave 1.60.114

**Yomitan version**
Tested on 23.10.25.0, 23.11.10.0 and 23.11.12.0

**Comment by jbukl** [comment]
https://github.com/brave/brave-browser/issues/30854
seems like it's due to this active issue for brave - thread has a fair amount of activity 😅

**Comment by uhp00** [comment]
> [brave/brave-browser#30854](https://github.com/brave/brave-browser/issues/30854) seems like it's due to this active issue for brave - thread has a fair amount of activity 😅
> 
> maybe making a static set of rules for removing cookies for all requests would work? don't know if that's possible (especially as the origin header is set dynamically atm) or if that would fix anything - didn't investigate any further once I found this thread.

I see, that would also explain why I never had this issue on Yomichan since it never made the switch to manifest v3 as far as I can tell. I'll close the issue since it looks like it's more so up to Brave to fix it and not Yomitan, but thanks for helping!
