### ISSUE TITLE
As of 23.11.12.0, certain custom CSS doesn't function properly anymore.

### ISSUE THREAD

**Issue by Wyzmic** [themoeway/yomitan#323]
The font size for the tag label contents does not go below 1em (default font size). It does function when increasing the value but not when decreasing it.

```
.tag-label-content {
   font-size: 0.5em;
}
```

**Browser version**
Microsoft Edge 119.0.2151.58

**Yomitan version**
23.11.12.0

**Comment by jbukl** [comment]
can't replicate on my end - could you drop some settings/screenshots of the css?

Browser version
Microsoft Edge 119.0.2151.58

Yomitan version
23.11.12.0

**Comment by jbukl** [comment]
> I see, yeah sure. I've tried different fonts too and it's not that. I didn't change anything in particular either so I have no idea. ![image](https://user-images.githubusercontent.com/72083780/283164539-7eaf8c1e-4bf0-4394-96aa-f573ac05a308.png) ![image](https://user-images.githubusercontent.com/72083780/283164597-5bb5ad90-1709-4586-9772-53440c4e1a04.png) ![image](https://user-images.githubusercontent.com/72083780/283164715-1ec070a5-3a8a-4146-b5a6-c26d05690193.png) [yomitan-settings-2023-11-15-15-31-33.json](https://github.com/themoeway/yomitan/files/13366502/yomitan-settings-2023-11-15-15-31-33.json)

settings worked for me too - seems bizarre, as if a minimum value is being applied.
have a few possible tests in mind:

1. 
![image](https://github.com/themoeway/yomitan/assets/148171160/e7713e23-a690-4f80-b215-603467a28859)
does changing the setting on this page do anything?

2. what does the dev tools show for `.tag-label-content` styles? is the custom css showing up?

![image](https://github.com/themoeway/yomitan/assets/148171160/aa508065-1552-4fda-8b04-77be8e682645)

3. does disabling all of your dictionaries except for one change anything?

4. any errors in dev tools console?

**Comment by Wyzmic** [comment]
The problem was the minimum font size, it's definitely a new setting. But now when I zoom in a page more than around 150%, even with the zoom level setting checked, the yomitan popup does scale with the browser zoom I'm using. Before when using em values for the font sizes, they stayed the same no matter what, now it's changed apparently. Maybe it's the newer browser code? Appreciate the help Jake!
