### ISSUE TITLE
Permissions toggle still too easy to miss

### ISSUE THREAD

**Issue by djahandarie** [themoeway/yomitan#330]
On Firefox, `Recommended Permissions (Important)` on the welcome page is required to check for Yomitan to work.
<img width="709" alt="Screenshot 2023-11-26 at 11 19 17 AM" src="https://github.com/themoeway/yomitan/assets/21412/c88c6af2-986c-4edb-8a01-3e1492ab9ef4">

I was doing some user testing with a friend who installed the extension, and they missed the toggle and thought the extension was broken as a result.

I think we need to move the toggle to be above-the-fold (probably the first thing on the page), and also put something like "required" or similar, and use more noticeable colors like red. Also we may want it to be on the settings page as well (in a noticeable spot) because people would not think to go to the welcome page if they already missed it there once.

We could likely also hide the UI element once it is turned on, so more like a set-it-and-forget-it sort of UI. That would allow us to make it stick out more when it is actually needed.

**Comment by Kuuuube** [comment]
Would it be possible to make these settings opt-out instead of opt-in? or at least try to prompt the user for them right away when the welcome screen pops up instead of forcing them to hit a toggle?

If possible I think that may be an even better solution than putting it at the top of the page in big red text.

**Comment by djahandarie** [comment]
IIRC in Firefox it must be opt-in after the extension is installed, which is why the current UI exists. But I don't have a source for that off-hand.

**Comment by Scrub1492** [comment]
Also include it in the README FAQ?

**Comment by Kuuuube** [comment]
Closing as this has been made much better by #884 and #942
