### ISSUE TITLE
Add Frequency Dictionaries to README

### ISSUE THREAD

**Issue by MarvNC** [themoeway/yomitan#334]
As mentioned in #305 , there are various frequency dictionaries built on open data such as [BCCWJ](https://github.com/toasted-nutbread/yomichan-bccwj-frequency-dictionary/) and [CC100](https://paperswithcode.com/dataset/cc100). BCCWJ can be added by linking nutbread's repository, but with CC100 there is no official place to download the dictionary on the web unfortunately.

**Comment by jamesmaa** [comment]
Seems like we should add this to recommended dicts, which we have now
