### ISSUE TITLE
Adding {sentence} into Anki card results in words previous of the sentence.

### ISSUE THREAD

**Issue by Pale-Gray** [themoeway/yomitan#340]
**Description**
When I hover over 彼女 in the red title on [this website](https://kakuyomu.jp/works/16817330652852151031) and add the word to Anki, it grabs the dashbar and text before 彼女. I expect it to output {sentence} as 「彼女は何より腹立たしくて、誰よりも愛おしい」, but I get 「>マイページ小説を探す公式連載書籍化作品初めての方へログイン新規登録（無料）ゆえに、僕は神を愛そう海鳴ねこ1話目から読む★304応援コメント42小説のフォロワー概要彼女は何より腹立たしくて、誰よりも愛おしいたった一人の王が君臨する。」.

I think it could be a formatting issue with the webpage, but I can't seem how to fix this problem.

**Browser version**
Chrome Version 119.0.6045.161 (Official Build) (64-bit)

**Yomitan version**
23.11.23.0

**Comment by Mansive** [comment]
Turning on "Layout-aware scanning" can alleviate the issue but not completely solve it. For example, it outputs {sentence} as 「概要彼女は何より腹立たしくて、誰よりも愛おしい」 instead of 「彼女は何より腹立たしくて、誰よりも愛おしい」.
