### ISSUE TITLE
Mass anki editing

### ISSUE THREAD

**Issue by KiRa937** [themoeway/yomitan#347]
There are a few requests for the ability to edit old Anki cards made in yomitan/baba/chan like replacing old glossaries. I want to add a suggestion for mass editing of old Anki cards.

There should be a tool for mass editing of old Anki cards. The tool should present an option of which fields to update. In terms of scale the tool shoud offer these options:

- to edit all present Anki cards
- to edit Anki cards that have tags [A, B, C...]
- to edit all present Anki cards except ones that have tags [A, B, C...]

By default Anki cards should have only one entry in the user's dictionary to grab info from. But in case there are conflicts with multiple entries user should be presented with options:

- use first available entry in each conflict
- save a list of conflicts in txt/html format for manual editing

**Comment by jamesmaa** [comment]
This seems covered by #895. Please reopen or file a new issue if there's something else you need

**Comment by KiRa937** [comment]
Technically it is covered, but still needs lots of work on the side: manually export deck as txt, import it as txt (for example in Google Sheets), filter it, insert the expression column into the Generator and export as txt (Send to Anki doesn't rewrite the notes), convert the result to csv and only then import into Anki. 
Conversion to csv is needed to choose which fields to rewrite and which to keep during import. So maybe the ability to export as csv and not txt would ease that part a bit.

**Comment by Kuuuube** [comment]
Anki's "txt" deck format is actually just a csv with `.txt` extension. The only difference is the first few lines contain metadata.

The way yomitan exports it contains full deck and template information but if you strip off the metadata at the top, Anki wont know what to do with the data youre giving it and it will let you overwrite it like youre asking. Just make sure to set the import options correctly when importing the "txt". Most importantly you need to set it to update existing cards instead of add new cards.

**Comment by jamesmaa** [comment]
Would this issue solve your problem? #1363

**Comment by KiRa937** [comment]
> Would this issue solve your problem? #1363

Probably. Is it related to export of Note Generator?

**Comment by Kuuuube** [comment]
Adding csv export to the anki note generator would be quite easy. It's literally the same thing as the current txt export minus a few lines of metadata at the top and an extension change.

All the real data is exactly identical, including the formatting of that data.

**Comment by KiRa937** [comment]
> Anki's "txt" deck format is actually just a csv with `.txt` extension. The only difference is the first few lines contain metadata.
> 
> The way yomitan exports it contains full deck and template information but if you strip off the metadata at the top, Anki wont know what to do with the data youre giving it and it will let you overwrite it like youre asking. Just make sure to set the import options correctly when importing the "txt". Most importantly you need to set it to update existing cards instead of add new cards.

Just checked it. Yeah, this works too. But still this is another step - "remove metadata from resulting txt".
