### ISSUE TITLE
Archaic words dictionary

### ISSUE THREAD

**Issue by Tosh0kan** [themoeway/yomitan#367]
I have been studying classic Japanese literature, and I have found that Yomitan's dictionaries do not contain enough (if at all) archai words. Currently, I have  `Jitendex [2023-12-10] rev.3.0`, ` KireiCake rev.rikai2 `, ` JMnedict rev.JMnedict.2023-12-11 `, and `KANJIDIC rev.kanjidic2 `. Some of the words that it couldn't parse are, for example, 思ふ, 得め, etc

Would it be possible to add a more archaic-focused dictionary?

**Comment by MarvNC** [comment]
Get some monolingual dictionaries, particularly weblio古語辞典. 思ふ is parsed by various monolingual dictionaries in addition to that one. Dictionaries are community supported though, you could make one yourself if you find a good data source. Related: https://github.com/FooSoft/yomichan/issues/2285

I'd also say to remove Kireicake (#195) and get more monolingual dictionaries if you're reading classical literature.

**Comment by Tosh0kan** [comment]
So I'd have to find someone that has made a dictionary from that source, right?

**Comment by MarvNC** [comment]
https://github.com/MarvNC/yomichan-dictionaries
https://learnjapanese.moe/resources/#dictionaries

**Comment by Tosh0kan** [comment]
Oh, wow. Didn't know either of those sites. Thank you!

**Comment by NinjaZMY** [comment]
@Tosh0kan have you found any custom monolingual dictionaries that could read archaic jp
I tried >実用日本語表現辞典 ; 旺文社国語辞典 第十一版 ; Pixiv  but they didn't include archaic readings 
only the archaic dictionary of weblio古語辞典 fixed it for me

I was wondering if there existed another dictionary in the resources that could read archaic jp
