### ISSUE TITLE
Sort dictionary display order in popup page

### ISSUE THREAD

**Issue by Casheeew** [themoeway/yomitan#368]
At present, there is no way to change the display order of installed dictionaries other than the imported order. 
When you have a large list of dictionaries, this might cause some inconvenience. Additionally, it might be nice to automatically assign the priorities based on some order. 
There are some workarounds such as https://github.com/MarvNC/yomichan-dictionaries/blob/master/sort-dictionaries.js but might be helpful to have an inbuilt option.

Some proposals: Lexicographical order sort, sort based on dictionary type (kanji / vocab /freq), sort based on priority, custom sort order

**Comment by MarvNC** [comment]
Yeah I'm hoping to work on this someday 🙏

With the way dictionaries are built there aren't really strict categories of an installed dictionary being a term/kanji/frequency dictionary, a zip file can contain all sorts of stuff. I think a drag to sort interface without the priority numbers would work best, along with an option to import an order from a txt.

**Comment by msikma** [comment]
On that note, it might be nice to have a built in default priority of sorts as well. Sorry if I'm hijacking this issue but it seems related. Just now Yomitan displayed 海保 as a surname first, before displaying it as noun, until I changed the dictionary priorities.

**Comment by Scrub1492** [comment]
Don't know if this is possible, because the dictionaries are not actually from Yomitan, so the extension wouldn't know about the dictionaries installed. Maybe it is possible with a hardcoded list of common dictionaries, but thatd mean someone has to remember to go and update it once in a while.

**Comment by jamesmaa** [comment]
This seems fixed in #981
