### ISSUE TITLE
Make `api.js` more typesafe

### ISSUE THREAD

**Issue by djahandarie** [themoeway/yomitan#391]
Right now a couple parts of the API are stringly-typed (the action parameter to `_invoke` etc). To some degree it's hard to fully avoid because we are stuck with sendMessage, but at least we can try to use enums that force the frontends and backends to at least sort of be talking the same language.

I'm not sure how easy it is to use typescript enums (or other option if there is something better) with our JSDoc / native JS (no compilation step) setup, but it's probably worth trying as I feel there is a lot of room for error here.

Also, I was considering if there is some way to just eliminate all the api boilerplate and auto-generate it, but I'm not sure if it is worth it. Maybe it would be worth it if there is an existing, standardized solution for this out there.

**Comment by toasted-nutbread** [comment]
Later on in the JSDoc annotation process, I got to the offscreen classes and I was able to do something similar to what I did in API, but a bit more type safe. Could probably refactor the API classes to be more similar to this.

The real killer here is the stuff in the cross-frame-api files. Those have little if any type validation, and it makes a lot of assumptions that proper usage is happening.
