### ISSUE TITLE
Unknown error when disk is too full

### ISSUE THREAD

**Issue by cashewnuttynuts** [themoeway/yomitan#395]
**Description**
I did a fresh install and installed dictionaries in https://drive.google.com/drive/folders/1-WReUZvneHEkvnjeqJA4oT08od7eK-sq with around 2GB left in my hard drive. 
However, the import fails with unknown error:
![image](https://github.com/themoeway/yomitan/assets/52880648/0233c576-1578-443c-80cf-4c32997add55)
The issue resolves when I clean up my hard drive. Other users have also experienced unhelpful error messages when importing such as in #357 . 
In my instance, the error originated from an unknown error in the z-worker library. 
It might be difficult or not possible to change the error message, but the extension can generate warnings if it detects that there is not enough space left.

**Browser version**
Version 120.0.6099.72 (Official Build) (64-bit)

**Yomitan version**
Yomitan 23.11.23.0

**Exported settings file**

**Comment by Scrub1492** [comment]
Also #356

**Comment by Kuuuube** [comment]
Fixed in #548, there is now a warning.
