### ISSUE TITLE
Improve profile switches

### ISSUE THREAD

**Issue by Casheeew** [themoeway/yomitan#408]
The profile switching key combinations currently only accept Ctrl, Shift, Alt. In my experience Alt doesnt even work as expected (does nothing) in those key combinations (Chrome). 
I used up all of my possible key combinations for different purposes (and don't want to switch too often between browser profiles).
We can add support for more key combinations to have more control over profiles, or have a keyword to change the browser profile without using different combinations (like Alt + Shift in Windows changes IME) so that one same key comb (e.g Shift) can be used for 2 browser profiles.

**Comment by jamesmaa** [comment]
Fixed in #832 right?
