### ISSUE TITLE
'View added note' can't open note editor window

### ISSUE THREAD

**Issue by krischimk** [themoeway/yomitan#417]
**Description**
When choosing the note viewer window to be displayed instead of the browser window when clicking the 'View added note' button, I get the error message: 

"An error occurred:
Anki error: 'Edit' object has no attribute 'finished'"

<img width="330" alt="image" src="https://github.com/themoeway/yomitan/assets/121830124/d552dd96-73a6-4657-930b-cf22b1b43e47">

In the Yomitan settings, it says:
"If an error occurs, Anki and/or AnkiConnect may need to be updated."

<img width="508" alt="image" src="https://github.com/themoeway/yomitan/assets/121830124/eb5e7f4c-5966-4eb4-8822-29c9ca24d929">
<br><br>These are however updated:<br><br>

**Anki version**
Version ⁨23.10.1 (fac9e0ee)⁩

**Anki connect version**
newest (from 2023.10.29)

**Yomitan version**
23.11.23.0

**Browser version**
MS Edge 120.0.2210.89 (Official build) (64-bit)

**Comment by toasted-nutbread** [comment]
FYI this is an issue in AnkiConnect, not this extension. Didn't look into it beyond noting that it's coming from Anki.

https://github.com/FooSoft/anki-connect/blob/1f7fc80b7e7f5ab904ba0e18fa657137d26936e8/plugin/__init__.py#L1665C1-L1665C1

**Comment by Xydez** [comment]
This issue is resolved as of 2024-01-02 by commit [2de0798](https://git.foosoft.net/alex/anki-connect/commit/2de0798fc1ee0eea992076aa47d3b0f453187282) in the anki-connect repository.
