### ISSUE TITLE
more flexible custom deinflect.json

### ISSUE THREAD

**Issue by Scrub1492** [themoeway/yomitan#421]
Create a section in settings page, where users can input a JSON string in. It can look like the custom CSS field:
![image](https://github.com/themoeway/yomitan/assets/52880648/80aab948-3f30-444a-8fc3-d6debc5753a6)

Use cases:
- Deinflect different dialects from the standard dialect:
e.g) 
つこうた -> 使った
つこた -> 使った
for some dialects;
- Get headwords for slang terms:
e.g) 
かっけぇ
かっっっこいい
- Get more dictionary coverage, but for cases that are not suitable to include in the default deinflect.json file:
e.g)
良さげ, 誇らしげ
良さ気, 誇らし気 
Reference: #73 
- More support for foreign languages, without including other language-dependent assets or code out-of-the-box. 
e.g) 
Korean language deinflection: https://github.com/Lyroxide/yomichan-korean/blob/master/ext/data/deinflect.json

This can count towards limited other languages support in yomitan; #410

**Comment by MarvNC** [comment]
As discussed in #yomitan-development, I feel like it'd be better to have alternative deinflect jsons supported officially and released with Yomitan. For the use cases you mentioned, I don't see much downside to including them here. For other languages it could lead to a bad user experience when people would have to manually find and paste in json data and don't get updates for improved deinflection rules, or are confused with multiple sources online with differing data.

**Comment by toasted-nutbread** [comment]
IMO it would probably be better if this is something that is imported and managed more like a dictionary. Probably better UX that way.
