### ISSUE TITLE
Audio is not populated in Anki note creation

### ISSUE THREAD

**Issue by zacharykeyes** [themoeway/yomitan#424]
**Description**
Audio is not imported into Anki notes when creating Anki notes. All other fields are properly populated. I don't see any errors popup or anything, it just fails silently

Digging into the firefox debugger a bit, it looks like the media fetch returns null? I haven't looked at this code before and have little experience in frontend, so I could be totally wrong.
![firefox_MtTPP42sDB](https://github.com/themoeway/yomitan/assets/14350340/f30f96a0-a410-49db-a8af-e33ca7b9bb83)

**Browser version**
Firefox 121.0

**Yomitan version**
23.11.23.0

**Exported settings file**
[yomitan-settings-2023-12-22-16-03-36.json](https://github.com/themoeway/yomitan/files/13754146/yomitan-settings-2023-12-22-16-03-36.json)

**Comment by zacharykeyes** [comment]
Closing as fixed. I just had to enable more permissions in the Firefox Add-ons Manager. Not sure exactly which permission it was, but it was one of:
*  Get data from the clipboard 
*  Exchange messages with programs other than Firefox 
*  Access your data for all websites

**Comment by felixwoolford** [comment]
For further precision: "Access your data for all websites" is the relevant permission.
