### ISSUE TITLE
Deinflection Json overhaul

### ISSUE THREAD

**Issue by Casheeew** [themoeway/yomitan#432]
### Improvements in deinflect.json
- slangs
- dialects
detailed cases can be found in #421 .
Origin: https://github.com/themoeway/yomitan/issues/421#issuecomment-1867230646

**Comment by Scrub1492** [comment]
https://github.com/FooSoft/yomichan/issues/2127

**Comment by Scrub1492** [comment]
https://github.com/FooSoft/yomichan/issues/2127

**Comment by Scrub1492** [comment]
-[] 古語 deinflection
  -[] [四段活用](https://ja.wiktionary.org/wiki/%E5%9B%9B%E6%AE%B5%E6%B4%BB%E7%94%A8)

**Comment by jamesmaa** [comment]
Seems done? This issue is too generic at this point to be useful
