### ISSUE TITLE
New Additions to index.json in Dictionaries

### ISSUE THREAD

**Issue by MarvNC** [themoeway/yomitan#445]
Some things I think could be added:
- CSS for the dictionary
- Lang code which could determine what language the entries are

**Comment by Scrub1492** [comment]
Is the CSS shipped with the dictionary?

**Comment by MarvNC** [comment]
Yeah, would be better imo than relying on getting the user to add the CSS manually which is messy.

**Comment by Scrub1492** [comment]
Will need it to work somehow with backwards compatibility. Not very familiar with the schemas myself.

**Comment by jamesmaa** [comment]
This is done
