### ISSUE TITLE
Consider reworking README file into multiple smaller files

### ISSUE THREAD

**Issue by toasted-nutbread** [themoeway/yomitan#469]
One of the problems that Yomichan historically had was that the readme was excessively large for a single file and really isn't good for finding information. And because of that Yomitan has inherited this issue. Something I have thought for a while is that the readme should be split into multiple markdown files, perhaps living in a "docs" folder or something, that contain smaller sections of info. For example, the description of the default Anki markers should be something separate, the FAQ should be separate, etc.

Some of the FAQ should also be checked to see if it still applies. If I recall, the section about Firefox import problems applied to a pretty old version of Firefox, so I'm not sure if it's still helpful.

**Comment by piercemorris** [comment]
Currently working on this, will post an update when it's complete - although it can be very subjective with the modifications

**Comment by piercemorris** [comment]
@toasted-nutbread since the majority of the README has been reworked, how much relevance does this issue still have? I the last port of call would be a revision of the FAQ but I'm not really familiar with Firefox and the issues surrounding it.

**Comment by toasted-nutbread** [comment]
IMO I'm fine with it as-is.
