### ISSUE TITLE
Welcome page rework

### ISSUE THREAD

**Issue by toasted-nutbread** [themoeway/yomitan#470]
Right now, I feel that the welcome page isn't great as an initial information page for a few reasons, and this is really me blaming myself since I set it up this way / never got around to updating it.

* The first thing you see is effectively a wall of text, which people are probably inclined to ignore.
* It's styled the same as the settings page, which is good for the settings, but perhaps not as good for an intro guide.
* It re-opens on every browser session, or at least it does when I'm testing and I reload the extension. I know there is some code to prevent this, but this could be improved.
* Related: #330

Overall, I just think the UX of this page could be much better. I do have some ideas I'd like to eventually test out here if I find the time, so I'll try to look into this sometime.

(again this is me creating issues to help track things that have been on my mind)

**Comment by Kuuuube** [comment]
Closing as this has been addressed in #884
