### ISSUE TITLE
deinflect.json tests

### ISSUE THREAD

**Issue by toasted-nutbread** [themoeway/yomitan#471]
deinflect.json has some potential dangers if it is not set up correctly, where I think it may be able to infinite loops. I originally expressed this concern here: https://github.com/FooSoft/yomichan/issues/1665#issuecomment-841849579.

Mainly posting this now because there seems to be interest in adding support for additional languages which will likely incur additional inflection rules and whatnot. So it would be good to actually be able to validate that all of the rules that exist don't cause any issues with other rules. This can probably be done by generating some sort of directed graph structure and searching for cycles, but I haven't really looked into this much.

**Comment by Scrub1492** [comment]
I'm looking into this.
Although, I'm a bit confused as to why 気難しい would deinflect into 気難しいい? am I missing something here?
I can understand if its something like かわい -> かわいい -> かわいいい.

**Comment by Scrub1492** [comment]
(By adding one rule 
```"-i": [
        {"kanaIn": "し", "kanaOut": "しい", "rulesIn": [], "rulesOut": ["adj-i"]}
    ]``` 
to deinflect.json the output is 
```[
  { term: '愛し', rules: 0, reasons: [] },
  { term: '愛す', rules: 2, reasons: [ 'masu stem' ] },
  { term: '愛しい', rules: 32, reasons: [ '-i' ] }
]``` with no infinite expansion

**Comment by toasted-nutbread** [comment]
I think the way I was originally thinking about this rule was "just add an い to the end and see if it's valid", so the rule would have been more similar to `kanaIn: "", kanaOut: "い"`, which would lead to infinite expansion. This is not to say this is the correct way to do this, but it's just demonstrating that some rules can break things and I don't think there's any checks in the definflector to prevent infinite expansion, as that would add overhead to a frequently used code path. So if it can be guaranteed via static analysis, that would probably be the better way.

**Comment by Scrub1492** [comment]
Not sure how to form a graph out of this because there is supposedly a variable amount of kanas before `kanaIn`, leaving this to the more talented peeps 😅

**Comment by toasted-nutbread** [comment]
Closing this now that we have a cycle test and a more clear way to approach deinflections in general based on the updated format of the file.
