### ISSUE TITLE
Issue with handlebars

### ISSUE THREAD

**Issue by Anpan2001** [themoeway/yomitan#478]
**Description**
When using [these handlebars](https://pastebin.com/raw/TeSJc6ij), the following error occurs:
![image](https://github.com/themoeway/yomitan/assets/105514779/45cc9426-3c8f-4b51-8d56-415a33c029a8)

Tester shows this:
![image](https://github.com/themoeway/yomitan/assets/105514779/4dc40372-1465-45d7-9a73-6b1618a76e50)

**Yomitan version**
Latest

**Comment by Kuuuube** [comment]
This appears to be fixed in the latest version ([24.4.7.0](https://github.com/themoeway/yomitan/releases/tag/24.4.7.0)). Reopen if you can still replicate it there.
