### ISSUE TITLE
Capture some implicit patterns in custom eslint lints

### ISSUE THREAD

**Issue by djahandarie** [themoeway/yomitan#483]
There's some stuff in the code, for example using our custom `parseJson` function instead of `JSON.parse` that we should probably formalize as lints, as most new contributors would not be aware of them, which could result in avoidable delays during peer review.

Forbidding certain functions shouldn't too hard to do using eslint's selector functionality: https://stackoverflow.com/questions/40977713/how-to-forbid-a-specific-named-function-with-eslint https://eslint.org/docs/latest/extend/selectors
-- but I'm not sure about other patterns we have and which ones would be formalizable.

cc @toasted-nutbread

**Comment by toasted-nutbread** [comment]
It's mainly any function that returns `any`, which the JSON conversion functions do. So right now, it's just the two functions in [json.js](https://github.com/themoeway/yomitan/blob/master/ext/js/core/json.js).
