### ISSUE TITLE
Template render error for {jpmn-primary-definition}

### ISSUE THREAD

**Issue by hiddenlucas** [themoeway/yomitan#487]
Hi there,

I get error when I'm using https://aquafina-water-bottle.github.io/jp-mining-note-prerelease/setupyomichan/ templates
Template render error for {jpmn-primary-definition}
Template render error for {jpmn-extra-definitions}

and log

'Error: Template render error for {jpmn-primary-definition}\n    at chrome-extension://bnfakblgbdahlhpdmpcigbppmnbdblac/js/data/anki-note-builder.js:174:31\n    at async Promise.all (index 1)\n    at async AnkiNoteBuilder._stringReplaceAsync (chrome-extension://bnfakblgbdahlhpdmpcigbppmnbdblac/js/data/anki-note-builder.js:195:17)\n    at async AnkiNoteBuilder._formatField (chrome-extension://bnfakblgbdahlhpdmpcigbppmnbdblac/js/data/anki-note-builder.js:168:23)\n    at async Promise.all (index 6)\n    at async AnkiNoteBuilder.createNote (chrome-extension://bnfakblgbdahlhpdmpcigbppmnbdblac/js/data/anki-note-builder.js:78:38)\n    at async DisplayAnki._createNote (chrome-extension://bnfakblgbdahlhpdmpcigbppmnbdblac/js/display/display-anki.js:557:66)\n    at async DisplayAnki._addAnkiNote (chrome-extension://bnfakblgbdahlhpdmpcigbppmnbdblac/js/display/display-anki.js:371:70)'

'Error: Template render error for {jpmn-extra-definitions}\n    at chrome-extension://bnfakblgbdahlhpdmpcigbppmnbdblac/js/data/anki-note-builder.js:174:31\n    at async Promise.all (index 1)\n    at async AnkiNoteBuilder._stringReplaceAsync (chrome-extension://bnfakblgbdahlhpdmpcigbppmnbdblac/js/data/anki-note-builder.js:195:17)\n    at async AnkiNoteBuilder._formatField (chrome-extension://bnfakblgbdahlhpdmpcigbppmnbdblac/js/data/anki-note-builder.js:168:23)\n    at async Promise.all (index 35)\n    at async AnkiNoteBuilder.createNote (chrome-extension://bnfakblgbdahlhpdmpcigbppmnbdblac/js/data/anki-note-builder.js:78:38)\n    at async DisplayAnki._createNote (chrome-extension://bnfakblgbdahlhpdmpcigbppmnbdblac/js/display/display-anki.js:557:66)\n    at async DisplayAnki._addAnkiNote (chrome-extension://bnfakblgbdahlhpdmpcigbppmnbdblac/js/display/display-anki.js:371:70)'

**Comment by toasted-nutbread** [comment]
Same issue as #437?

**Comment by Kuuuube** [comment]
Aquafina's JPMN has not been updated and will not work with yomitan. Try using https://github.com/arbyste/jp-mining-note instead.
