### ISSUE TITLE
Scanning doesn't work after browser restart

### ISSUE THREAD

**Issue by YizhePKU** [themoeway/yomitan#502]
**Description**
After browser restart, holding shift to scan doesn't work until I click on the extension icon once.

**Browser version**
I can replicate on Firefox 121.0 and a fresh-installed Firefox 122.0b4. Cannot replicate on Chrome.

**Yomitan version**
Yomitan 23.11.23.0

**Comment by kon-sv** [comment]
Check the permissions on the extension. If you right click on the extension it will most likely have
`Extension can read and change data: Only when clicked`

It is possible to change this on the Permissions tab for the extension by checking `Access your data for all websites` to always enable scanning without clicking

**Comment by abaga129** [comment]
I was having basically the same issue that I always had to click the extension when I opened a site before it would start scanning.  @kon-sv 's suggestion fixed it for me.

**Comment by YizhePKU** [comment]
@kon-sv 's suggestion fixed it for me too.
