### ISSUE TITLE
shift+search button no longer opens search pop-up

### ISSUE THREAD

**Issue by uhp00** [themoeway/yomitan#515]
**Description**
Holding shift and clicking the search button no longer opens a search pop-up and instead behaves the same way a regular click does, opening a new search tab.
Update: I have noticed the pop-up does show when doing it in an incognito window for some reason, although it also opens a regular search tab at the same time so it's not really a good workaround.

**Browser version**
Tested on Brave 1.61.114 and Chrome 120.0.6099.217

**Yomitan version**
23.12.29.0, still broken on 24.5.5.0

**Comment by Skretkowicz** [comment]
I am encountering the same issue on my Mac, I had a setup on previous computer, everything is working, but on the new setup no matter what I do I do not see the popup. In settings, I see the dictionaries installed on the test word 読め, but no matter what I do in the normal browser and what settings I tried, it does not popup on Firefox
