### ISSUE TITLE
Clarify Stance on Other Languages

### ISSUE THREAD

**Issue by MarvNC** [themoeway/yomitan#516]
With Yezichak being merged in, there would need to be some changes made to the readme (after #512) to indicate that other languages are officially supported. Also, in the meantime it might be possible to link free dictionaries for any other languages that are currently already supported such as Mandarin/Cantonese.

**Comment by brishtibheja** [comment]
Yezichak will probably close the discord server as he said. will the converted dictionaries be uploaded somewhere for use with yomitan?

**Comment by StefanVukovic99** [comment]
> Yezichak will probably close the discord server as he said. will the converted dictionaries be uploaded somewhere for use with yomitan?

I'll probably put the converted dictionaries up in releases when I set up a separate repo for the converter(s). I guess the discord will remain tied to that project, instead of the extension.

**Comment by jamesmaa** [comment]
Done
