### ISSUE TITLE
Updating the Yomichan migration docs to reflect the changes to regexMatch handlebars

### ISSUE THREAD

**Issue by arbyste** [themoeway/yomitan#531]
**Description**
It looks like the upgrade to Version 23.12.29.0 changed the way that the handlebars uses regexMatch. The following quote is from this pull request for JPMN: https://github.com/arbyste/jp-mining-note/pull/4

>The problem is that `regexMatch` no longer works in the form `{{regexMatch regex [flags] [text-to-modify]...}}`. 
Instead, it only works in the form `{{#regexMatch regex [flags]}}text-to-modify{{/regexMatch}}`. Maybe an issue should be raised in Yomitan?

Was this change intentional? I couldn't see anything about it in the release notes for 23.12.29.0. If this behavior is expected, then perhaps it would be a good idea to add it to the Yomichan migration docs? (https://github.com/themoeway/yomitan/blob/master/docs/yomichan-migration.md)

**Yomitan version**
23.12.29.0

**Comment by Scrub1492** [comment]
Seems like it should be handled by this pr #439 . @toasted-nutbread thoughts?
