### ISSUE TITLE
(Firefox) Yomitan doesn't import audio into card

### ISSUE THREAD

**Issue by DankChoir** [themoeway/yomitan#538]
**Description**
Audio in Yomitan hover still works perfectly, though when importing card, the WordAudio fields is empty.
![image](https://github.com/themoeway/yomitan/assets/79992320/2b221dba-8593-4d5e-9cbb-aea5c26d2879)

This only occurs on Firefox, I tried with Chrome and it was able to import audio (same config)

![image](https://github.com/themoeway/yomitan/assets/79992320/0dba6544-51bf-4d54-8f27-a101239bbc39)

**Browser version**
Firefox 121.0.1

**Yomitan version**
Yomitan 23.12.29.0

**Comment by arbyste** [comment]
I can confirm that I see the same behavior on Firefox 121.0.1, but not on Brave 1.61 (although with Brave I still need to restart Yomitan every time I reboot due to [335](https://github.com/themoeway/yomitan/issues/335) )

**Comment by DankChoir** [comment]
![image](https://github.com/themoeway/yomitan/assets/79992320/b6ce99c4-3052-4e36-b53b-a0ba22cef3e7)
I have found the issue. On Firefox you must enable these settings in the extension setting for Yomitan to be able to import audio 
[Source](https://xelieu.github.io/jp-lazy-guide/setupYomitanOnPC/#__tabbed_1_2)
