### ISSUE TITLE
License Clarification

### ISSUE THREAD

**Issue by MarvNC** [themoeway/yomitan#540]
> Required licensing notices for this project follow below:
>
> EDRDG License
> This package uses the EDICT and KANJIDIC dictionary files. These files are the property of the Electronic Dictionary Research and Development Group, and are used in conformance with the Group's license.
>
> Kanjium License
> The pitch accent notation, verb particle data, phonetics, homonyms and other additions or modifications to EDICT, KANJIDIC or KRADFILE were provided by Uros Ozvatic through his free database.

Are these still part of Yomitan itself or are they just in dictionaries for it? Other than the [dictionaries](https://github.com/themoeway/yomitan/tree/dictionaries) branch. Also, maybe KanjiVG should be mentioned as it's used for the kanji stroke orders.

**Comment by NinjaZMY** [comment]
Normally they aren't part of yomichan / yomitan 
Those dictionaries have their own separated licences  

The Real question would be if an extra Licence is needed in order for yomitan to automatically use these dictionnaires 
( without the need for the user to manually download / install each dictionary ) as mentioned in #660 

- [ ] #660 
> [!IMPORTANT]
> the #660 issue and this issue are strongly connected -  there is a sort of codependence, in order to achieve #660 
> it is required to solve this issue: 
>- [ ] #540

**Comment by Kuuuube** [comment]
These licenses are no longer included in yomitan.
