### ISSUE TITLE
The clipboard-image tag in Anki integration doesn't work

### ISSUE THREAD

**Issue by TheCheddarCheese** [themoeway/yomitan#546]
**Description**
I set up the Anki integration as described in the guide, and everything works properly, except for the field with the {clipboard-image} tag which is always empty even when I have an image copied. The extension has all the optional permissions enabled.

![image](https://github.com/themoeway/yomitan/assets/124603704/c356c72a-f342-4ea0-b161-e62a677f1e85)

**Browser version**
Firefox 121.0.1

**Yomitan version**
23.12.29.0

**Anki version**
23.12.1

**Exported settings file**
[yomitan-settings-2024-01-20-14-36-17.txt](https://github.com/themoeway/yomitan/files/13998250/yomitan-settings-2024-01-20-14-36-17.txt)

**Comment by masiv1001** [comment]
I'm too having that exact problem with
**Browser:** Firefox 123.0 (flatpak)
**Yomitan:** same
⁨**Anki:** same
Strangely, clipboard content can be read when utilizing {clipboard-text}

**Comment by peldas** [comment]
I'm having the same problem with
**Browser:** Firefox 125.0b8 (64 ビット)
**Yomitan:** same
**Anki:** same

**Comment by peldas** [comment]
Update: I've fixed the issue thanks to [this message](https://discord.com/channels/617136488840429598/778430038159655012/1087077237561508000) on the TMW server:
> I looked at the Yomichan source code and found that the handlebars `{clipboard-text}` and `{clipboard-image}` requires the following permissions to be set to `true` in `about:config` for it to work
> 1. `dom.events.asyncClipboard.clipboardItem`
> 2. `dom.events.asyncClipboard.readText`
> 
> After setting these permissions to `true`, restart your browser and it should work now.

**Comment by Hikari2w2** [comment]
same issue with brave :(
