### ISSUE TITLE
Is there any way to access chrome-extension:// from yomitan?

### ISSUE THREAD

**Issue by RyanOrigens** [themoeway/yomitan#559]
The problem I have encountered is that I'm unable to access my other Yomichan-Korean instance with this Yomitan. The thing is, it utilizes 'chrome-extension://' and, as far as I'm aware, it isn't possible on Chromium...

**Comment by toasted-nutbread** [comment]
There is unfortunately no way to do this, at least last time I checked into a related issue about accessing chrome-extension URLs.
