### ISSUE TITLE
Sentence Field on Anki messing up while having furigana on top of a sentence.

### ISSUE THREAD

**Issue by RyanOrigens** [themoeway/yomitan#560]
When there is furigana on top of a sentence, it attempts to add the furigana to the sentence field, resulting in a disruption of the entire sentence.

This specific problem occurs exclusively with Language Reactor. It seems that Language Reactor may not be utilizing Ruby for the furigana text.

Given that Language Reactor is a widely used extension and the only one supporting furigana on Netflix, I believe it would be worthwhile to attempt to provide support for it.

**Comment by mcsantiago** [comment]
What version are you seeing this in? Can you provide a screenshot of the Yomitan card format and the effect you're seeing on Anki?

**Comment by RyanOrigens** [comment]
Sentenced Mined:

![image](https://github.com/themoeway/yomitan/assets/103891807/13744248-3825-4bde-b32f-c7ff3773b4c5)

Anki Card Format:
![image](https://github.com/themoeway/yomitan/assets/103891807/37678450-a25e-4cf3-a3b4-2fa1d5d5ef06)

Yomitan Settings for Anki
![image](https://github.com/themoeway/yomitan/assets/103891807/04f7911c-51e1-4a5a-88a9-0bc2f20fff37)

Version:
Latest Stable Release (Google Extension Store)

**Comment by JSchoreels** [comment]
Same issue here ! Maybe we could disable the furigana in Language Reactor for a workaround, but it's a bit unfortunate

**Comment by RyanOrigens** [comment]
Disable furigana is the same than disabling the subtitles for me...

**Comment by emanuelps2708** [comment]
Well this is not a solution for yomitan but you can use the AJT Japanese Anki Add-on if you want furigana in your Anki cards, the link is https://ankiweb.net/shared/info/1344485230 and here's a link to set it up to your needs, I hope this helps a little bit ;)

**Comment by RyanOrigens** [comment]
@emanuelps2708 Furigana works fine on Yomitan as long as the Furigana option on Language Reactor isn't active. Therefore, the only solution is disabling Furigana, which is something I'm willing to do, at least not at the moment.

The field will already be messed up if I choose the option to include Furigana or not in the Yomitan sentence, since the text on Language Reactor isn't actually Ruby; it's just plain text that also gets scanned and wrongly added. The only solution is manual support by Yomitan developers, and I think since everybody is utilizing it, it would be a great thing.

**Comment by Kuuuube** [comment]
This issue should be reported to language reactor. The correct fix for this is for them to support furigana using ruby text.
