### ISSUE TITLE
Renaming of the dictionaries

### ISSUE THREAD

**Issue by ganqqwerty** [themoeway/yomitan#569]
A user should be able to rename the dictionary in the dictionary list. This is especially useful for the frequency dictionaries where longer names cause too much space to be used.

**Comment by toasted-nutbread** [comment]
This was something I thought about back in the Yomichan days as well, basically allowing user aliasing. (Internally, the dictionary name has to stay the same due to how the database works.)

**Comment by jamesmaa** [comment]
#1270
