### ISSUE TITLE
Anki backlinks in popup

### ISSUE THREAD

**Issue by ganqqwerty** [themoeway/yomitan#571]
### Scenario description
 
* a user calls the popup on the word 読む
* this word already exists in the users' anki deck: the is a card with text 読む in the `Target word` field
* Yomitan performs a call to anki database and displays the list of the cards with 読み as a target word. 
* Yomitan allows the user to open the card in the cards browser in anki

### Why is it useful?
* a word that was previously added to anki is a word that the user forgot. Reminding of this word in a familiar context should strengthen the recall in the future
* some users prefer not to add multiple cards for the same word.

**Comment by ganqqwerty** [comment]
This is more of an idea than a feature description. It requires discussion and design.

**Comment by StefanVukovic99** [comment]
Doesn't this already work? There is the `Check for card duplicates` setting, and a button to view the already added note. 
![image](https://github.com/themoeway/yomitan/assets/24891609/3a802cf5-0302-43c1-9ae5-cb94e913bf27)

**Comment by ganqqwerty** [comment]
This one is very rudimentary version of what I mean. It allows the user to view the added note immediately after the user added a word to anki. If the user views the same word once again, this button is not shown. Not sure if it's expected to work this way, but even if it were shown, it's not exactly the feature I mean. 

What I mean is displaying a fully-fledged dictionary entry with the information taken from the users' anki card. Such dictionary entries can be grouped in a separate tab if we support tabs one day: #568

**Comment by toasted-nutbread** [comment]
> It allows the user to view the added note immediately after the user added a word to anki. If the user calls yomitan popup on the same word once again, this button is not shown. 

It should be shown if the note is already added.

As for the idea of showing the full Anki card data in the Yomitan popup, this feels like a scope creep and not a good separation of duties of the two applications. This may not be as simple of a feature as it may seem, such as cards containing custom styling and embedded HTML (potentially dangerous or simply not easily compatible). I would strongly recommend considering whether duplicating Anki functionality in Yomitan is useful and worth the long term support.

**Comment by ganqqwerty** [comment]
Fairly speaking, it does sound like an example of an optional feature, that should not be included in the core, but be a plugin of sorts.

**Comment by Kuuuube** [comment]
Closing this as it seems too far out of scope.
