### ISSUE TITLE
Descriptions of the word forms

### ISSUE THREAD

**Issue by ganqqwerty** [themoeway/yomitan#572]
When the word is not in its dictionary form, yomitan shows a form indicator (for example `-tai` for 食べたい). These form indicators can be made more comprehensible. One way to do it is to have a short description of each word form and show this description on hover. 

For 食べたい example: 
* the user hovers on the `-tai` indicator
* yomitan shows a tooltip "`wants to do` form of the verb"
![CleanShot 2024-01-24 at 14 53 21@2x](https://github.com/themoeway/yomitan/assets/697308/9134185e-84c5-43b1-aa99-10e2ea46fcb9)

**Comment by ganqqwerty** [comment]
Related issue: #564

**Comment by toasted-nutbread** [comment]
I completely agree with this. This ties back into the comment I've made a few times about "this format needs to be made more generalized." Additionally, dictionaries should support providing custom inflection maps, which has its own associated set of challenges, and the internal inflection map should support being disabled.

**Comment by ganqqwerty** [comment]
thanks a lot!
