### ISSUE TITLE
The auido is not played automatically for the very first lookup

### ISSUE THREAD

**Issue by ganqqwerty** [themoeway/yomitan#585]
**Description**
Auto-play audio is turned on. 
![CleanShot 2024-01-28 at 18 14 41@2x](https://github.com/themoeway/yomitan/assets/697308/3d70ae15-b2b2-4806-a4d5-6bddb945ae90)
Audio playback sources are set up like that: 
![CleanShot 2024-01-28 at 18 14 41@2x](https://github.com/themoeway/yomitan/assets/697308/6aae8f1b-560e-47c1-9fc4-f4c54fcee989)

I load a new tab and go to the content. 
I scan the word, for example 正月 on this page
I expect that the audio will be played when Yomitan's popup is displayed.
Instead of that, the audio is not played automatically. I am trying to do more lookups and audio is not played automatically. 
Woraround: 
* To resolve the problem, I manually click on the `Play audio` button: 
![CleanShot 2024-01-28 at 18 17 42@2x](https://github.com/themoeway/yomitan/assets/697308/a24fbcf1-3b6a-4eca-9ca7-81b117771d8f)
* The audio is played normally. The audio is played automatically for all consecutive lookups. 
* If I reload the page, again, the audio will not be played automatically for lookups until I click the `Play audio` button again. . 
* Also, if I follow a hyperlink and change the page, the audio will not be played automatically for the lookups until manual click on `Play audio`. 

**Browser version**
Version 121.0.6167.85 (Official Build) (arm64), MacOS 14.1.2 (23B92), Apple M1 Max

**Yomitan version**
Yomitan 24.01.14.0

**Comment by mcsantiago** [comment]
I'm unable to replicate this with MacOS Firefox Yomitan 24.01.14.0

**Comment by Kuuuube** [comment]
Interaction is required to autoplay audio. See https://developer.chrome.com/blog/autoplay and https://developer.mozilla.org/en-US/docs/Web/Media/Autoplay_guide
