### ISSUE TITLE
offscreen.js purpose and functionality?

### ISSUE THREAD

**Issue by toasted-nutbread** [themoeway/yomitan#586]
I've done a little bit of looking into this, but I don't fully understand why some components are in offscreen.js, specifically the `Translator` and `DictionaryDatabase`. As far as I can tell, this is supposed to address some sort of startup lag that would occur after the extension idles for a while and the service worker has to restart, but does anyone know how having these components in an offscreen document fix the issue? It seems like the additional indirection would make it slower in general.

Related:
* #316
* #319
* #325
* https://github.com/themoeway/yomitan/pull/584#issue-2104241060
* https://github.com/themoeway/yomitan/commits/master/ext/js/background/offscreen.js

**Comment by djahandarie** [comment]
Maybe @praschke might have some insight on this one

**Comment by praschke** [comment]
an indirection is always slower in absolute terms but that doesn't mean it's perceptible.

even if it is perceptible, the capabilities of the service worker and the offscreen document are completely different, and the issue you mention is why the indirection was necessary.

the purpose of those components being kept in the offscreen document is that the offscreen document is kept alive forever. [the service worker was taking forever to initialize the database and become ready](https://github.com/themoeway/yomitan/issues/292#issuecomment-1784006211), so it had to be moved out of the service worker.

**Comment by toasted-nutbread** [comment]
I see, so it's being treated as somewhat of a stand-in for the old background page where it seems to be always alive. Presumably this is because it is reading the clipboard, which is always running.

My only worry after reading some of the docs is this:

https://developer.chrome.com/blog/Offscreen-Documents-in-Manifest-v3
> To reduce the likelihood of extensions using these as a "background page replacement", only the [chrome.runtime messaging APIs](https://developer.chrome.com/docs/extensions/mv3/messaging) are exposed to the offscreen document.

I.e. that chrome may break something by changing how this feature operates in the future.

In any matter, I don't think using the offscreen window is the wrong choice here, but the codebase could be more clear about what issue it is solving. I'll take this as an action for me to do.
