### ISSUE TITLE
Anki integration: Show all card duplicates

### ISSUE THREAD

**Issue by eloyrobillard** [themoeway/yomitan#610]
## Currently

Suppose you have more than one duplicate of a card in your deck.

### With duplicate checking on

When using Yomitan on the corresponding term, clicking on the book icon will open the Anki card browser for a specific card selected by `nid`.

Said book icon:

<img src="https://github.com/themoeway/yomitan/assets/67062814/422db1f9-7808-43ec-93a6-962b98cd1bf7" width="400"/>

### With duplicate checking off

The book icon doesn't show up, so I can't open the Anki card browser from Yomitan.

## Proposal

Instead of `nid:<id>`, filter by deck/field/other such that all cards corresponding to the term are displayed.

Something like: `deck:"<deck-name>" <field-name>:<term>`

## Intended Use

I often have duplicates for terms that change meaning given the context. 

Clicking filtering them out from Yomitan would help me figure out if I found yet another use of the term, or if that use is already covered.

### Example

Let's use 何分 as an example. 何分 has 3 meanings:

1. a little
2. please
3. anyhow

Now suppose I already have a card for 2 of the uses, but forgot which ones. 
Using this enhancement I could quickly check which, and decide whether I have found an example for the remaining meaning or not.

**Comment by toasted-nutbread** [comment]
Is this not already a thing? There is an option to change the scope that card duplicates are searched for:
![image](https://github.com/themoeway/yomitan/assets/11037431/9e57f9e7-1907-4344-821d-6e4ef8d9fa6f)

And you can already right click on the button to list the duplicates:
![image](https://github.com/themoeway/yomitan/assets/11037431/72b56774-0765-42c6-abdf-dcb481bc8f52)
![image](https://github.com/themoeway/yomitan/assets/11037431/246db636-d7cc-4bed-8cbb-066eb86f15c1)

**Comment by eloyrobillard** [comment]
Oh! I had no idea this feature existed. 

On the other hand it's slightly different from what I had in mind: when I click either of the entries, it just filters the Anki browser by `nid`, and not by term.
This makes sense given the UI in your screenshot, but doesn't match my use case.

(for a different issue: maybe the list could be displayed by default when clicking on the book icon, otherwise it's hard to know the feature even exists)

**Comment by MarvNC** [comment]
In Anki, you can search `nid:${id1},${id2}` to search multiple notes at once. Perhaps this could be done to show the list of all matching notes by default.

**Comment by eloyrobillard** [comment]
If we don't want this as the default behavior, it can just be a special entry in the "right-click list":

```
View all notes...
Note 1: <some-id-1>
Note 2: <some-id-2>
```
