### ISSUE TITLE
Introduce more lints from eslint-plugin-unicorn and eslint-plugin-sonarjs?

### ISSUE THREAD

**Issue by djahandarie** [themoeway/yomitan#615]
Regarding https://github.com/themoeway/yomitan/pull/584#discussion_r1476878318:

> Use spread `[...this.languages.values()]`

@toasted-nutbread I found this lint https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-spread.md which seems to capture your advice here.

That unicorn plugin seems to have [a lot of other potentially useful lints](https://github.com/sindresorhus/eslint-plugin-unicorn/tree/main?tab=readme-ov-file#rules) too, would you like to take a look at it and see which ones you agree with? I'm mostly fine to go with your opinion on what lints we use, but if there's anything you're on the fence on feel free to raise it and I'll add my opinion.

---- 

Also regarding https://github.com/themoeway/yomitan/pull/600#discussion_r1475483957:

> return the math.floor value instead of assigning and returning

I found https://github.com/SonarSource/eslint-plugin-sonarjs/blob/master/docs/rules/prefer-immediate-return.md. Same story here that sonarjs seems to have lots of other potentially useful lints that might be worth adopting.

**Comment by toasted-nutbread** [comment]
I'll take a look at them. I've used the sonar one before, so I think there is some good stuff in there. In general, there's a few things I should do with our eslint file, since I recently figured out what one of the issues was related to fully typed typescript analysis. I'll look into these as well as part of that.
