### ISSUE TITLE
Allow Yomitan Search to Be Installed as a PWA for Mobile Devices

### ISSUE THREAD

**Issue by MarvNC** [themoeway/yomitan#622]
https://github.com/themoeway/yomitan/compare/master...MarvNC:yomitan:pwa

I tried to do this so that it could be added as a homescreen app on mobile devices. However it never seems to work, probably having to due with these errors and secure origin stuff. If anyone has some insight that'd be cool, or maybe it's simply not possible.
![chrome_Yomitan_Search_-_Google_Chrome_2024-02-02_21-23-03](https://github.com/themoeway/yomitan/assets/17340496/f7674e98-f6d9-4103-9cbd-2184335cd544)

**Comment by Renji-XD** [comment]
Not possible - one requirement is that both service worker and site are served via https

**Comment by MarvNC** [comment]
that's unfortunate :( thanks for confirming.
