### ISSUE TITLE
ignore html soft hyphen when scanning

### ISSUE THREAD

**Issue by StefanVukovic99** [themoeway/yomitan#633]
![image](https://github.com/themoeway/yomitan/assets/24891609/1795c04a-1845-459e-a815-a3ce11e1e851)

The soft hyphen `&shy;` is preventing scanning of some texts. I can look into this, but could use some pointers on what I should change.

**Comment by toasted-nutbread** [comment]
https://github.com/themoeway/yomitan/blob/6b327e0b7a7e8c91f1a7d99520c8769863228074/ext/js/dom/dom-text-scanner.js#L464-L479
I believe it's this, look at the zero-width stuff in there
