### ISSUE TITLE
Add sentence when adding an anki card from a child popup

### ISSUE THREAD

**Issue by cristian428** [themoeway/yomitan#639]
It'd be really useful if when opening a child popup and clicking the add an anki card button, the sentence being scanned could be added, just as if you're in the parent popup. Really useful for when learning Japanese, you need to look at an alternative form of a word or phrase through a child popup or when learning Chinese, if you need to hover over the simplified/traditional character you can automatically add the original sentence from the text being scanned.

**Comment by Kuuuube** [comment]
The `{sentence}` handlebar will do this.
