### ISSUE TITLE
Allow multi-line values for the front / back of Anki cards

### ISSUE THREAD

**Issue by mcsantiago** [themoeway/yomitan#653]
Currently in Yomitan 24.01.14.0 only a single line allowed for defining the card format.

<img width="734" alt="image" src="https://github.com/themoeway/yomitan/assets/8943898/d907e81c-bfb6-4aa9-9776-5aaf937ecfce">

I would like to be able to define the front to be something like:
```
{expression}
{pitch-accents}
{audio}
```

Maybe I'm missing it in the documentation or UI somewhere.

**Comment by Kuuuube** [comment]
The proper way to do this is to create more fields for your cards in anki. Then in the anki card template you can arrange the fields in any way you want.

See: https://docs.ankiweb.net/editing.html and https://docs.ankiweb.net/templates/intro.html
