### ISSUE TITLE
Yomitan should ship with dicts installed / an easy way to install dicts that doesn't involve navigating to the github 

### ISSUE THREAD

**Issue by JulianJapan** [themoeway/yomitan#660]
Right now when you install yomitan you get greeted with a massive, overwhelming welcome screen, then you have to find the part where it talks about you being able to find dictionaries on the homepage. On said homepage you then gotta find a link to a separate dictionary docs where you finally can download (and then install) the standard dictionaries. (and this all assumes that you read through the welcome page without just clicking off / feeling discouraged by a wall of text ^^)
It kinda feels like it is assumed that you aren't going to read all this anyway as you are likely setting this all up while reading a dedicated guide. 

It should be a lot easier (& less work) to find and install the standard dictionaries, maybe even install them via a few clicks within yomitan 

(would it be possible to avoid having to install them on your machine? pre-installed standard dictionary combinations via dbs? like jitendex + kanjidic?)

**Comment by MarvNC** [comment]
Related: #470

**Comment by MarvNC** [comment]
Having options of dictionaries that can be one-click installed would be cool. 

For example there could be a built-in list of free dictionaries such as Jitendex and KANJIDIC (and others) that could have their latest release fetched from Github and installed in one click. Could be worked in with an auto-update from Github feature as well.

**Comment by donkuri** [comment]
I am not sure about shipping dictionaries with Yomitan, but a one-click free dictionary install would be great. If the auto-update from GitHub can be implemented, then we can avoid update issues so that would be best.

**Comment by brishtibheja** [comment]
> Some users do not even know how to navigate through GitHub or Discord to find download links

数年前の私ですねw

**Comment by jamesmaa** [comment]
Implemented in #991
