### ISSUE TITLE
Add an option to scan when selecting/highlighting text.

### ISSUE THREAD

**Issue by mireimu** [themoeway/yomitan#681]
Would be useful for touch users if there was an option to scan on highlighting text rather than on hover(tap).

**Comment by brishtibheja** [comment]
賛成です。アドオンの今の状態じゃスマホでスワイプするのはちょっと難しいかな。この機能があれば助かります。

**Comment by Wyzmic** [comment]
If you highlight text and yomitan pops up then you probably won't be able to copy any japanese text at all. Also these settings seem to work best, for me at least, could give it a shot if anyone's interested. 
![Screenshot_20240213_172314_Kiwi Browser.jpg](https://github.com/themoeway/yomitan/assets/72083780/a5b26caf-4589-426f-a160-1f2fbf232cf3)

**Comment by yogurtroyale** [comment]
> If you highlight text and yomitan pops up then you probably won't be able to copy any japanese text at all. Also these settings seem to work best, for me at least, could give it a shot. ![Screenshot_20240213_172314_Kiwi Browser.jpg](https://private-user-images.githubusercontent.com/72083780/304461868-a5b26caf-4589-426f-a160-1f2fbf232cf3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4ODU0MjcsIm5iZiI6MTcwOTg4NTEyNywicGF0aCI6Ii83MjA4Mzc4MC8zMDQ0NjE4NjgtYTViMjZjYWYtNDU4OS00MjZmLWExNjAtMWYyZmJmMjMyY2YzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDA4MDUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1Mjc0NzE2Y2Y1MmRhMDkzZjA2Yjc1MzEzNzViMjQzN2I1ZTZkNzI2Mjk4NWI0YjEwNjJkN2ExZTBlY2QyYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3XCHGtSTh0qmPo7F7KZFgpMtRxhjYRzZSVBafmeehFw)

My settings don't have options like this, how are you seeing these?

**Comment by jamesmaa** [comment]
This is done via #1028 and the keyboard shortcut `Scan Selected Text`

**Comment by ActionBasto** [comment]
> This is done via #1028 and the keyboard shortcut `Scan Selected Text`

where do i find this option? sorry i'm not understanding.

**Comment by MarvNC** [comment]
I don't think this is done, mobile users can't use keyboard shortcuts easily. I believe the issue was asking for the popup to search on any text selection without keyboard input.

**Comment by Kuuuube** [comment]
jmaa almost certainly is referring to being able to select text and in the context menu scan with yomitan. Unfortunately, android browsers do not allow extensions to add things to the context menu due to the system context menu being the same as the one used in the browser.

As for scanning any time text is selected, that probably isnt a very good solution.

**Comment by ActionBasto** [comment]
i think there is a need for a more deliberate solution for yomitan on mobile. in it's current state the only 3 ideas that work for me are

a. turning it off until needed, which is very slow
b. only enabling on specific sites, which isn't nearly as convenient when browsing casually
or 
c. having a secondary browser with it enabled all the time

none of these solutions are great, but with it enabled normally it makes some sites near impossible to navigate with any settings i've tried.

**Comment by MarvNC** [comment]
> As for scanning any time text is selected, that probably isnt a very good solution.

why? I would really like that as an option.
