### ISSUE TITLE
<br> tag 

### ISSUE THREAD

**Issue by brishtibheja** [themoeway/yomitan#682]
I don't know what is causing it but please have a look at this.
![Screenshot_2024-02-13-10-22-21-219_com ichi2 anki-edit](https://github.com/themoeway/yomitan/assets/136738526/5124686c-1467-4012-bdf2-d0283ff3856e)

The `<br>` tag is not converting to a newline. これ普通なのか 🥲

**Comment by yangmillstheory** [comment]
Could you please add some more information? Details of your setup and at least the word you've looked up. Also, is that a screenshot of Anki or the Yomitan popup?

**Comment by brishtibheja** [comment]
> Also, is that a screenshot of Anki or the Yomitan popup?

That is from AnkiDroid's latest beta. The yomichan popup looks fine to me. Also in case this helps, I am using the dict colorizer css from Marv's repo.

> Details of your setup and at least the word you've looked up. 

I am not a dev so I may miss crucial info. In which case, please let me know. 
I was using 24.2.12.0 ver. of the add on my Redmi 12 phone. 
I mined 身近 from [the second para of this article](https://monstar-lab.com/dx/technology/about-ai/). I was only testing yomichan with various sites and to me it seems the issue persists in 旺文社 and 大辞泉
If there's any particular setting or anything else it would help here please let me know.
Actually as  a sidenote here, It would help us non-techies if there was a "copy debug info" just like they have one for ankidroid.

**Comment by yangmillstheory** [comment]
Thanks for the clarification.

>Actually as a sidenote here, It would help us non-techies if there was a "copy debug info" just like they have one for ankidroid.

You can always file a bug requesting this feature in this repository. It sounds like a decent idea to me. Either that or a having the maintainers create an [issue template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository).

**Comment by brishtibheja** [comment]
@yangmillstheory I sometimes feel like yomichan is a product designed with a tech literate audience on mind. Never seen something where clicking customize opens up a page asking you to put in your own code lol. I don't dislike the customizable part, it's just feels a little un-intuitive to me. Hopefully this will improve with yomitan. btw could you create the new issue for me?

**Comment by yangmillstheory** [comment]
>btw could you create the new issue for me?

No, please do the legwork yourself.
