### ISSUE TITLE
validating dictionary with large term banks fails

### ISSUE THREAD

**Issue by StefanVukovic99** [themoeway/yomitan#683]
**Description**
[kty-de-en 25k.zip](https://github.com/themoeway/yomitan/files/14258827/kty-de-en.25k.zip)
[kty-de-en-5k.zip](https://github.com/themoeway/yomitan/files/14258818/kty-de-en-5k.zip)
These should be the same dict, only differing in number of entries per term bank. Validating the 25k one freezes on 2% with only a console error `Uncaught (in promise) TypeError: Failed to fetch    dictionary-worker-main.js:1`. 

I think I once had this problem on my fork, and it was the zip.js library failing, but I just used smaller term banks since then.

**Browser version**
Chrome 121.0.6167.160

**Comment by Scrub1492** [comment]
Cannot replicate this bug (I'm on Chrome 121.0.6167.185)

**Comment by StefanVukovic99** [comment]
Me neither, maybe it was related to low disk space...
