### ISSUE TITLE
Anki integration `{sentence-furigana}` tag using HTML entities

### ISSUE THREAD

**Issue by harrisonmg** [themoeway/yomitan#686]
**Description**
Recently, only the `{sentence-furigana}` value for Anki cards have started escaping angle brackets with HTML character entities, see below:
![image](https://github.com/themoeway/yomitan/assets/3968357/372b2014-2c75-4174-864b-98e12bff8070)
![image](https://github.com/themoeway/yomitan/assets/3968357/e729ee06-e19a-42c7-81fa-a37df2c1419a)

As you can see, the `{furigana}` field is working fine. I reset my templates for good measure, but here's the template for `{sentence-furigana}` anyway:
```
{{#*inline "sentence-furigana"}}
    {{~#if definition.cloze~}}
        {{~#if (hasMedia "textFurigana" definition.cloze.sentence)~}}
            {{getMedia "textFurigana" definition.cloze.sentence escape=false}}
        {{~else~}}
            {{definition.cloze.sentence}}
        {{~/if~}}
    {{~/if~}}
{{/inline}}
```

**Browser version**
Firefox Developer Edition 123.0b9 

**Yomitan version**
Yomitan (development build) 24.2.12.0

**Exported settings file**
(If you think it might be relevant, create a settings export file using the _Export Settings_ button on the settings page and attach it to this issue.)

**Comment by Kuuuube** [comment]
Even though I marked this as fixed in #722 it isn't exactly back to the way it was before.

Due to the handlebars now properly escaping outputs by default you will need to use `{{{ }}}` syntax to allow unescaped values through.

The handlebars you mention here will need to change to this:
```
{{#*inline "sentence-furigana"}}
    {{~#if definition.cloze~}}
        {{~#if (hasMedia "textFurigana" definition.cloze.sentence)~}}
            {{{getMedia "textFurigana" definition.cloze.sentence escape=false}}}
        {{~else~}}
            {{{definition.cloze.sentence}}}
        {{~/if~}}
    {{~/if~}}
{{/inline}}
```
