### ISSUE TITLE
Enhance progress UI when importing dictionaries

### ISSUE THREAD

**Issue by yangmillstheory** [themoeway/yomitan#691]
Basically the progress UI when importing dictionaries is

>Import Progress 16547654687 of 5646546846546464 rows completed

Enhancements:

1. Display a percentage of progress
1. Display a progress bar (ideally whatever framework that's currently being used already provides such a component)

WDYT? I think 1) would be an easy win; happy to take that on.

**Comment by StefanVukovic99** [comment]
Using the footer popup as mentioned in #465 would do it (this issue is a subset of that one).

**Comment by jamesmaa** [comment]
Isn't this done? Or is it referring to dictionary collection? #940
