### ISSUE TITLE
Duplicated info messages in the title

### ISSUE THREAD

**Issue by cashewnuttynuts** [themoeway/yomitan#709]
**Description**
The warning and error messages displayed when hovering over the Yomitan icon are duplicated.
![image](https://github.com/themoeway/yomitan/assets/52880648/76f93a30-4350-4270-afa0-69d87b1cdae0)
This was mentioned in a previous issue or a conversation on TMW discord, but I couldn't find it. Also, the original conversation did not have clear steps to reproduce.

Steps to reproduce:
1. Have no installed dictionaries
2. Install JPDB Freq dictionary
[Freq.JPDB_2022-05-10T03_27_02.930Z.zip](https://github.com/themoeway/yomitan/files/14323389/Freq.JPDB_2022-05-10T03_27_02.930Z.zip)
3. `Delete all` from the settings
4. Repeat indefinitely

**Browser version**
Chrome 121.0.6167.185

**Yomitan version**
24.1.14.0

**Comment by Paukageo10** [comment]
[Freq.JPDB_2022-05-10T03_27_02.930Z.zip](https://github.com/themoeway/yomitan/files/14367659/Freq.JPDB_2022-05-10T03_27_02.930Z.zip)
Paulagio10
