### ISSUE TITLE
RangeError: Maximum call stack size exceeded when importing dictionary

### ISSUE THREAD

**Issue by dududkrn** [themoeway/yomitan#716]
**Description**
it is the first time i use this yomitan, when i import dictionary, it said 
RangeError: Maximum call stack size exceeded

this problem is only at Cent Browser, when I use Chrome, it will be okay.

I tried to reinstall the yomitan, but it is still not work on Cent Browser

![image](https://github.com/themoeway/yomitan/assets/111353510/38e0e50c-bd5e-44a1-bb8e-d193173e4cc0)

![image](https://github.com/themoeway/yomitan/assets/111353510/4f05dc1a-1ff8-4953-9bce-328f95102b6d)

**Browser version**
Cent Browser
版本 5.0.1002.354（正式版本） （64 位） (Chromium 102.0.5005.167)

**Yomitan version**
Extension version: Yomitan 24.01.14.0
Platform: Windows
Browser: Chrome
Language: zh-CN
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
AnkiConnect version: Unknown (Anki not running or connected)
Installed dictionaries: None installed

**Exported settings file**
(If you think it might be relevant, create a settings export file using the _Export Settings_ button on the settings page and attach it to this issue.)

**Comment by jamesmaa** [comment]
Please reopen if you still experience this issue. Unfortunately I can't say we support Cent Browser. If you can find a way to repro on Chrome, Firefox, Edge, or Brave, please reopen
