### ISSUE TITLE
Apostrophe does not display correctly when exporting to an anki field and not in structured content

### ISSUE THREAD

**Issue by Kuuuube** [themoeway/yomitan#718]
**Description**
The dictionary entry (term: `書影`):
![1](https://github.com/themoeway/yomitan/assets/61125188/73cac679-7252-49f3-b75e-30d190fddc8c)

https://github.com/themoeway/jmdict-yomitan/releases/tag/2024-02-19

The result in anki using the `{glossary}` handlebar:
![2](https://github.com/themoeway/yomitan/assets/61125188/c4e5afb9-f0e0-437c-81c9-b9dea41304bb)

The apostrophe turns into the escape sequence `&#x27;`.

This issue also occurs very noticeably with `<br>` tags in some dictionaries. (#682)

This does not happen when testing on Jitendex leading me to believe it's only an issue when not using structured content.

**Browser version**
Firefox 124.0b1 (64-bit)

**Yomitan version**
Yomitan 24.2.12.0

I also tested this on Yomitan 24.01.14.0 and Chromium 121.0.6167.184. I couldn't replicate the issue on that version of yomitan.

Mansive in the TMW discord reported not having this issue on Yomitan 24.01.14.0 and it only occuring on 24.2.12.0, Testing both versions in Firefox.

**Comment by Kuuuube** [comment]
Bisected this issue to #613

**Comment by harrisonmg** [comment]
Maybe also related to #686
