### ISSUE TITLE
yomitan interprets keybindings when typing in the search bar with fcitx5

### ISSUE THREAD

**Issue by rivke41levp656** [themoeway/yomitan#719]
**Description**
When typing in the search bar with fcitx5 active, yomitan interprets the input as a yomitan shortcut.
For example I have 'j' bound to 'go to next entry', and if I type 'j' with fcitx5 active and the searchbar focused, 
it will put a j in the search box and also executes the 'go to next entry' command.
Is this expected behavior? 
It restricts me to kana input or forces me to type the query elsewhere then copy it into yomitan.
I want yomitan to not interpret keypresses as shortcuts while the searchbox is focused.

**Browser version**
Firefox 122

**Yomitan version**
23.12.29.0

**Comment by andrewsartor** [comment]
Just opened up a PR to address this, as I ran into it as well (vim keybinds for navigating yomitan :) ). If it doesn't get accepted, it's just a one line change so could be easy enough to fix at least for your local install.
