### ISSUE TITLE
Some dropdown menus do not function

### ISSUE THREAD

**Issue by Kuuuube** [themoeway/yomitan#721]
**Description**
Various dropdowns in the `Configure Anki card templates...` and `Configure Anki card format...` menus do not function and show zero items in the list to pick from.

![Capture](https://github.com/themoeway/yomitan/assets/61125188/08b1b924-34e2-4dd8-9a48-73d340f8e68d)

**Browser version**
Chromium 121.0.6167.184, Edge 121.0.2277.128

**Yomitan version**
Yomitan 24.2.23.0

**Comment by StefanVukovic99** [comment]
I think it's introduced in #707 / 6cf38229b

**Comment by djahandarie** [comment]
@toasted-nutbread Any thought on where this bug might be from?

**Comment by toasted-nutbread** [comment]
Oh, I set up this menu in a very stupid way. Will fix.
