### ISSUE TITLE
'word' search resolution does not look behind cursor

### ISSUE THREAD

**Issue by Scrub1492** [themoeway/yomitan#734]
Expected behavior: When I turn on the 'word' search resolution option, I can scan anywhere within a word and it will give the whole word.

It is currently not the case:
(actual)
![image](https://github.com/themoeway/yomitan/assets/52880648/db59b630-8ad3-4d0d-878d-3036256e904f)
(expected)
![image](https://github.com/themoeway/yomitan/assets/52880648/1d84966e-a70f-4ffc-aa33-f9cc900afb1c)

Due to Yomitan only looking up information from after the cursor.

**Comment by Scrub1492** [comment]
The substrings are unrelated to the original word a lot of the time. However, for example, you can search 'polite' from within 'impolite'. @StefanVukovic99 what do you think?

**Comment by StefanVukovic99** [comment]
Oh, I can see how you'd expect that. However the search text is still `scanLength` characters long, starting from the cursor. This setting just controls what substrings of the search text are looked up. 

Your `impolite` example I think highlights a useful feature, being able to deliberately look up a substring. I think looking behind the cursor would better fit a new setting like Scanning > Aim assist.

**Comment by Scrub1492** [comment]
Yeah, I just thought that it is slightly inconvenient to have to aim for the first letter to look up when the word is long, for example `pneumonoultramicroscopicsilicovolcanoconiosis`. (Yes its a meme but a lot of European languages do that)
