### ISSUE TITLE
 Issue with Creating an Entity Using JSON File and yomichan-dict-builder

### ISSUE THREAD

**Issue by FahadHeiji** [themoeway/yomitan#742]
Hello Yomitan Team,

I am currently working on a project that involves creating a dictionary using JSON files with the `yomichan-dict-builder` package. I have a JSON file structure that I tried to convert into an Entity Term with Tags. Here is an example of the JSON structure:

```json
{
  "Word": {
    "Id": 1,
    "Kana": "あい",
    "Writings": [
      {
        "Text": "愛",
        "Class": 0,
        "Parts": [{ "Kanji": 24859, "Reading": "あい" }]
      }
    ],
    "JLPT": 3,
    "Difficulty": 5,
    "Meanings": [
      {
        "Arabic": "حُبّ، وِدّ، مَوَدَّة، مَحَبَّة، مَعزَّة، عِشْق، غَرَام، هَوَى، هُيَام، وَلَه، شَغَف (|بالقراءة|)، وَلَع (|بالفن|)؛",
        "Note": "",
        "Japanese": "そのものの価値を認め、強く引きつけられる気持。",
        "Source": "岩波国語辞典",
        "Pictures": [],
        "Related": []
      }
    ],
    "Categories": [
      { "Id": 9, "Name": "اسم", "ShortName": "" },
      {
        "Id": 26,
        "Name": "اسم يمكن استخدامه كفعل بإضافة する",
        "ShortName": ""
      }
    ]
  }
}
```

I tried to create an example entity using this JSON file and the `yomichan-dict-builder` package. However, I encountered an issue in the tag section when adding a Tag has spaces in it like my case `"اسم يمكن استخدامه كفعل بإضافة する"` (please see the attached image for reference). Could you please guide me on how to fix this issue? Any help or guidance would be greatly appreciated.

Thank you in advance for your time and assistance.

![Screenshot](https://github.com/themoeway/yomitan/assets/114103612/02fad7d7-3ac6-425e-a835-1db9a3923c6b)

**Comment by StefanVukovic99** [comment]
Using `NO-BREAK SPACE` seems to work. 
![image](https://github.com/themoeway/yomitan/assets/24891609/fbcfcc16-bf76-48f8-b944-46c9f9e49e52)
![image](https://github.com/themoeway/yomitan/assets/24891609/e9826d3f-d5e2-4101-8ef7-2177908e7fed)

**Comment by FahadHeiji** [comment]
That's great idea, i will do it right away
