### ISSUE TITLE
English support issue

### ISSUE THREAD

**Issue by Geniusssmit** [themoeway/yomitan#744]
**Description**
I mine word convene and html for the sentence field looks like this
```hearings are<b>convene</b>d,```
spaces are not respected.
![anki_2024_02_29_10_53_44_948_VymPaRzKNB](https://github.com/themoeway/yomitan/assets/24941285/37f3f974-9ae0-4d71-a0f2-370b340b7bca)
I figured something wrong with yomitan's anki template settings {cloze-prefix}<b>{cloze-body}</b>{cloze-suffix}
Any help? 

**Browser version**
chrome 122.0.6261.95

**Yomitan version**
24.2.26.0

**Exported settings file**
[yomitan-settings-2024-02-29-15-19-19.json](https://github.com/themoeway/yomitan/files/14449931/yomitan-settings-2024-02-29-15-19-19.json)

**Comment by Geniusssmit** [comment]
When the update will be pushed? Still suffering from the need to to fix each and every card...

**Comment by Geniusssmit** [comment]
mined "unscrupulous" from
```
emphasizes the woman's aggressive, perhaps unscrupulous, efforts to advance her own interests.
```
got this
```
emphasizes the woman's aggressive, perhaps  <b>unscrupulous</b> , efforts to advance her own interests.
```
space after the word is not needed here

**Comment by Geniusssmit** [comment]
also two spaces before <b> tag for some reason

**Comment by Geniusssmit** [comment]
field ```{cloze-prefix}<b>{cloze-body}</b>{cloze-suffix}```

**Comment by StefanVukovic99** [comment]
Seems to work fine for me, export your settings and send them here. Or try resetting your handlebars templates.

**Comment by Geniusssmit** [comment]
Sorry, I have found the culprit. It was my settings. Everything is fine now.
