### ISSUE TITLE
Redundant code present in my cards (or not?)

### ISSUE THREAD

**Issue by Wyzmic** [themoeway/yomitan#746]
**Description**
I'm unsure if my cards are being created properly. To my untrained eye at least, it seems that there's a lot of redundant code present that is taking up extra space such as `data-sc-name="..."` and `lang="ja"`. Is it how it's supposed to be?

**Browser version**
Microsoft Edge 122.0.2365.59

**Yomitan version**
24.2.26.0

**Anki version**
⁨23.12.1

**Exported settings file**
[yomitan-settings-2024-02-29-21-03-52.json](https://github.com/themoeway/yomitan/files/14453503/yomitan-settings-2024-02-29-21-03-52.json)

`<div style="text-align: left;"><ol><li>character (of a person) | personality | disposition | nature</li><li>characteristics | nature (of a thing, event, etc.)</li><li><span><span data-sc-class="pri" data-sc-name="見出部" lang="ja"><span data-sc-class="外字" lang="ja" style="font-size: 0.6em; vertical-align: super;">＊＊</span><span data-sc-name="見出仮名" lang="ja" style="font-weight: bold;">せい かく</span><span data-sc-name="アクセント" style="font-size: 0.7em; vertical-align: super;"><span data-sc-name="accent0">⓪</span></span>【<span data-sc-name="標準表記"><span data-sc-name="教育漢字" lang="ja">性</span><span data-sc-name="教育漢字" lang="ja">格</span></span>】</span><div data-sc-name="解説部"><div data-sc-name="大語義"><div data-sc-name="語義"><span data-sc-name="語義番号">㊀</span><span data-sc-name="語釈" lang="ja">物の考え方・感じ方や行動によって特徴づけられる、その人独特の性質（の傾向）。</span><div data-sc-name="用例G"><div data-sc-name="用例" lang="ja">「<span data-sc-name="言換" lang="ja"><span data-sc-name="言換M" style="font-size: 0.5em;">△</span>明るい（飽きっぽい・几帳面<span data-sc-name="ルビG" style="font-size: 0.65em; vertical-align: super;"><span data-sc-name="ルビ" lang="ja">(キチョウメン)</span></span>な）</span><span data-sc-name="見出語省略">━</span>」</div><div data-sc-name="用例" lang="ja">「<span data-sc-name="見出語省略">━</span>がひねくれている」</div><div data-sc-name="用例" lang="ja">「<span data-sc-name="見出語省略">━</span>的に〔<span data-sc-name="同意語M">=</span>性格の点から言って〕合わない」</div><div data-sc-name="用例" lang="ja">「<span data-sc-name="語例" lang="ja"><span data-sc-name="見出語省略">━</span>像<span data-sc-name="アクセント" style="font-size: 0.7em; vertical-align: super;"><span data-sc-name="accent4">④</span></span></span>」</div></div></div><div data-sc-name="語義"><span data-sc-name="語義番号">㊁</span><span data-sc-name="語釈" lang="ja">その物事を他と区別する、本質的な特徴。傾向。</span><div data-sc-name="用例G"><div data-sc-name="用例" lang="ja">「<span data-sc-name="見出語省略">━</span>が<span data-sc-name="言換" lang="ja"><span data-sc-name="言換M" style="font-size: 0.5em;">△</span>変わる（あいまい）</span>」</div><div data-sc-name="用例" lang="ja">「国際的な<span data-sc-name="見出語省略">━</span>を帯びる」</div><div data-sc-name="用例" lang="ja">「アマチュア的<span data-sc-name="見出語省略">━</span>が濃い」</div></div></div></div></div></span></li><li><span><span data-sc-name="見出部"><span data-sc-name="見出仮名" lang="ja" style="font-weight: bold;">せい<span data-sc-name="語構成" style="margin-right: 0.5em;"></span>かく</span><span data-sc-name="アクセントG" style="font-size: 0.7em; vertical-align: super; margin-left: 0.25em; margin-right: 0.25em;"><span data-sc-name="アクセント"><span data-sc-name="accent">[0]</span></span></span><span data-sc-name="表記G" lang="ja">【<span data-sc-name="標準表記" lang="ja">性格</span>】</span></span><div data-sc-name="解説部"><div data-sc-name="大語義"><div data-sc-name="準大語義"><div data-sc-name="中語義"><div data-sc-name="語義G"><span data-sc-name="語義Gnum">①</span><span data-sc-name="語釈" lang="ja">その人が生まれつきもっている感情や意志などの傾向。</span><div data-sc-name="用例" lang="ja">「彼とは<span data-sc-name="見出相当部" style="font-weight: bold;">━</span>が合わない」</div><div data-sc-name="用例" lang="ja">「楽天的な<span data-sc-name="見出相当部" style="font-weight: bold;">━</span>」</div></div><div data-sc-name="語義G"><span data-sc-name="語義Gnum">②</span><span data-sc-name="語釈" lang="ja">ある物事に特有の傾向や性質。</span><div data-sc-name="用例" lang="ja">「事件の<span data-sc-name="見出相当部" style="font-weight: bold;">━</span>を解明する」</div></div><div data-sc-name="語義G"><span data-sc-name="語義Gnum">③</span><span data-sc-name="専門" lang="ja">〘心〙</span><span data-sc-name="原綴G" lang="ja">〔<span data-sc-name="原綴">character</span>〕</span><span data-sc-name="語釈" lang="ja">その人特有の行動の仕方、ならびにそれを支える心理的な特性。特に感情的・意志的な側面をいうことが多い。キャラクター。</span></div></div></div></div></div></span></li><li><span><a href="#"><span lang="ja">性格異常</span></a></span> | <span><a href="#"><span lang="ja">性格劇</span></a></span> | <span><a href="#"><span lang="ja">性格検査</span></a></span> | <span><a href="#"><span lang="ja">性格小品</span></a></span> | <span><a href="#"><span lang="ja">性格俳優</span></a></span> | <span><a href="#"><span lang="ja">性格破綻者</span></a></span> | <span><a href="#"><span lang="ja">性格描写</span></a></span></li><li><span><div data-sc-pixiv="parent-link" style="font-weight: bold;"><a href="#"><span lang="ja">←心</span></a></div><ul data-sc-pixiv="summary"><li lang="ja">性格とは、その生物の性質のことである。</li></ul><div data-sc-pixiv="main-text-title" lang="ja" style="font-weight: bold;">概要</div><ul data-sc-pixiv="main-text" style="list-style-type: none;"><li lang="ja">性格という言葉は英語でいうところの「character」に相当する。<br>その生物固有の感情や意思の傾向のことである。<br>その定義は様々であり一律ではない。</li></ul><div data-sc-pixiv="related-tags" style="margin-bottom: 0.4em;"><div lang="ja" style="font-weight: bold;">関連記事</div><ul data-sc-pixiv="related-tags" style="list-style-type: none;"><div lang="ja"><a href="#"><span lang="ja">ヤンデレ</span></a>・<a href="#"><span lang="ja">癒し系</span></a>・<a href="#"><span lang="ja">ツンデレ</span></a>・<a href="#"><span lang="ja">ドM</span></a>・<a href="#"><span lang="ja">癒し</span></a></div></ul></div><div data-sc-pixiv="footer"><span data-sc-pixiv="read-more-link"><a target="_blank" rel="noreferrer noopener" href="yomitan_dictionary_media_1_せいかく_性格_2024-01-29-20-59-01.png" style="cursor:inherit;display:inline-block;position:relative;line-height:1;max-width:100%;color:inherit;vertical-align:middle;"><span style="display:inline-block;white-space:nowrap;max-width:100%;max-height:100vh;position:relative;vertical-align:top;line-height:0;overflow:hidden;font-size:1px;font-size:1em;width: 1em;"><span style="display:inline-block;width:0;vertical-align:top;font-size:0;padding-top: 100%;"></span><span style="--image:none;position:absolute;left:0;top:0;width:100%;height:100%;-webkit-mask-repeat:no-repeat;-webkit-mask-position:center center;-webkit-mask-mode:alpha;-webkit-mask-size:contain;-webkit-mask-image:var(--image);mask-repeat:no-repeat;mask-position:center center;mask-mode:alpha;mask-size:contain;mask-image:var(--image);background-color:currentColor;display:none;--image: url(&quot;yomitan_dictionary_media_1_せいかく_性格_2024-01-29-20-59-01.png&quot;);"></span><img alt="pixiv" src="yomitan_dictionary_media_1_せいかく_性格_2024-01-29-20-59-01.webp" style="display:inline-block;vertical-align:top;object-fit:contain;border:none;outline:none;position:absolute;left:0;top:0;width:100%;height:100%;"><span style="position:absolute;left:0;top:0;width:100%;height:100%;display:table;table-layout:fixed;white-space:normal;font-size:initial;line-height:initial;color:initial;"></span></span><span style="display:none;line-height:initial;">Image</span></a> <a href="https://dic.pixiv.net/a/性格"><span lang="ja">pixivで読む</span></a></span></div></span></li></ol></div>`

![image](https://github.com/themoeway/yomitan/assets/72083780/a1aa6336-2fad-4ae5-bd75-837c11eebf9e)

**Comment by MarvNC** [comment]
> Is it how it's supposed to be?

Basically yes, it was defined that way in the dictionaries themselves. The `data-sc-...` is used to semantically label different sections of the dictionary (could be used for css) and the `lang` is specified to ensure that it's rendered in the correct language (you can also specify other languages like `zh`, `yue`, etc.) Repeated use of `lang` might be a bit overkill but I assume the dictionary converter had some reason for doing it that way.

**Comment by stephenmk** [comment]
> Repeated use of lang might be a bit overkill but I assume the dictionary converter had some reason for doing it that way.

Those [are added automatically](https://github.com/FooSoft/yomichan/pull/2131) by Yomitan when rendering the markup and not necessarily specified by the dictionary.

**Comment by Wyzmic** [comment]
I see, so it's how it's meant to be at the moment. Appreciate the fast response! Keep up the good work guys 🎶
