### ISSUE TITLE
Doesn't work in firefox reader view

### ISSUE THREAD

**Issue by Kellen-wq** [themoeway/yomitan#763]
**Description**
if i open page in [native firefox reader ](https://support.mozilla.org/en-US/kb/firefox-reader-view-clutter-free-web-pages) yomitan popup doesn't appear
example page: https://ncode.syosetu.com/n6407iq/1/

**Browser version**
Firefox 123.0

**Yomitan version**
23.12.29.0

**Comment by Scrub1492** [comment]
It seems that extensions do not work on firefox about: pages. See https://support.mozilla.org/en-US/questions/1365979
