### ISSUE TITLE
Apostrophe to &#x27;

### ISSUE THREAD

**Issue by Geniusssmit** [themoeway/yomitan#765]
**Description**
add a word with definition that has apostrophe, you will get ```&#x27;``` instead of ```'``` on the card.

definition
![image](https://github.com/themoeway/yomitan/assets/24941285/b1a2cda5-6dde-43e7-97a2-cb7f6c5dc729)

result
![image](https://github.com/themoeway/yomitan/assets/24941285/c9d0010a-24f6-4d33-a9ec-c487cafbab26)

html
```<ol><li data-details="kty-en-en"><span class="dict-group__tag-list"><span class="dict-group__tag dict-group__tag--name"><span class="dict-group__tag-inner">v</span></span><span class="dict-group__tag dict-group__tag--name"><span class="dict-group__tag-inner">🇺🇸</span></span><span class="dict-group__tag dict-group__tag--dict"><span class="dict-group__tag-inner">kty-en-en</span></span></span><span class="dict-group__glossary">To skip to the head of a queue without waiting for one&amp;#x27;s turn.</span></li></ol>```

**Browser version**
chrome 122.0.6261.95

**Yomitan version**
24.2.26.0

**Exported settings file**
[yomitan-settings-2024-03-04-11-03-24.json](https://github.com/themoeway/yomitan/files/14480480/yomitan-settings-2024-03-04-11-03-24.json)

**Comment by Scrub1492** [comment]
This issue is resolved by https://github.com/themoeway/yomitan/pull/722. It will likely be fixed in the upcoming release.

**Comment by tomashaddad** [comment]
This bug is happening to me again in Yomitan (development build) 24.2.26.0.

**Comment by Kuuuube** [comment]
> This bug is happening to me again in Yomitan (development build) 24.2.26.0.

My prs to fix this issue were merged in after that build was put out so it's expected that it wouldn't work. It's been over a month now without a new pre release. Hopefully there will be another out soon.

**Comment by StefanVukovic99** [comment]
Closing as this is fixed in the latest release
