### ISSUE TITLE
The `Sentence termination characters` setting doesn't work well

### ISSUE THREAD

**Issue by BilderLoong** [themoeway/yomitan#770]
**Description**
(Describe what the issue is, if it is reproducible, and if possible, how to reproduce it.)
I haven't configured the single quote as the sentence termination characters as the terminator.
![image](https://github.com/themoeway/yomitan/assets/45122720/865ccfb1-f672-48d0-abd5-0341ce71fcc8)
But when I scan the word `donc` in this `Des orages sont également fréquents durant l'été, il vaut donc mieux se munir d'un parapluie.` The result `{senetence}` variable added into Anki is: `été, il vaut donc mieux se munir d` which only contain the part between two `'`.

**Browser version**
I am using Chrome 122.0.6261.112 (Build officiel) (64 bits)

**Yomitan version**
```
Extension version: Yomitan (development build) 24.2.26.0
Platform: Windows
Browser: Chrome
Language: fr
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
AnkiConnect version: 6
Installed dictionaries: JMdict Extra, 研究社　新和英大辞典　第５版, BCCWJ-LUW, CC100, Youtube, 日本語文法辞典(全集), 絵でわかる日本語, 毎日のんびり日本語教師, どんなときどう使う 日本語表現文型辞典, JLPT文法解説まとめ, 語源由来辞典, Pixiv, デジタル大辞泉, 三省堂国語辞典　第八版, 大辞林　第四版, 実用日本語表現辞典, 岩波国語辞典　第八版, 広辞苑 第七版, 故事ことわざの辞典, 新明解国語辞典　第八版, 旺文社国語辞典 第十一版, 明鏡国語辞典 第二版, 複合語起源, アクセント辞典, kty-de-de-ipa, kty-de-de, kty-de-en-ipa, kty-de-fr-ipa, kty-de-fr, kty-de-ipa, kty-de-zh-ipa, kty-de-zh, kty-en-en-ipa, kty-en-fr-ipa, kty-en-fr, kty-en-zh-ipa, kty-en-zh, kty-fr-de-ipa, kty-fr-de, kty-fr-en-ipa, kty-fr-en, kty-fr-fr-ipa, kty-fr-fr, kty-fr-ipa, kty-fr-zh-ipa, kty-fr-zh, kty-ja-de-ipa, kty-ja-de, kty-ja-en-ipa, kty-ja-en, kty-ja-fr, kty-ja-ipa, kty-ja-zh-ipa, kty-ja-zh, kty-en-en, kty-en-de-ipa, kty-en-de, Jitendex.org [2024-02-25], Vicon Ger to Eng, yzk-freq-en-v3, yzk-freq-de-v3, kty-de-en, yzk-freq-fr-v3, Vicon Eng to Fre, Vicon Eng to Ger, Vicon Eng to Jp, Vicon Eng to Trad Chi, Vicon Fre to Eng, Wordset, seth-oald-extra, yzk-freq-en, seth-oald-ipa
```

**Exported settings file**
(If you think it might be relevant, create a settings export file using the _Export Settings_ button on the settings page and attach it to this issue.)
You can use the `フランス語` profile to reproduce this.
[yomitan-settings-2024-03-09-08-03-26.json](https://github.com/themoeway/yomitan/files/14545586/yomitan-settings-2024-03-09-08-03-26.json)

Do I misconfigure it, or is this a bug? If you need more information, please let me know.

**Comment by StefanVukovic99** [comment]
It looks enabled by default, have you tried disabling it?

**Comment by BilderLoong** [comment]
> It looks enabled by default, have you tried disabling it?

I tried disabling it like the below config:
![image](https://github.com/themoeway/yomitan/assets/45122720/22703028-f52a-479e-9c1a-2dc958a17a57)

When scanning the word `donc` in the above example sentence, the result of the `{sentence}` is:
```
`ce it.) I haven't configured the single quote as the sentence termination characters as the terminator. But when I scan the word donc in this Des orages sont également fréquents durant l'été, il vaut donc mieux se munir d'un parapluie. The result {senetence} variable added into Anki is: été, il vaut donc mieux se munir d which only contain the part between two '. Browser version I am using Chrome 122.
```

This is not a desired result, considering I still want to retain other characters as terminators.

**Comment by Kuuuube** [comment]
This appears to be working as expected. If you want `«` to break the sentence you need to add it as a terminator not a quote.
