### ISSUE TITLE
Alternate pitch accent graph styles 

### ISSUE THREAD

**Issue by m-edlund** [themoeway/yomitan#772]
Since I use jidoujisho on mobile and want my cards to look the same on mobile and desktop, I would love an option in yomitan to use the pitch accent graph style of jidoujisho.

The jidoujisho style of graph looks like this:

![image](https://github.com/themoeway/yomitan/assets/44649263/9602c8ba-418b-4199-beb0-f1ef13eb01a7)
![image](https://github.com/themoeway/yomitan/assets/44649263/f60247b1-6f83-4212-ac32-ee478e8322b0)

I imagine the cleanest way to give the option would be to introduce another handlebar ("pitch-accent-graphs-jj" or similar) so as not to interfere with the existing pitch accent graph.

I've already implemented this in my fork to a point where it works for me, and could clean it up for a pull request if there is interest in such a feature.

**Comment by StefanVukovic99** [comment]
completed in #773
