### ISSUE TITLE
Can not load JMdict file downloaded from ftp.edrdg.org

### ISSUE THREAD

**Issue by PucklaJ** [themoeway/yomitan#779]
The file downloaded from [here](http://ftp.edrdg.org/pub/Nihongo/JMdict.gz) uses gzip, but Yomitan requires zip. I tried using gunzip and then zipping it again, but Yomitan fails to read it with the message `Error: No dictionary index found in archive`.

Are there any directory tree and file naming conventions for the zip contents?

**Comment by brishtibheja** [comment]
Just in case you don't you can look up [Marv's repo]()

**Comment by PucklaJ** [comment]
Thanks! This solves the problem, but I will leave the issue open in case someone wants to support gzipped files

**Comment by MarvNC** [comment]
Thanks for bringing this up, but Yomitan is designed to work with a [defined structure](https://github.com/themoeway/yomitan/tree/master/ext/data/schemas) of zip archives containing json files. So it's safe to say this isn't a planned feature or something that would be done in the future.
