### ISSUE TITLE
Duplicate Card Checking NOT working in 2c5af21 compared to 24.01.14.0 (latest release chrome-dev version)

### ISSUE THREAD

**Issue by bewizible** [themoeway/yomitan#788]
**Description**

The issue lies in the difference between versions 24.01.14.0 and 2c5af21. In 24.01.14.0, the duplicate note checking functionality operates across all note types. This means it checks against every note type and premade decks, notifying me if a card has already been added. However, in 2c5af21, the duplicate checking only functions if I've already added the card or if it indicates that the headword already exists within the same type I'm exporting to (in this case, JPMN). It does NOT inform you if the card already exists in a different note type. This behavior persists even if you've set the duplication-scope to Collection.

**Browser version**
Chromium 124.0.6325.0

**Yomitan version**
2c5af21

**Exported settings file**
(If you think it might be relevant, create a settings export file using the _Export Settings_ button on the settings page and attach it to this issue.)

**Comment by Xydez** [comment]
I can confirm that this happens to me as well.

**Comment by peldas** [comment]
Same thing happens here with Deck Root set and using the same note type in two different decks under the same parent deck. Using Yomichan 24.4.7.0 on Firefox 125.0b9.
