### ISSUE TITLE
Are there anyway to style (bold, highlight or underline, etc) the part of the text in the glossary when exporting to Anki.

### ISSUE THREAD

**Issue by BilderLoong** [themoeway/yomitan#789]
## What do I want?

Be able to style some parts of the dictionary glossary when exporting to Anki. 
Like this:
<img width="504" alt="image" src="https://github.com/themoeway/yomitan/assets/45122720/a898c2ff-ecb6-4fde-a6bb-a0bdcbdab480">
## My use scenario
When looking up an expression with multiple meanings in the dictionary glossary, normally, only one meaning is used in the current context. I want to highlight this meaning so that it can help me quickly find the correct meaning when reviewing this card.

**Comment by StefanVukovic99** [comment]
This is similar to #462 

I don't think there is a good way to to this

**Comment by BilderLoong** [comment]
> This is similar to #462
> 
> I don't think there is a good way to to this

Thank you! It is similar to #462. I will close this duplicate issue.
