### ISSUE TITLE
Force selection if word cannot be scanned (scan misses possible words)

### ISSUE THREAD

**Issue by KlugB** [themoeway/yomitan#792]
Sorry if this is a duplicate but surprisingly I could not find any information about this in the FAQ or Issues.

Quite frequently I have the problem that the auto-scan does not select the word I want to look up.

For example, in the sentence パンダくんのせいじゃない ("It is not Panda's fault") it is impossible to look up せい. You can either select のせる or せいじゃ. IMHO it would be very helpful to have some control over the selection of text you want to look up, like an additional modifier key (maybe Ctrl-Shift instead of Shift).

But maybe a solution for this problem already exists, and I just missed it?

Extension version: Yomitan 24.01.14.0
Platform: Windows
Browser: Chrome
Language: de

**Comment by MarvNC** [comment]
Hover over せ and scroll down.

**Comment by KlugB** [comment]
> Hover over せ and scroll down. Or use alt + scroll/arrow keys to skip between dictionary definitions

I tried this, but the shortest term displayed is せいじ. せい does not occur in the list. Also, even if this worked, depending on the length of the term you'd have to scroll _a lot_ sometimes.
