### ISSUE TITLE
Make it possible to hide readings in the search page

### ISSUE THREAD

**Issue by WilsonNet** [themoeway/yomitan#804]
I was using Yomitan's Search Page as a Texthooker page since the Visual Novel that I was playing uses both shift and whell as shortcuts and pressing those keys were causing a lot of headaches.

I noticed that you can't hide the kana readings but it is pretty easy just by adding `display: none`  to `.query-parser-segment-reading` 

I can take this task myself when I find some time.

**Comment by rudnam** [comment]
Shouldn't you already be able to do that through the Popup's custom css?

**Comment by Kuuuube** [comment]
Fixed in #804
