### ISSUE TITLE
No {cloze-body-kana} marker

### ISSUE THREAD

**Issue by Magyarapointe** [themoeway/yomitan#815]
In the GitHub documentation for Anki integration, you list the {cloze-body-kana} marker for Terms
However, it doesn't work, because it isn't defined in the Handlebar.js Anki card template in the Yomitan settings ( and it is not mentioned in the marker help info in the Settings).

Unfortunately, I have no idea how to create it. I modified the {reading} marker definition to work as a substitute regardless of kana-only status, but can you help with the {cloze-body-kana} definition ?

Thank you !

**Comment by Kuuuube** [comment]
This handlebar is currently only available in the latest pre-release. It will come to a stable release at some point but if you need it now try using the pre-release.

**Comment by Magyarapointe** [comment]
I should have taken a better look on github. Thank you !!
