### ISSUE TITLE
RTK dictionary (custom) broken in 24.1.14.0-24.4.7.0 update

### ISSUE THREAD

**Issue by johngavingraham** [themoeway/yomitan#820]
I made a dictionary for keyword -> kanji lookup for Remembering the Kanji - it's an experiment that I'm planning to try and release after I've exercised it a bit more. It worked fine at 24.1.14.0, but breaks with 24.4.7.0, and I'd like to get it working again. (I use this on two computers, after I saw it break on the first I went to the second and took note of the version, forced an update and saw it stop working, so I'm sure it's something between those two versions.)

**I'm aware this might be entirely my problem, but I don't really know how to go about finding what's wrong/how to fix!**

The project is [here][1], the latest version of the dictionary itself is [here][2].

It uses [yomichan-dict-builder][3], which hasn't had an update since I built the dictionary, I'm not a JS dev but the package-lock.json indicates the latest version of my dictionary uses the latest version of the builder (i.e. 2.5.0).

Before, hovering over a kanji would include the entry from this dictionary alongside the other ones - I put it down as a "reading", mostly to keep it separate from other definitions, though I'm aware that's a bit hacky but it gave me what I wanted (i.e. the kanji in its own section in the pop-up, as opposed to just part of another section, if that kanji is also a whole word).

Now, the entries simply do not appear. Deleting and re-importing the dictionary does not fix it, and the import goes fine with no errors. I've also tried updating my browser (Chromium) to no avail. I've had a look at the changelog - I'm a developer but not a web developer, and never worked on Yomitan itself, nothing there jumped out at me.

Any help in what might be wrong or how to find out would be appreciated!

[1]: https://gitlab.com/johngavingraham/yomitan-rtk
[2]: https://gitlab.com/johngavingraham/yomitan-rtk/-/jobs/6274613792/artifacts/browse/artifacts/
[3]: https://github.com/MarvNC/yomichan-dict-builder

**Comment by StefanVukovic99** [comment]
It's because the definitions array is empty. It works if you just change
```json
["一","one","","",0,[],0,""]
```
to
```json
["一","","","",0,["one"],0,""]
```
![image](https://github.com/themoeway/yomitan/assets/24891609/8a224618-d99e-4027-8157-1c148992eeb0).

Other than that, not sure what's best for your use case, but maybe you can turn off grouping term-reading pairs, then your dictionary can have normal readings and not be grouped with others, and/or set the priority on your dict higher so that it shows up on top. Also maybe the kanji_bank format is a better fit, though I guess you'd t hen have to click on the kanji to see the entry.

**Comment by johngavingraham** [comment]
Thanks very much @StefanVukovic99, I'll try that when I can. As for "grouping term-reading pairs", I can't find that in the Yomitan settings, or is that something you'd expect the dictionary itself to specify (i.e. presumably as part of the dictionary builder)?

**Comment by StefanVukovic99** [comment]
It's this setting 
![image](https://github.com/themoeway/yomitan/assets/24891609/ff9b90bc-45f1-41d1-843a-c67dc1f509c1)

**Comment by johngavingraham** [comment]
So adding an empty definition did in fact solve the problem - thanks very much @StefanVukovic99 !
