### ISSUE TITLE
Yomitan spitting out errors when Anki is not opened

### ISSUE THREAD

**Issue by koiyakiya** [themoeway/yomitan#825]
**Description**
I didn't have Anki opened and usually that would just lead to a "Not connected" next to the Anki button, but now it's just spitting out errors (nothing seemed to break). This has never happened to me on any other version before.

**Browser version**
Chrome 123.0.6312.123

**Yomitan version**
2024.4.15

**Exported settings file**
[yomitan-settings-2024-04-16-01-04-30.json](https://github.com/themoeway/yomitan/files/14985487/yomitan-settings-2024-04-16-01-04-30.json)

![image](https://github.com/themoeway/yomitan/assets/149911531/19e8cc2a-1f1d-46c6-af75-81d80a134bc8)
![image](https://github.com/themoeway/yomitan/assets/149911531/2835e574-b738-4440-8e25-7c142c1dc84f)

**Comment by paperclip-dayo** [comment]
Same, Yomitan 24.4.16.0 w/ Edge Dev 125.0.2518.0.
Extension constantly throws up "error" icon and spams console with "Anki not connected" when scanning words.
I have Anki integration disabled and never used it to begin with.
