### ISSUE TITLE
Bypass validation with dev approved hash

### ISSUE THREAD

**Issue by Ceynou** [themoeway/yomitan#828]
(Describe the feature or change)
I don't know how validation works and what it implies and how fast it has become since yomichan but if we could skip the validation by verifying that the hash of the dictionary(zip) matches with the one that the developers added to their whitelist(?), maybe that would save us some times?

**Comment by Kuuuube** [comment]
Maintaining a list of valid dict hashes feels out of scope. There are also occasionally dict format changes that if not caught could result in corrupting someone's yomitan database by not validating.

**Comment by Ceynou** [comment]
> Maintaining a list of valid dict hashes feels out of scope. There are also occasionally dict format changes that if not caught could result in corrupting someone's yomitan database by not validating.

Understandable, dict format changes would also imply whitelist reset or not pushed to master until the hash tests are successful, which makes it even more out of scope... Maybe we could asign someone to that particular task, idk...

I can't get past jpdb freq list and other dictionaries' validation step on my Bigme b751 ereader 😔

**Comment by MarvNC** [comment]
> I can't get past jpdb freq list and other dictionaries' validation step on my Bigme b751 ereader 😔

try exporting your dictionary collection from your pc and importing it in the reader, it bypasses those steps.

**Comment by Ceynou** [comment]
> > I can't get past jpdb freq list and other dictionaries' validation step on my Bigme b751 ereader 😔
> 
> try exporting your dictionary collection from your pc and importing it in the reader, it bypasses those steps.

But I thought the collection import resulted in slower lookups, was this fixed?

Also I don't even know why I talked about asigning someone to that task it should be totally automated, maybe I'll try to make a pull request if I ever get into this project

**Comment by MarvNC** [comment]
> was this fixed?

never was confirmed/benchmarked. I imported ~100 dictionaries on my 4GB ereader and lookups are okay.

**Comment by Ceynou** [comment]
> > was this fixed?
> 
> never was confirmed/benchmarked. I imported ~100 dictionaries on my 4GB ereader and lookups are okay.

Alright thanks, I'll stick to collection import now
