### ISSUE TITLE
yomitan for firefox android

### ISSUE THREAD

**Issue by JunkyardCat** [themoeway/yomitan#834]
(Describe the feature or change)
make yomitan work for firefox android version

**Comment by Kuuuube** [comment]
Yomitan does work on firefox android. What issues are you having with it?

**Comment by JunkyardCat** [comment]
ye i tried searching the store and found it. 
does it work in incognito mode? i tried pressing on some jp words and its not showing up. it works good on normal mode
also how much of a battery drain is it to leave it on and scan keys to none. will it trigger every time i touch a word jp/eng?

**Comment by Kuuuube** [comment]
You need to allow the addon to work in "incognito mode". Go to `Settings` > `Add-ons` > `Yomitan` and enable `Run in private browsing`.

The battery drain should be negligible. It does try to scan when you tap but there aren't any intense calculations running that would drain battery a lot.

Closing this as it appears to be resolved.
