### ISSUE TITLE
Support S Pen for Samsung Galaxy S* Ultra phones

### ISSUE THREAD

**Issue by Lolle2000la** [themoeway/yomitan#838]
I use a Samsung Galaxy S24 Ultra, which comes with a S Pen. However, using that pen for pen inputs under advanced inputs does not currently work on Firefox for Android. If possible, I would like to use my pen to select words instead of normal touch input.

Settings: [yomitan-settings-2024-04-18-14-20-09.json](https://github.com/themoeway/yomitan/files/15027223/yomitan-settings-2024-04-18-14-20-09.json)
Version: Yomitan 24.4.16.0

**Comment by Kuuuube** [comment]
Does your pen detect as a touch input or anything at all? Yomitan has no control over what type of input events are sent by the browser.

**Comment by Lolle2000la** [comment]
Is there some way to check that? I don't know how to.

**Comment by Kuuuube** [comment]
You can use this to check for pen events https://patrickhlauke.github.io/touch/pen-tracker/. If you put your pen on it and nothing happens it probably isnt using pen events.

If your pen is using touch events you should be able to use the touch section of events in otd. If it still doesnt work with that it's likely a firefox issue not a yomitan issue.

**Comment by Lolle2000la** [comment]
Ok, it seems firefox does not recognize those events. I think I will open a ticket with firefox if that might bring success.

Thank you for your help!

**Comment by Lolle2000la** [comment]
I have filed a ticket via Mozilla's bugzilla portal, which ended with the following issues:
[https://webcompat.com/issues/136105](https://webcompat.com/issues/136105)
[https://github.com/webcompat/web-bugs/issues/136105](https://github.com/webcompat/web-bugs/issues/136105)

**Comment by Kuuuube** [comment]
Closing as the upstream bugs appear to be fixed https://bugzilla.mozilla.org/show_bug.cgi?id=1892537.
