### ISSUE TITLE
Add benchmark suite & call it in CI

### ISSUE THREAD

**Issue by djahandarie** [themoeway/yomitan#87]
There are a couple of performance-related issues in the tracker, so I think it'd help the maturity of the project if we had a simple benchmark suite of a few of the most important top-level functions (db lookups, scans, popup generation with long amounts of text, etc) to start, so we could track improvements and regressions in our PRs.

Many of the things in `test/` could probably be converted into benchmarks, though we'd likely need to adapt each of them to actually be working on a realistically large input for them to be representative of real-world usage.

References:
* https://github.com/benchmark-action/github-action-benchmark
* https://benchmarkjs.com/

**Comment by siikamiika** [comment]
I can try to do this

**Comment by Scrub1492** [comment]
vitest supports bench functions: https://vitest.dev/api/#bench
