### ISSUE TITLE
Chrome: Yomitan Icon displays error upon scanning any text

### ISSUE THREAD

**Issue by ShufflerousB** [themoeway/yomitan#878]
**Description**
Whenever any text is scanned using Yomitan the window will open after a delay and for practical purposes everything works, but the icon in Chrome will nonetheless display a red box, "Yomitan - Error" on hovering over the icon with mouse, and refuses to elaborate when clicked on.

**Browser version**
Chrome: Version 124.0.6367.93 (Official Build) (64-bit)

**Yomitan version**
Yomitan 24.4.16.0

**Exported settings file**
[yomitan-settings-2024-05-03-04-13-32.json](https://github.com/themoeway/yomitan/files/15196155/yomitan-settings-2024-05-03-04-13-32.json)
![image](https://github.com/themoeway/yomitan/assets/138436845/6330b96f-2d63-4f19-a097-1fa6a5de1674)

**Comment by StefanVukovic99** [comment]
This should be fixed in #843
