### ISSUE TITLE
Passive and potential forms should not be able to be combined

### ISSUE THREAD

**Issue by peldas** [themoeway/yomitan#896]
**Description**
In Japanese grammar it is not possible to combine the 未然形 of られる twice – for example instead of 食べられられる ❌ it would be correct to say 食べられることができる ⭕. Attached is a screenshot showing Yomitan attempting to deinflect a typoed verb as potential-passive which is impossible.
![image](https://github.com/themoeway/yomitan/assets/13115959/2949226e-d229-4a81-b8de-6e6a62524e11)

**Browser version**
126.0b9 (64 ビット)

**Yomitan version**
24.4.16.0

**Comment by StefanVukovic99** [comment]
This should be relatively easy to fix, and seems logical, but just to be sure, could you find any source that this form is impossible in all cases?

**Comment by Lyroxide** [comment]
> 食べられられる ❌

That is possible.

Source: https://detail.chiebukuro.yahoo.co.jp/qa/question_detail/q1085025955 (Best Answer)

**Comment by jamesmaa** [comment]
Is this a real bug? Please re-open if so
