### ISSUE TITLE
Remove unused `data-parent-distance`

### ISSUE THREAD

**Issue by jamesmaa** [themoeway/yomitan#899]
My understanding is that this attribute is not being used. The task involves documenting the original use case of why `data-parent-distance` is introduced (avoiding [chesterton's fence](https://en.wiktionary.org/wiki/Chesterton%27s_fence)) and if it's truly unneeded, removing the instances in which it occurs. You can write the context onto this issue or in the PR

**Comment by StefanVukovic99** [comment]
looks used
![image](https://github.com/themoeway/yomitan/assets/24891609/e846bde7-fc82-437f-800e-1ff6e4a616d5)
