### ISSUE TITLE
Silence playwright message on success.

### ISSUE THREAD

**Issue by jamesmaa** [themoeway/yomitan#900]
Every time we have a PR we get a `No visual differences introduced by this PR.` message by Playwright. This is kind of noisy for a large chunk of PR's and simply not useful information on the cases in which nothing was introduced. This task involves reading the Playwright documentation and figuring out if we could silence this on success and only show when visual changes ARE introduced

**Comment by djahandarie** [comment]
FWIW, it was intentional to include the message when I made the pipeline, to ensure that we could differentiate between success and the action subtly breaking. But maybe it could be replaced with adding a 🚀 reaction or something when it passes so we know it's functioning
