### ISSUE TITLE
Make onKeyDown logic more readable

### ISSUE THREAD

**Issue by jamesmaa** [themoeway/yomitan#918]
The logic in `search-display-controller.js`'s `onKeyDown` logic is difficult to reason about. Task is to either simplify this logic or make it easier to read/reason about. A test or some way to verify it preserves behavior is very ideal

Related discussion: https://github.com/themoeway/yomitan/pull/914/files#r1597534169

**Comment by brandonrainey** [comment]
Thanks for putting up these good-first-issues! I have a easier to reason about version made, just trying to figure out writing a test for it.
