### ISSUE TITLE
Edge Store Release

### ISSUE THREAD

**Issue by MarvNC** [themoeway/yomitan#923]
It would be cool if Yomitan was also distributed on the Microsoft Edge store someday.

**Comment by jamesmaa** [comment]
What work would it take to make this happen?

**Comment by MarvNC** [comment]
There seems to be an [action](https://github.com/marketplace/actions/publish-edge-add-on) for it so it would probably be Darius doing the admin work of setting up an account with the Edge store and creating workflows for it.

**Comment by MarvNC** [comment]
[Edge addon published](https://microsoftedge.microsoft.com/addons/detail/yomitan/idelnfbbmikgfiejhgmddlbkfgiifnnn)

**Comment by jamesmaa** [comment]
done
