### ISSUE TITLE
compatibility issue between Calibre's web content server (Chrome) and Yomitan

### ISSUE THREAD

**Issue by biho1217** [themoeway/yomitan#927]
I've been enjoying reading e-books using Calibre's web content server (Chrome) and Yomitan. 
However recently, scanning suddenly stopped working.

I tried to find a way to downgrade the version of Yomitan, but I couldn't find it. Is there any possible suggestions to solve this problem?

**Comment by jamesmaa** [comment]
I can reproduce the same issue but unable to figure out why this is occurring. In the meantime if you want to downgrade you would have to install the extension manually from the release page. Here was the last stable version https://github.com/themoeway/yomitan/releases/tag/24.4.16.0

I assume this issue occurs from the latest version? Could you past your debug info?

**Comment by jamesmaa** [comment]
I see the error 
```
Blocked script execution in 'about:srcdoc' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.
about:srcdoc:1 
```

in the console when I try to scan. I'm not sure if this _wouldn't_ occur in the previous version

**Comment by jamesmaa** [comment]
I'm also unable to scan in the 24.4.16.0 version of yomitan

**Comment by jamesmaa** [comment]
Can you also report your version of calibre? I wonder if they did something to break this

**Comment by biho1217** [comment]
I tested current yomitan version with calibre version of 6.24.0 / 7.3.0 / 7.10.0. They all didn't worked
I downloaded yomitan version of 4.16.0 and it gave me errors too. I am testing more..

**Comment by biho1217** [comment]
I was able to read books with calibre version 6.24.0
