### ISSUE TITLE
The scanning is case sensitive, so if the first letter is capital it doesn't detect it.

### ISSUE THREAD

**Issue by YossefGamerr** [themoeway/yomitan#946]
Is there a way to make the scanning not case sensitive?

if the word is written "Vrouw" it isn't detected, because in wikitionary it's written as "vrouw"

**Comment by StefanVukovic99** [comment]
What version of yomitan are you on? (You can check via the `About` button in the bottom left of settings)
If you select `Dutch` from the language dropdown, it should handle capitalization.

**Comment by jamesmaa** [comment]
@YossefGamerr please reopen this issue when you have more context to provide
