### ISSUE TITLE
Add documentation for multilanguage support

### ISSUE THREAD

**Issue by jamesmaa** [themoeway/yomitan#947]
We're getting inbound questions about whether yomitan supports _ language. Let's add a section in the README mentioning multilanguage support and a table indicating which ones are supported and what degree

**Comment by brishtibheja** [comment]
What do you guys think about changing the description to remove the word Japanese in \"Japanese pop-up dictionary browser extension\". This is in the top of the main page.

**Comment by jamesmaa** [comment]
Done in #1183
