### ISSUE TITLE
Why is the TTS service not available for all langauges? and how do you add Audio from websites like DutchPod101?

### ISSUE THREAD

**Issue by YossefGamerr** [themoeway/yomitan#948]
so yeah, the TTS is only there for some languages, and is there an option to add audio from websites like DutchPod101 just like how the extension has JapanesePod101??

**Comment by MarvNC** [comment]
> TTS is only there for some languages

The TTS voices are provided by the SpeechSynthesis API from your browser. I recommend using Microsoft Edge as it has many TTS voices for pretty much every language. Your selection will be quite limited using other browsers.
