### ISSUE TITLE
Yomitan freezing on setting import

### ISSUE THREAD

**Issue by artjomsR** [themoeway/yomitan#950]
**Description**
In the past, I've had issues with Yomitan freezing on launch. It was working for me on 13th May, but the next day it started freezing again. I've reinstalled it, but now I can't import my previous settings. Yomitan just freezes. I've tried leaving it for 10 mins to no avail. I've done an import some time ago in the past and I don't recall it being so long

I'm attaching both most recent backup and the 1st one I did. I'm pretty sure the one from April worked in the past. I've tried in Firefox and Chrome on 1 machine and vanilla Chromium on another - all freeze for me. As an experiment, I've tried to export the settings from a fresh extension and import that, which worked. So it must be something to do with my original settings

I've initially setup Yomitan testing version around April and switched to stable in the beginning of May. Like I've mentioned, I've had issues with Yomitan freezing on launch in the past (so I couldn't use Yomitan or export my settings). So if this is some sort of one time hiccup, then I could just redo my settings. But I'd hate this to be a recurring issue where I'd need to be regenerating the settings every now and then.

**Replication steps**
As easy as it gets - import one of my backup json files (either as is or with sanitization) 

**Browser version**
Version 125.0.6422.61 (Official Build) (64-bit); Windows 10

**Yomitan version**
Yomitan 24.5.5.0

**Exported settings file**
[yomitan-settings-2024-04-11-09-52-58 - freezes.json](https://github.com/themoeway/yomitan/files/15327260/yomitan-settings-2024-04-11-09-52-58.-.freezes.json)
[yomitan-settings-2024-05-07-12-46-12 - freezes.json](https://github.com/themoeway/yomitan/files/15327261/yomitan-settings-2024-05-07-12-46-12.-.freezes.json)
[export with default settings - works.json](https://github.com/themoeway/yomitan/files/15327262/export.with.default.settings.-.works.json)

**Comment by StefanVukovic99** [comment]
This is probably caused by #936, so this file where I've just manually changed the `searchResolution` to `"letter"`  instead of `"word"` should work. 
[yomitan-settings-2024-04-11-09-52-58-maybe-fixed.json](https://github.com/themoeway/yomitan/files/15331137/yomitan-settings-2024-04-11-09-52-58-maybe-fixed.json)

**Comment by artjomsR** [comment]
thank you so much, that works!
