### ISSUE TITLE
Adding shorcut "Yomitan search" for mobile device ??

### ISSUE THREAD

**Issue by SalwynnJP** [themoeway/yomitan#969]
Currently, is there no other option than :
- open kiwi browser then 3 dots
- open yomitan then "search"
Too long

Is there another way to access instantly without all these steps ?

**Comment by Kuuuube** [comment]
This is not something yomitan can fix. You should be able to bookmark the search page or on some devices you may be able to create a shortcut on your home screen.

**Comment by SalwynnJP** [comment]
> This is not something yomitan can fix. You should be able to bookmark the search page or on some devices you may be able to create a shortcut on your home screen.

Already tried but didn't work

**Comment by Kuuuube** [comment]
That looks like a bug in kiwi then. You should report it to them.

**Comment by SalwynnJP** [comment]
> That looks like a bug in kiwi then. You should report it to them.

ig isn't a bug coz this bookmark is considered as a "website" so that's why it doesn't load the page

**Comment by SalwynnJP** [comment]
Fixed (solved by a widget lol)

**Comment by MarvNC** [comment]
Related: #622
@SalwynnJP can you explain how you did the widget workaround?
