### ISSUE TITLE
"Select matched text" should not select っ

### ISSUE THREAD

**Issue by Lyroxide** [themoeway/yomitan#980]
**Description**
With "Select matched text" option enabled, scanning a word right before the Japanese comma `、` will select the word with the comma.

![b7add2fc-366a-4d52-8863-72906effcc8f](https://github.com/themoeway/yomitan/assets/33834537/99353370-4621-4122-916e-1f6cf7a70627)

**Browser version**
Firefox 126.0

**Yomitan version**
24.5.5.0
Not an issue in 23.11.23.0 (Android Kiwi Browser)

**Exported settings file**
[yomitan-settings-2024-05-20-13-24-20.json](https://github.com/themoeway/yomitan/files/15377532/yomitan-settings-2024-05-20-13-24-20.json)

**Comment by Lyroxide** [comment]
Apparently it is due to my text replacements

![image](https://github.com/themoeway/yomitan/assets/33834537/dde2c098-435b-428c-83c7-b156fe2a0c19)

but I'm not sure if it's intended from https://github.com/themoeway/yomitan/pull/793

There's another similar issue with っ(small tsu) replacement, which is not in my custom text replacements. I thought there used to be setting for that but it's gone?

![image](https://github.com/themoeway/yomitan/assets/33834537/dc9355e2-d211-428a-a703-7ebaadff4492)

**Comment by Geniusssmit** [comment]
I have the same issue with っ
![image](https://github.com/themoeway/yomitan/assets/24941285/7c9bfe01-6a94-4a1e-8803-284e33571e4d)

**Comment by Geniusssmit** [comment]
"　" should also be skipped I think
![image](https://github.com/user-attachments/assets/2eddf89a-0ad6-46ac-9a49-70df9e0e659b)

**Comment by Geniusssmit** [comment]
also mining this this word from this sentence with 
```{cloze-prefix}<b>{cloze-body}</b>{cloze-suffix}```
bolds different characters for some reason
```ボウ<b>フウリ</b>ン総代　梅宮一だ。```
