### ISSUE TITLE
Is there a way to import dictionaries without using deconjugation?

### ISSUE THREAD

**Issue by nuanjanP** [themoeway/yomitan#989]
(Describe the feature or change)

Is there a way to import dictionaries into Yomitan, with the aim of not using automatic deconjugations (but still allow wildcard searches)?

My background is this: I use Yomitan solely for its search page, and can live without automatic deconjugations but would like wild card searches. Concretely for example, I'd like to be able to find `山猫` from `*猫` but I'm fine with having to search for `行く` myself when I see `行きます`.

The reason I'm asking about skipping deconjugations is that, from my understanding, it is this capability that makes importing dictionaries take so long (and perhaps also eat up much more of the storage on the disk). Yesterday I imported a big dictionary ([大辞林 第四版](https://drive.google.com/file/d/12t4MxKOVa79m5Q2RNwDYY-ZUzfG-b69A/view) from [*Shoui's Yomitan dictionaries collection*](https://drive.google.com/drive/folders/1TRylrqtoYi2hW9dAjci5cugNzde_WRTM)) and it took 2 full hours to finish, with the only active application on my computer being Firefox running only 1 tab, namely Yomitan's setting page. During that time, I cannot use my computer at all. This is too much in my opinion.

So I figure if we can choose to import dictionaries with the assumption of not doing automatic deconjugations (but still doing wild card searches), I would appreciate it a lot.

Looking forward to hearing any opinion on this feature.

**Comment by StefanVukovic99** [comment]
The premise is mistaken - the deinflection that happens for Japanese, marked with 🧩, is performed by yomitan on every lookup, regardless of dictionaries installed. 
![image](https://github.com/themoeway/yomitan/assets/24891609/a95177e0-1561-4aa8-9856-92a65c74ea99)
![image](https://github.com/themoeway/yomitan/assets/24891609/05a554ae-c6ec-4ee6-b8ab-3e81dc0487f5)
Dictionaries can contain deinflection information, marked with 📖 when displayed, but I don't think any Japanese dictionaries make extensive use of that right now (as Japanese is agglutinative...)

That said, 2 hours is a lot. Check out #608, firefox is known to be slower I think, what are your device's specs compared to those in that issue? I've never tried the wildcard import but it probably exacerbates the import time

**Comment by nuanjanP** [comment]
Thank you for the clarification.

Comparing the specs, I'd say my laptop is on par with the android phone and way worse than the laptop in that issue. So perhaps it wasn't not strange it took 2 hours. Well, I guess I'll adapt to the issue from next time on. :)

Thank you again for the swift answer.
