### ISSUE TITLE
Hide add card button if enable 'Prevent adding' card.

### ISSUE THREAD

**Issue by foxmean** [themoeway/yomitan#990]
Instead of the current UI:
![image](https://github.com/themoeway/yomitan/assets/13077459/dbee9c43-1e64-48a5-8f2c-76a95aaabbce)
Should we change to something like this?:
![remove-button](https://github.com/themoeway/yomitan/assets/13077459/a4fddf87-5f9e-48b8-b999-b0f11856239c)

**Comment by Kuuuube** [comment]
Having the ui in a consistent order is important. Removing the button instead of disabling it breaks this. If you just want this for your personal use you can add some custom css.

**Comment by foxmean** [comment]
Thank you.
