### ISSUE TITLE
Yomitan is adding extra HTML to (and searching for it in) the Kanji/Expression field, creating undetectable duplicate cards.

### ISSUE THREAD

**Issue by wwly23** [themoeway/yomitan#993]
**Description**
![image](https://github.com/themoeway/yomitan/assets/6302264/b01213ba-4d11-4a60-9951-b7b0c6ef621f)
![image](https://github.com/themoeway/yomitan/assets/6302264/7b7d6df6-6081-4031-be61-e49601107918)
![image](https://github.com/themoeway/yomitan/assets/6302264/3aecc4ac-3653-4ce1-967f-9277d615aef1)

The first image has an extra I think newline compared to the second image.
The second image's card was created by a previous Yomitan version before it auto-updated on May 21, 2024.
The third image was from when I mined it about 1.5 years ago with no problem.

Don't worry about the differing Frequency field. Deleting the extraneous HTML data with the HTML Editor causes it to properly show up as a duplicate in the Card Browser, but then Yomitan doesn't detect the card is in the deck and creates the card in the first image if I click the Plus button to add the "new" card. 

If anyone has any tips on clearing the HTML data from the field that would be very useful. I couldn't get Anki's Find and Replace to remove what I needed to avoid duplicates.

Here's the HTML code of the first card:
` 
 
 
 
 
 
 
 
 

 
 
 
 
 
 
 
 
 
 
 

 
 
 
 
 
 

 
 

温存`
(That kinda failed I think)

**Browser version**
Latest Firefox and latest Chrome, same issue.

**Yomitan version**
Yomitan (development build) 24.5.21.0 for Firefox 
Extension version: Yomitan 24.5.14.1 for Chrome

**Exported settings file**
(If you think it might be relevant, create a settings export file using the _Export Settings_ button on the settings page and attach it to this issue.)

**Comment by Kuuuube** [comment]
All previous cases of this have been due to messed up handlebars. Try resetting them. And if you are using custom handlebars test without them.

**Comment by wwly23** [comment]
Thanks, that was the case.
