### ISSUE TITLE
Yomitan popup is almost unusable on certain sites

### ISSUE THREAD

**Issue by shiki-tm** [themoeway/yomitan#995]
I had noticed awhile ago that yomitan popups wouldn't appear on this one specific Chinese grammar website.
https://resources.allsetlearning.com/chinese/grammar/Expressing_duration_with_%22le%22

I've come across a website for reading Chinese webnovels that is having this problem too. It's very difficult to use yomitan here on Android.
https://story.udn.com/dcstore/Read.do?nid=245984#1,asc

I've checked websites that use simplified characters and some with Traditional characters and that doesn't make a difference, sometimes they worked and sometimes didn't. I checked all my yomitan settings but nothing is really that different from my Japanese profile settings. Touch settings are the same. I've removed Japanese regex patterns and also tested random css and popup settings but no change. I also changed kiwi browser language settings and permissions, turned off block ads/popups, etc but it's the same. I turned off all extensions except yomitan and no luck. Switching to Desktop version of the site changes nothing. Also turned off dark mode and other stuff in chrome flags.

So I was thinking this is something to do with websites containing or formatted for Chinese characters. If I use my Japanese profile I still get the issue on those problem websites. If I use the Chinese profile on Japanese sites or even ttu reader for Chinese books, it works perfectly fine. I checked these websites on my windows laptop and they work fine with yomitan there.
Actually my yomitan settings on desktop and kiwi browser are the same and I was even able to use my touch for pop ups in the problem websites on my touch laptop so maybe it's something to do with kiwi browser actually?

The problem is best explained with the screen recording

https://github.com/themoeway/yomitan/assets/36088384/56ba0cf7-b9a5-49dd-9572-128d4a2fcd03

The only way I can get a popup to actually appear on those websites is by touching and holding a character for a very specific time. Not a quick tap but not too long either. Maybe for like half a second. 

https://github.com/themoeway/yomitan/assets/36088384/af57f54c-516b-47ad-9c04-e224fe3c55f4

Interestingly if I refresh the page, only the first touch lookup works completely normal but any taps after keep having the same problem. 

Actually I'm convinced it might have to do with kiwi Browser since those same websites work even with touch lookups on my window touch laptop. 
I really hope someone can solve this because it makes yomitan almost unusable especially as a beginner one needs to do lots of word lookups.

Kiwi Browser Version 124.0.6327.4

Yomitan version 24.5.14

**Comment by peldas** [comment]
I don't have a fix, but just commenting that both websites work for me with keyboard+mouse on Windows 10 with Firefox version 127.0b7 (64 ビット) with Yomitan 24.5.14.1. I've included a screenshot of my settings in case it helps. This is on my Chinese profile but the language for that profile is set to Japanese.
![image](https://github.com/themoeway/yomitan/assets/13115959/0ed4448d-03ee-4404-befa-5f9a666a9d25)

**Comment by cristian428** [comment]
Thanks for testing on Firefox. The problem persists. I'm convinced it's something to do with kiwi browser

**Comment by Kuuuube** [comment]
This is a browser/site issue with touch handling and focus being messed with. Unfortunately theres not much yomitan can do here. It may be possible to get better scanning if you set yomitan to scan on touch start but that will cause issues with scanning while scrolling. You may also be able to hold a little longer and that can sometimes help in this situation.
